---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 15m
  chart: minio
    spec:
      chart: minio
      version: 13.7.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      main:
        enabled: true
        hosts:
          - host: "minio.test.arneklein.net"
            paths:
              - path: "/"
                pathType: "Prefix"
        integrations:
          certManager:
            certificateIssuer: "domain-0-le-prod"
            enabled: true
