---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 15m
  chart:
    spec:
      chart: minio
      version: 13.7.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      config:
        enabled: true
        type: nfs
        path: /mnt/strawberry/encrypted/backups/minio-s3-backups
        server: 10.42.1.3
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                MINIO_ROOT_USER: ${MINIO_USER}
                MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ingress:
      main:
        enabled: true
        hosts:
          - host: minio.test.arneklein.net
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
