---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-recovery
  namespace: minio-recovery
spec:
  interval: 15m
  chart:
    spec:
      chart: minio
      version: 15.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      stopAll: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                MINIO_ROOT_USER: ${MINIO_USER}
                MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    persistence:
      config:
        type: nfs
        path: ${MINIO_NFS_PATH}-auto-2025-05-31_23-25-clone
        server: ${TRUENAS_IP}
    ingress:
      main:
        enabled: true
        hosts:
          - host: minio-recovery.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
