apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - minio/ks.yaml
  - immich/ks.yaml
  - media
  - paperless-ngx/ks.yaml
  - external-services
  - vaultwarden/ks.yaml
