apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflareddns/ks.yaml
  - external-services
  - immich/ks.yaml
  - kubernetes-dashboard/ks.yaml
  - media
  - minio/ks.yaml
  - nextcloud/ks.yaml
  - paperless-ngx/ks.yaml
  - unifi/ks.yaml
  - vaultwarden/ks.yaml
  - code-server/ks.yaml
  - cloudflared/ks.yaml
  - netdata/ks.yaml
  - drawio/ks.yaml
  - actualserver/ks.yaml
