apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:o9/VxZJLT0WAfv6j3hntz0evo8EscGyxRzp51kHY0KNJoOM3Pv7dNvZHmXmypzLn7LLUmYb7rNaBTqSf8L690pM=,iv:f0XYkiLyviZbBJ/sm2F/isBnK3rVQ5F08PkryWTYZtQ=,tag:5JsmikEt/QvrvVz9xVjg7Q==,type:comment]
    #ENC[AES256_GCM,data:91m7TZASB4bQC5EbXhoCBeh93sekEE/E8STVzNIytWhaVtNXTaSyAQXNMm8=,iv:OLRAtKIaYzF/Hqe0NW7L1XYYSMdsFvbVcoQ24g+YSFw=,tag:0z1iZDgBy2Gq2/p6VmXV+g==,type:comment]
    VIP: ENC[AES256_GCM,data:AZ9zvQo6Co42J+I=,iv:c7twABzba2qdN+xgB8eh7hSLyRBXd3Kv1iUmRP7qFQw=,tag:GIag0dKIolqC/h9VZuWgmg==,type:str]
    #ENC[AES256_GCM,data:IXO6RMfhdOqSY8mEEP7WtmH72O9XDaS6tzzB,iv:GPcnMcyc7wB9xTI7IX96B+btrc4PIelitnC1bw4dwng=,tag:nQrAfqygY1KxT5M3ve4xtg==,type:comment]
    #ENC[AES256_GCM,data:NeeoPweIhEYHGiXmmgGzeYFW/ow3VUn4647dJ1FOHSFchuyXUczmk6P3Q19BleifmQCPbCpDt5D98q/HzXEzlFzMToPM8bPjMIWfyhLpDhvBcAOn+jXPL/M=,iv:2okMf9mcORvEBD73vXgLoObZJ/QIM0VabvWJd+mST8g=,tag:TW3A1srwQEoQasNP5b39iQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:R0nzikACBfYVNaM=,iv:oz55WxvtIG7Ci13mEZfn4tJ04N9QVfdAfa4vaOwihxc=,tag:52r2jmVUJJkCbO1QO04GDQ==,type:str]
    #ENC[AES256_GCM,data:QN84r7Gg7jzlJriO/Oqyd7qAl7phfpmDVee/w1p0KSSFkw==,iv:qCOsPbvcd4eHgT4008OM5QGpGyn60vCYIfl9TQ/ifgI=,tag:VJofAuWiSGDVRugZ54Iuxw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:tIiH9J8pnAHs,iv:n/gVrsouRYTunxTBduAcpnJ031Sy8pBFlQaw4hANZck=,tag:k3vYtvjoVd9HduIYrKqnHQ==,type:str]
    #ENC[AES256_GCM,data:joZ7d1eNFVKkrZD4e4Bi5chp561+aPABhqhRIBd7LK4Zf/xZbszmFKdfymjgsFc=,iv:ZBjCAQB0E7/Fpk30Purvte1kF7b/hnYOmPVf3u356lA=,tag:N/NrGfsM+VPW70dBvJqN8w==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:ZvbWA7+Rrd89zM0/iSDjSPCCNcmSp0M=,iv:SHG2UBM15JgIKkh1tHcCVZ5XcTM9X2Gcm/jQ/6ZeBpk=,tag:QI2ajtqSeNinYMN0NpJkrA==,type:str]
    #ENC[AES256_GCM,data:dqZmOXYnZTNnRHOZ3o1bBcOhBEmWPeBxuE7r2TpJzqd9dTc/M9oRrJb65pMz4cTfU2imH/lGN6HuXCPl8lv76zh1PgTlQtO0rw0NwOvByrLOAw==,iv:HZS6NKasqaylNoluEPv80dXTO0ItK71a0KJf9eBv6d0=,tag:vtQHCi9V+Zp261p/BOnIkw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:oQpEvUZ3E6iMKdM=,iv:piSipfiHyutxKQCNe+wDWMu3tPMvLNYmJOkEMwGSw2k=,tag:EMIfUrqwH5DsmadEI1dXSQ==,type:str]
    #ENC[AES256_GCM,data:L5J4jpTKyMGOh+sWqXAALy+EhPrW+JwovLS+9S2nkliO,iv:AObF7FcWmmQIKsqKqPMG4htIBdNDEbkDYr5NRGMoT+I=,tag:JVGonnSfGcPDTqUJtBARzQ==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:o+8qdRvURKEgzG4=,iv:gg37Gy9iyR0loZU+oS79fYe6yoXHZd+erLFSjFyaoHI=,tag:sqfou21qtlQFi+Q26CFRig==,type:str]
    #ENC[AES256_GCM,data:D77OdoWqmxJc4zrcSR6+fHSXoVwTI26GkrRCtYCKlGaSidGbzmCmS4vJM09Pm1rWyGQkLmd7OtJGZsIBkNWCRGo53ZJkOhjOqkLh6JbF81U=,iv:znEz75hJ5pcsnHdIon5jVr1x2pX6aHCPO7BMh3BA0OA=,tag:4uz7LAV6XxaH7oHcxKoOyA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:I+SezH4EJE51Jvw=,iv:bh9n/cF0jjNPhaCyKLkDeBB+foMzdmePNWMv/9iOzN0=,tag:Ixx7Bxy0xGhKa8s/hY0F2w==,type:str]
    #ENC[AES256_GCM,data:R/ilbGoBDeUnHcItev5Wz3VidNMrfCdyJHe1FGASbd7Vo1+MYgTZX9RmHBoJIHKPXwpXei+J+ZyOenepFUyzgK3ED7Whv7VUi3qSTsUdRdpLNl1T2TzQ,iv:zwKxB5/1ZZROAMiKTAbuS2Ahk4f1AKqDwjJuWxSWjjw=,tag:LkXjohX8kSwnVl/PiGBMag==,type:comment]
    #ENC[AES256_GCM,data:jgw/xDlI+oLha3/fRcZFN6XcAHa6xpf/DQsyOq4CuGg2TqisYMF06TQspr5Je9hUM6U1qsqUzfB/BwswDush6r94dwFCFShhsfiv6XvLvn/M/9uw+FQrS49Mwb23O3UQr2ekRQePfM/olRacePP9OXHbfDe6iOXLqdY6Ug==,iv:5U0ZvO/sAQLcI/6axRcu9mUHzgsUX6M9MeYJrMDyqlo=,tag:aJHK95H6+zauhrdI/oG0SA==,type:comment]
    #ENC[AES256_GCM,data:7KZB1o8jvLlpz8oJSv6MuYQOLDkZXn2R0Jyi/r5ZX3sn0LiLnqynWsUoz5vqN14CgB5uevJgNXQq9u0cwTKuQ38o2px3yaxiVuul7gU666Q=,iv:nPhfyyH0x0U25VvvZa7lnHRikHIUcG7F2LwDpIZdmq4=,tag:7Iy1wPVTGb1uo6+rpseu1Q==,type:comment]
    #ENC[AES256_GCM,data:US3g+Ig1wW1G3MJdghV7/9QvgrUtT5U6Bgk1r74fhlQDuRlnPMbLM11OzxHV5R1BYLVeg7SK,iv:THJqXgHHeN9d0iMTTu4qcLuTx2F6KeiK7G1m+Re/n30=,tag:qN2A/n8qU3q1dkHzaSN9FA==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:uHVsiu3/SJIkQ7m7+A==,iv:Fdu4S7uKqwruE2tMb2Qr80NxbdRYxsaRpAatAkskdeo=,tag:EkEDF3fqSeZtsfniPdg4iQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:gzlPfRhXvaKvP+2dPaA0Wg+U/kE211Xk,iv:gAc2nAH6u+GQEilJYWJ8w/qc2ML7ThQMrycovYzXGsA=,tag:ZsY01si9JMEylq5zcXLTMw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:BmnWtXn+i0DVcJ5Y/2WPF4mqg42L5g8LFvrxOJ/H7LHLKC1bSafQlA==,iv:HEMzDiM98dHbj07UBARCG9XWEjlXFYFu8bW878XVytc=,tag:AC5Tl1Qnco5mvEuu504EBw==,type:str]
    #ENC[AES256_GCM,data:oRcYL9YZo/QxCZjVatmegfYIGqDHqX72EihFB0VKcEuNHzMFJufNyhjUIKdaq8h1/PMAY++TQUE=,iv:+cIAZa9ew01rE+slIX6JpcgJ7VwEvaWAWv4b3V+Xh98=,tag:RLcXhoID5BU2P0F9oNu+9Q==,type:comment]
    #ENC[AES256_GCM,data:edwQ36k5Ww4Knz0dxqtBzO9ukKqhfxW38A==,iv:BtGgyaEBUud+u/Cr+9gMCKJgO/0KBpsaKjxuI6bbT9M=,tag:iy7BH+QJL9bEvUnlhBkvPQ==,type:comment]
    #ENC[AES256_GCM,data:pKkQDnATkMSuX9i+QWgxCJD/GLV+PBCGpUiamkSboAGvnCtMuFq9ZKkCCI1mWTfjpE+i5TaFpmC0fTUZYtRD+or0So0ghgR4zEcetwU=,iv:f6vnEax6vBTfePcpRbbI7U+Iw4UhETP1ts9dXm+IoXg=,tag:CqCJUm6/VotrM7uh2YV6/Q==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:dHTPSWwlV4O3HSc9zrviKFTK3I0sH1Y2RY2LJKPDE9Ezho23eFXefdbzsifAB0AK,iv:VoUzRDlhwqBc58FiTkMIEaeZ22zl7mDQsjTqOGf0GZ8=,tag:ux8+KZvow58EjEdvrLAWSQ==,type:str]
    #ENC[AES256_GCM,data:g+W6SWpnxP1GrxuVQGvB7FKJE8NU4szVfrZqM5qUYkzCPo88OVBuhEbCPiuPO2j97uIgdAPjVTi9LSrVBzwsH+D/E2lzbe4=,iv:aipHhE2BFBwYiQwzX4HlHa+LDevpiHozqBc7FtT1+3o=,tag:SfcJxwdWSBRBKryvSo80hQ==,type:comment]
    #ENC[AES256_GCM,data:vhNPgoPuTP24kn2iKaj37o3mUk5PSHC1UsJcQQBse2A0t7v8XhR58xzX4CRwm4BO0VM5+l3X,iv:xSDXdKez/0hIDGMXITdfJXxWsaK4RURWh3FkoDkWgA0=,tag:TvgLdOVOE+L/eye/UADlkQ==,type:comment]
    #ENC[AES256_GCM,data:9vhSmQHux4wB4T7zHa7dnimUuyX9n8csXld4BV/1w033kfE=,iv:38Xl2VnRyJDXRkt59G3pgQcVAFz3X/hLgNwxD3c898c=,tag:0oIEyt4Kb4uZJl3QYIfJkw==,type:comment]
    #ENC[AES256_GCM,data:ei+INdMueHjkcJraQoFRzNFeZ2sPPdyTXeooC6xN3Sxk82a/Nfyj,iv:PCZHKEY5IphiPY91iIx0NSoHDGsoXG+Wbt/IWldY40w=,tag:OigRj+Rm6p59OK5kYpQ/5A==,type:comment]
    #ENC[AES256_GCM,data:zVHg5O5a9V9TCAASEZg=,iv:rNhNaeNSiIFrsepozFryueBgOQhuQiS9hUnITiEozVM=,tag:XLpfHoSxKaz9uNdnVXYMVA==,type:comment]
    PODNET: ENC[AES256_GCM,data:b2sRAF8j9XfIhsKtkw==,iv:sPPZjZHmvNdGmMn++P/ZDsj9qkBqUUftmm4WJPawuvo=,tag:9WuoXza/YGo0RDoNyXZoFw==,type:str]
    SVCNET: ENC[AES256_GCM,data:+5VWIZ50N1aJtBtMxg==,iv:1iayvMgsItltWNugCmSY5ln20vjgFVsDTQ0ebkAHroE=,tag:XTVa06EhmR//9AihcAbxHA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:q7UhmA==,iv:ErRdLP5hPzz2qvRt1Nah3sYHdi7o0oxVVdfSiozY8LA=,tag:bvVIH+It3SbRZPLELcI4mA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5reegnllyypk4t5522yvknfddhnjvl6tvqmjfzmpc7u9wdfrgwsxqutxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWjdBcW0yc3lmWklwVkZa
            VmZYTlUxUDJHRXQ4cFFjNFBrTWR6aUpUOWtJClBIdXdwcTQxZzlRUlhDcGVkTndM
            dW9OMEgrT2xRNFg5VENWYU5ocnptT1kKLS0tIENTNzlVRjNnOXZ1N0xaMmZ5ZWNk
            d1Azd2FIWFl4WVdmS1RHdm5CemNGVWcK42nyzhJTMXM5b1/F5J97oA7aixhcCSaM
            DO89iT/dJ/fNNWOmB5wZ6mDiZbTvggdl09DJb6x9aIo3cDbT86doiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T11:28:45Z"
    mac: ENC[AES256_GCM,data:4nAzWN6S9pMjV8X01KKOqn2B7f08xNyV9z6SEGC6bvo2FQx1xNoeR5AhxKNANVKfzzm0JFyl3M+MG3k4K/E1nA72sblOF442W8n5Qxcuv0BIVOk3Ndk503mlScaGO19jPhfxAIDJc/SDsena3kt54YoW8vmPxtw5sLRwqHuI9K0=,iv:d8drraFYGBYYq0trP8XKsT9s9PAUwkgFVWCFgBuxMxM=,tag:LcLvNnJZ+q85u+k/mlH02w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
