apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:lnB7mn/gV69kzXhs+hlz+tW6GgGLrDJyub7RQhiAGnnb1iQSTICJjYkj80ULSbjbzhW651kxsi5qT3+tJ7G0wDo=,iv:I+UdWIGJjr/APfArJCSXWtWU4jZLZ0f8LqVjql25Ycg=,tag:yXhJBa5a+kWgSIigMHvHwQ==,type:comment]
    #ENC[AES256_GCM,data:8HGsBJGN1flsQoVb53n8ckaXu3Gv85jqCn/rhgqXW51kEAC61pcwLzs4JjM=,iv:WeKTnNiLcGPgnjSFFCHGruBCHX/3eNZGuibA9O7gkrw=,tag:ynMO8RPm8UMNEJFeRkgpIw==,type:comment]
    VIP: ENC[AES256_GCM,data:/+xSi9GsPnKrRgg=,iv:9/dR/3PwqwGKGRGVbn2RbEH7DzF6nyabgBkRaJJzoLE=,tag:4Z9cbUM9oLHppIjYu9HIxA==,type:str]
    #ENC[AES256_GCM,data:pG6Oh8hMGdXFjcPZMawVNJUY8TNoxDvxKeV4,iv:+bicHBvyRYDuqWj97jt5ZjC2Cf7vxjd1/r51v49intY=,tag:pFYfCTdFgiJAa6+Y0X+7bw==,type:comment]
    #ENC[AES256_GCM,data:jXqP5Gy6YimDAnxMv1rhPcvx4Ge55VZ+2D/snT7JFdgmTDHdUacZEIad0XVDkwWNdVAvK9ow60XcbYToFwRd8TNrLpwtaycXDNU1LAXtVqcKfSsQ7nx74Ow=,iv:ATa5qKdh9atDrohgwJ+LxEL23lc0SuaEhjgzBsdjOGw=,tag:7zyL4ixRp4em3ZU7CguCgQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:dhAz3mGNhdauAy0=,iv:9ofR6ksS+Mi40YGfrGzFYlSnzMdjsiKdswFiaTKT1HI=,tag:BkU7mH7/pkd3sUt4Vra0/A==,type:str]
    #ENC[AES256_GCM,data:ywxpO7Xnzpm/J53t1osUanzAmmi5L9udAIh0HV6+d0ZRrg==,iv:mevlarWzMDyO0VMoyQqxoYSrUal4pXQdiY4Js/Ln/aI=,tag:KnnHl13s9DwBYk4dNnj7YA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:gXMMuTqkUfS3,iv:d/lx63DlXjCGib48VEGvWFBwAUcZqRp+tv3s6AN5SDo=,tag:fqIp7AMkqNyz46rGEvZowg==,type:str]
    #ENC[AES256_GCM,data:b9mToZn/sQQbuts2MQ0xXUL7S8UDMSdwx60Rs8M5KV8SHL1sSLy0BrLX8LRIg1A=,iv:nBLTtdlqQMj8XA1DIYi3NcbZos58C9tvDbtxbo9f4kc=,tag:IdxERY+Tt45mAMxd6LZI4g==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:ublXU30/T4hycPFaBkV87Oc2drmhPSQ=,iv:lGxIcast8eICt03eKsbf/aCqiet2WtTtcSyTpua3L/4=,tag:LdpeeavcHmU7ITu62ub1lQ==,type:str]
    #ENC[AES256_GCM,data:Vn5vazTaKPrR+K6UhKihFzlI7lM8GSSHwkaa8d8hUONL0+0vZULAPk0dGIFv+hRR2Vgv2NTuUJPwte5hRhq7n60tcG1tNDZG2uz/iAD/jM6HbQ==,iv:7+pDPbuTCRofNwgJdlllP1FchoofApOJ7AlYvCgyA7Y=,tag:J3KbR5UZlwR4t9fBQ+8nCQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:MAdwTQy07q+Tpxw=,iv:OQsET052DOaphTuQw2hDjX6BGoaK20ndSCtQsKNc4WM=,tag:3D+KdVLLyT5/DCwiNs0COQ==,type:str]
    #ENC[AES256_GCM,data:u5O2nZm1CDegdHOU7DtH2P7CZBh1rCUhXv/X8d50h4yT,iv:j9V7iWPAi9QYs6gO1LUTCVF7jkjNZlP6YT5UAOpdZoU=,tag:3RqYrNqZR5zVSSavdv+Kmg==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:cIFt8NfOnlPnEaI=,iv:eAZKDZY2Yhs7oOw94xZj29BBUilqB/1BszeSYE5zoNY=,tag:mo6onsYYGbowKfDyPs2EzQ==,type:str]
    #ENC[AES256_GCM,data:0KwW1VO477wjijqW/U2V1KHCepp2zh58co9CVxBO2CIIQ8ebH7nD/QtTMHV+kEgWjymdhFH+01otO/i2XKA1kHkEmTjLvt1yOtXy2WovB7U=,iv:SR2en2bs+d6dOmVFsSzjS7IRrdsDW2bPdGOM6NhG0Eg=,tag:GUOlIZDc9B+QwJuVDC0fKQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:VJPlefAMCMXuJVE=,iv:GsxeeGBXJSBw+POoE6zxz0/fRh6tzb1hAENfBhH6n3o=,tag:dIPzAnJZJMXM5BHRuBfbHg==,type:str]
    #ENC[AES256_GCM,data:n7Fivl7Mtj6+v00kPfxYyxzZJGMr4ni4ssE1VqRnFOdDrIMq9/6jap3ZTplT7f9D7wHofhhMCx+/RToG9QN9hgxI80N0Z4ylr28+SMyMEE80uk2K3YYi,iv:sSCEZ+JHXq8ZxTZCZkusLEn85iyEjftdPunuC3SO6Dw=,tag:4dFq9Wo1Sh95P3KwawN4Og==,type:comment]
    #ENC[AES256_GCM,data:5gLmMo/7kjw6K3Y3zcBShlfZCMrYPoyl0sVMM6STmW5LGzkwsNEGhTNn6lNH08n7krR4oZd8BHTg1g1q6CKxEDpB4Qwq4wA73LIbMwfRsZd9eAgN8tVd3IFrRuAMy+OhbkbMPKyX067pakDJXqPqtLQuhosPdzC336slGw==,iv:1ioqFj1zzzaTjNaaBKJaHJ7fuLNUHpP9b/hbCP2AE9o=,tag:qgP/6X0AbYrS5ik8UjYAEQ==,type:comment]
    #ENC[AES256_GCM,data:gB61xOMqEL7jVPVZPXjYh/zSkmjHLcy/I8ryIR7yfoea6/jl5d+zKgaJT0bml/fEoYdSOlk924njC7qeZgHJH7eRzYXZEE0KAwtM9gQxCYI=,iv:bOKe++x4rDRPk04QZwFoAKoxnLdH8ObNUp1E+qz43UA=,tag:JTnEOh4f3yJLoVg7vnNZhA==,type:comment]
    #ENC[AES256_GCM,data:cjigHr/RtdXxVXJ0x/ZwXC5/Uy9/LWuaZzYRxNc1iLXxbIoWLkTkPSUZJvhxqJ9NGI3dEafn,iv:SDV30qNAbnifDpiUYz4jgs7LInUYb5aPe7FhUNw/oWg=,tag:nNT4M9csZkn2H7+gFVXD6A==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:BPgohKqDES/DcI864Q==,iv:3fb/oAK0TviEiu8/e1qmO0XjQ8SsgR8xUSYnKYZkmUI=,tag:FrgZFt5MHBii39by9J2V1g==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:BSU7OnT01T78nbKpdf/QW/cLTyJJ5X2X,iv:DV7sJbb5Z8CrPJVQHMhCZ3UZaFeHGrwZaAnoRjzZcgw=,tag:710jyhhbtojpLt7bE2W1AQ==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:6k6KouFZfxEZzjXWebF2XdEd42l8OHjqDzJNWpRs2xfdNtQ6tt9NiA==,iv:DZgjkYAZqVJR9lwK45p7I/G4o/Xcw8zCDQP10igKslk=,tag:dmgMpeDMDQugc3F2BAI68Q==,type:str]
    #ENC[AES256_GCM,data:siazaeIvIieaSKW6ga3YKeRTb+hLjKB2ENkXKWqvMjr0GpqTGK8AxwCk9vSzFJb9Yk/SZVRYusw=,iv:6BCMTCkcrTw8VXvIIL3x8B3M1l4Q9bBUmZiakwYvfhQ=,tag:iwOhmu1cM2m18ZYTkEkUhA==,type:comment]
    #ENC[AES256_GCM,data:iCmgfbNMqCoBuXTWcRelKXFoldYQvSHWOQ==,iv:A+EKMWbqmeHbM+g0RW25I9u3jpTxur/mIpgOmISi6do=,tag:t2bs1PdmXGIxyzHmeg2h9Q==,type:comment]
    #ENC[AES256_GCM,data:rSoawcLzQTDEJX9fR3ZWKzqsmzf1LEGHKPd3rddYAEWlyGF7r7obEBOfBY0uKyXTjradTzrxEg2pgjaAnl2tjVWXYTTqMiSZOoafKtg=,iv:uQ7EchB+TE1gB3GHA7QoNRZ3KVxBJK3/GhPct3CYxU8=,tag:PjDJFpEy2OyEReeaL7v8bw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Moc/0gHceJlwq4kHGwmUCbE66BYnzqbL7KSzUkGWw9qqqLRXp0WCiYv85Cigg+ym,iv:xO6NJ3HmP141/K+Gu5ynQhvu8Ngn71dl/j0XrdYgRrs=,tag:licdUMbmMxGo18lKcV7rWg==,type:str]
    #ENC[AES256_GCM,data:8+bcxhemZcrLI4DuOp6xlgYiogpnY2EQ2Jawx0ZnOOOmdesgXr83RUviHSDi+AQVe/ppWgwF4kkBTvvoi7ew9TPhKvqSGD4=,iv:36hENYAj8KTEjPwfh6zceJRDRBiYAThIWw9zPha7npA=,tag:VydXCLOW8dLiDqPo5RhxRg==,type:comment]
    #ENC[AES256_GCM,data:7fIAzqTeXe56h1fu5VWTUtQArOHNt5aCJwl/TFHjueLGFJc52thdDA2Q5jHFcZTH/1V2yoaT,iv:KGcvyT1mH4HeboWIcFEwF7Ywx2y8v6V84BK6QFRgR6s=,tag:c3UE2O83scE+jqrY6S5RtA==,type:comment]
    #ENC[AES256_GCM,data:yGbIJXoJ8x4duEuEo3OP6Xh/oiD5Uj5AYzrmuixuwhwOCCs=,iv:S/3DWPKMmg1YhsL+ovqeVMpDZP5ll37ho5mZPPgWxRA=,tag:qxld0QaW6a3MEWjwhhSuPg==,type:comment]
    #ENC[AES256_GCM,data:CKKvCKfHNAkTY0tmI7FhWzTpeRLFWD2kNC4+G0uSM0Yt3yzO8kf6,iv:RLyM3acLZIO8CbxHgpYem+yRNhjlrZeRhLDXE7A6vh8=,tag:Y5TtVCn17wdjtpQta6S8Wg==,type:comment]
    #ENC[AES256_GCM,data:QdMgDNNqbeURg5MArjU=,iv:x0xRLEaGcpLlqPwOL5+0f6KMaUC7CN1QUHcv/m6mMv0=,tag:bOSeFWG89eNM1XLZxVv84A==,type:comment]
    PODNET: ENC[AES256_GCM,data:pbhEgL3erMEL9RrfkA==,iv:gnWuhJ5xScDbqr6dIhI85Tc9jsVe+NuiySG9HIunRfc=,tag:UfJPpNEATryrWP3xsNFoJA==,type:str]
    SVCNET: ENC[AES256_GCM,data:Pkvr/C6qiDkOjAz1SQ==,iv:BVdr16qBETtygKuBEubrOF66cMYQMA26F7G/DvaLhpc=,tag:NGo4En7OOLZbmyIocsx8nQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:4svouQ==,iv:uEVesKI+pQb4OQaPCphFl5jb4Y/dbUL3J5lGiUIRPuo=,tag:AC6jPg1VvqcIc35GMyqxGg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5reegnllyypk4t5522yvknfddhnjvl6tvqmjfzmpc7u9wdfrgwsxqutxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoT24zUGorTUIxaVN4eC9H
            aTJ4SUltb1hza3pKTGNuZTRtTzBCMjF1QnprCkEyU1dEZVVNeEtzdUJ5KzNtVjN3
            WFJQQ21DWWxUVFFpdjM1MEZqcEtibkUKLS0tIHJoL0ZpM0huRWpVMEN5NEhUM3Ay
            VnRKTnk2eXF3L2s4T1FPVTBqZ2F1NkkKW2GyzFA3f0L1VHccPVVJLA8SEFKMHrB9
            mNF9zyU6Th+0w2jMy240ZaSUwfI1e2EJTuz0oDWZcRmiz4kFzgz1OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-18T19:19:49Z"
    mac: ENC[AES256_GCM,data:kbQLDDYeud08N5lZzup+kqwhXRXqcMMvD0YyPsVc+A25N4xGRFD4STDH4MvGDWue2CSthPBVdhBUXgtOFJArDP1mmmAPlrIzESWOaixxRFuCTD1llqn0q93bb7MejZw+fTnAl5ptUdEvVJEFVjdunaiwXnJOmoV5sitdDXWtPLw=,iv:zwiFYJDi03nFUyN4sq68kBrQhsFdHrFMkY3rD80VBJc=,tag:NHF/+L4HD/FgpeNJo2AHjQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
