apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:+ZMUgVirYvEUrGENDBswouvBuGy4EDvomzfcKGsjlM8HKueTNUfLdsnwR3He6zuwqIAtRoeD+Mgqf5X000v/++w=,iv:39C7w6xmlCw+zXM1ccZPRzTZWF1pFOSzPfZepRi9h/A=,tag:raU3ucTMa6w3qVNJUSrbJQ==,type:comment]
    #ENC[AES256_GCM,data:/WhTgHzLOgVd+Af7uEaQVFgQddkP0To21itA7KJi4HdWXwPNciq+SHWFGJg=,iv:ypruaGrt8MLZtxXf0vDNgtLd/okiO3CxmgL60WbmDxo=,tag:iYU5gxO2+HmTPdC+P80+hg==,type:comment]
    VIP: ENC[AES256_GCM,data:koSFHI7Och+LiwQ=,iv:jwsa+TdPiuv06Y4Sw4MXDgTwluAv9NqMJlUiFNuZf3w=,tag:jMDBv3cISgP1Pwd35oWXAA==,type:str]
    #ENC[AES256_GCM,data:X5I8r0MtOv2WRS9QlrrEPi32Of4SS7K3wowc,iv:a6VtZQt1p0HnZdd42ts0axr+Gn7yOR2GK6p3EpxSVqI=,tag:8sPzTdu6jet0NyC6y8pdoQ==,type:comment]
    #ENC[AES256_GCM,data:dYygrZmPVZn3JTIw0XeUXHOpgCrAl+JNRvEos+cURke3NOsfi4E78M7W0514cI0IyAOjapyEPmkvw3OFr022xOu7PsH1UygI4NNIb9/OR3CKQ4cPiOlDZew=,iv:APoHhy3jp1IgHpShVHwQDvXZP3Zp3EyyRrgO36FLriM=,tag:R3jb6DUkuo7+5Ct3PqK3sg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:pSKpSqqRD9nmMCg=,iv:g8ihTjX2KdLLwZewWBz7Iw21aLplvJ/DpMqmEupxtco=,tag:k/BEzVRP6X2Swf2MH3HQwA==,type:str]
    #ENC[AES256_GCM,data:k1pJrKBiNLowVxhQkvrLPqCw29SYWtFRyZKuoyG3PSzdQQ==,iv:nM+aoCKpPWe3ROMS7JdhT2kLG52PHnS4/Z5YDvNkvI4=,tag:SLbPkg29B25s5CSnaLSCpQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:QnA2cJ03AGHK,iv:wgtWgHcTC/U+sJDl+fkcUJtaVvgeMCfOrU3A0H52Nus=,tag:Lqse4KikpZsnNOQwzgK71g==,type:str]
    #ENC[AES256_GCM,data:jYMuQ+3NNH/jsM+B5mEF/y/PChHnWEtItkBnnbppaRFZmKFQgc+ok0qgaNWYzcA=,iv:/h9z9sd85XxPzik1MQuSmTD1jMMxzoAR1S8d/VjcaWY=,tag:AxsKEwGec9NCLcN4hnH6nA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:7+k+zQc0z0f5qkINq5E67mDWHh1siU4=,iv:EPBM4pGSeBfcyMDzZfPG/XuL/smBjcat04n3sGGughw=,tag:OqqoybCvvGnha20NM4i3Tw==,type:str]
    #ENC[AES256_GCM,data:dB78KGulS6e16dDXNs6JMP9avZHGxruO8Y++OwLkvj79UTl/QRMRN72b1lDL3Pv3IgzOY/yK/masYJ6ea5+1mHvQnc40PRuGR3gOEVVpgdq/rg==,iv:vjTuhcBn4KFGpyhdSaIYRCLOwzcRhybULrUpP+clvxE=,tag:O7Jo1L4LS+CxfT6lwKTs2w==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:lrFihN5rYsk9YBE=,iv:yYUmzWOGWzkNAmHTUrEfv2CDK6oJtNZEb2zjCsTkMgY=,tag:FlLtnZ8MCqL4uTGx+dWTLQ==,type:str]
    #ENC[AES256_GCM,data:rZMszB6ZfskxVqMGAEiEUxgBW4Z22ufuU/aAjpnwRJhe,iv:lGGRfgTfU0LaNTkSeFDM3s9nAuebRl8kcoa/hchGpPY=,tag:DiJPXin+Wvm9ag0ticH7hQ==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:UUlyjFxjhpMo7dA=,iv:CDQYcr8+ExLMQ2JP0Nxgf+yZvxLVVm3o4zzgFWvnKrc=,tag:caGJXRY7K71x8sCFihliXg==,type:str]
    #ENC[AES256_GCM,data:tFiEJOPHd7++K3F1i+1bJnzY9nV5KEc1czbPrrqRwStA8tbPxKMmoYY4/iakVovgq4E17MQA8WnLwRCF9iVDlWUynS0a42SYEq2tf3iBtRc=,iv:Ol1Vzay9/MGLVaVwFk0UeIFX00dyxc+w6BcfodDM/ZY=,tag:UuCQ3oo0NXym8WVkPlTIzA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:Xm4l9+IXm+Xe4h0=,iv:tJeG8MbzAm0ZIQO63NGPygsqlCj1feLsovVpOVCYRJI=,tag:f4ngwGN1Z4kvPInrUxz8EQ==,type:str]
    #ENC[AES256_GCM,data:TBwHuRKEQHpE6fHo0H+4s7aVlXTYjyriHo3zCdXl9KD1cMwoY/V7kVe2URn/hqoDTfGEgkwZerigJ3QEQV64dpYpyva54swD9IcU1bwRGDRKiMIVlqBa,iv:20y2P6f2tmzb/bIT+DRNjJWBKsFmhccLPYdewTlfsZM=,tag:M24WyY8RoSgRGb2EAG246Q==,type:comment]
    #ENC[AES256_GCM,data:EQSBv/mvugXIc0J1k1xbzYSAQcPATTfFSxnlpNywUC4vhJbXYpze6TAJqogYkvnTeIBD7WbqKlDb28L6FmeAV7XKu7kOuWSC16fQsZG6erRF6A/ZCA3lzyoFrQO6Xmq9bTIr5PGiqyKx92hahojsIv9ywww/PU6C8HRTkQ==,iv:MeqVjS2qkmDkjihUdObi6zecfQ/Qxc0HgGgZ9pG9WyY=,tag:vxeqZPG4l9aCRxr6dor4Tw==,type:comment]
    #ENC[AES256_GCM,data:0WDil7KrjR025/qepfecL0PGA9ZJ+nmiQtTMf5rzPUxu/RFXPlnFEb6rlhBnGrcc1RsP+rMz0xVFRtNen6aeoMOuP0aL2mxSC8Jh30ETMws=,iv:Phvr6WLu+9nH9L7V7j8cfgrVs6q4k3u/MYGIFEc5apI=,tag:Qang4F43nhGSSDeOlnEmJA==,type:comment]
    #ENC[AES256_GCM,data:ifHk+N6/3U60sAuwuaP9IDzK4FkwL5Y95a6Y1PmqdWjmU1AWwchyQS361JBPxab4sK2dwS2p,iv:AwQ5erD/HGRFlWhNsuz96Mls/JnsviibWFPD0OgP7xE=,tag:BsewoPsEnPyaE934ACuZiA==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:DQZCyPPMqmcuOM6EDg==,iv:FHDcGSlUTW0Pz2wCJeCx1z8vbv74YBh11bKI4wDDdFw=,tag:M7Pdmqxuf2tROYAkypNzHQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:cFFy0RsDDbQedaB4CeFlnv33rrtNsh9t,iv:aQ1xXPyW7AKsVio9xQE5W9San6VBNnzgzj+5xTNiYds=,tag:onzxwNmCVaOsX9jmxtLe8Q==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:UiwSuWxFmHu1GhA3P1al5zJllvS1JnG0oN21tT3MOU9LYlKRFF78KQ==,iv:U7Zi5IuNq7p6XaxtgYkpQLzPmQw5zxYYKNFM5VQuVaI=,tag:vkIaE35dtmC4bGD19UWjNQ==,type:str]
    #ENC[AES256_GCM,data:eQHM0aDjTCTdMsX/f1G7Aj3WZukk7zV9q+mq+5G0lmun3hXX2LxpE3mz5qMN/pHjECB1T3UIOO0=,iv:FEqvUO1hnO1/DRQAcv/SojXx2VGKYAl0t72oNqdTOIU=,tag:EJQ6C5y/TAYpUh+MO6lqMQ==,type:comment]
    #ENC[AES256_GCM,data:wHOCqh2PS7rT1iDoK39xxOU3FmbmavnpTA==,iv:sWsolIOg0+CPdqkGDrf40N/V7A6gLONrPe1ftT9UdKg=,tag:H+UaddT86YgSUPSfKdjc8Q==,type:comment]
    #ENC[AES256_GCM,data:vvNEWXgl7xWpf+KAcrigvFeFlWNwkAwM8E4hFaFd2KSkXLwXBP34BuCn0fvLVs5CmbnHwuzyHMSQ6VZMm4YOrIV6z3yZQndFkUL6xeQ=,iv:ieHA/3fN1IzbN5cxuNsenoDjH1PR4cXJ9dV2/xbOsGw=,tag:v7wXUPEJnw/1JSxpQb954w==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:OhIMG2v5yWLaJqXxTqKXjB8zAu2KGFeqtLJs02RpEXI2aZOkxHe9MOX9Uk5Ip5JK,iv:H8jlhysMCdDk/ATzOq22m1s+oIhMzRXb8kyBjJ2bChk=,tag:vtfeMb8Hx0UCj5VNTBXlHQ==,type:str]
    #ENC[AES256_GCM,data:8XpxqSE8jG+i7HSbyMx1FfjAk8uWL/ogLY7tGJJgYqYAx6vr4EXVDDOAK4sSmAu5XAJjH4G0h2XXmJlx3qEOs7bjReMPBZs=,iv:RpBoL9nwZs+wUgonEHb39nCJ90uMA+zcmwkZhCiweWM=,tag:70oCSJOZ3SF+AzhKM5yAIg==,type:comment]
    #ENC[AES256_GCM,data:Da2Ht9B+B0iBA0fcRVvetP3fTaPsXHAR7xo8Vj3eNvWXN0gYdhb7w1iCvk9ySlm6Vegxv7Zz,iv:UJLXn5A1h0QlrbysJsj8qpFOvK8O3Y61VEe8opGRtJ4=,tag:YbSJr2sF6wf4Gh88wGs6SA==,type:comment]
    #ENC[AES256_GCM,data:62pfL952kBcWeYmn/CjeZYGYmBvPQKM+DfEvnhN+Qz2LjM0=,iv:tF7Xk7R0HHucYJHQX0YXZuUJaeDwmXmlhPPGe01Ji5k=,tag:M5pkJOYV46gvPe0VM5nSSw==,type:comment]
    #ENC[AES256_GCM,data:g1jiMyow9zrDr+BqWB5UzCtTC9qU9z0tB1KJQk3QdhF4M8Z1crwY,iv:pkXxkXfo/SUcyISTc7N5QHnB8lQzTPFoNfjGv1+Txfw=,tag:vZ2C0MyBht1KB+jI1ZJi/Q==,type:comment]
    #ENC[AES256_GCM,data:77xC7uyesNLgrPsLRFQ=,iv:5U/TGtjI01PjMPttxTU9WGeD5gLN7wo5MOtN+CW5Bxc=,tag:+PF4TtthIiipOBrevue61w==,type:comment]
    PODNET: ENC[AES256_GCM,data:JTyC7ccHtCPfpXSbVg==,iv:48FK9TsPVFxlR0ZegNXfobnj58jo2AhKsUcN54DEH3U=,tag:JQ1rMcjgenfh7DMcbrYZhA==,type:str]
    SVCNET: ENC[AES256_GCM,data:0i+foWPt+gqGjku1Mg==,iv:G7bDaNp7RAwRnssWOfYG0C4ZprWUSdr6bqES/BEUpag=,tag:wDIPpSCzQMphZR6pYRjGcg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:HHbntQ==,iv:ew47U22J10Um+qgAi9/fCLD9NH1KUo4tcKvRnCu5+pw=,tag:8/INKutWu2Ze0cLnFuxFYA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5reegnllyypk4t5522yvknfddhnjvl6tvqmjfzmpc7u9wdfrgwsxqutxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSi9lQzZEZW1JaDV0cGV3
            ZkdrSE1IZC9MWDBMUWtZbFBLeXc0OUVrR25rCm15MU9SeC8rRDFEN2VVS043c0xZ
            ejV0MzhSanBVY2tWUE5OeURKaHhTVGMKLS0tIHRQUE9neEx4dlI4U3FOQ1pwQXRF
            L0ZtSDJpelJiWEJYeWpXdmVuZCtqV3cKWRKW6ojoUn8DggM+D3fbcvd1yRIoai4+
            yu5H1JrjAKkqkCzB60n0jYnqupGoseG8fXozKLMFkKHkq5b8GGsNLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-13T21:18:03Z"
    mac: ENC[AES256_GCM,data:1x96iZhyg4I2mXWJ+hRx2V0Bp4IJ/x58R8g+mbnizoL6geqOmyq0nGy4qNZ88ZFmOrdHKsbahXAFAmxXnkoYiThQWGd1mySpGWJVGNQ+Lr2d94ewETAkZo/BhCoB4NhL2cH0AMTKUKCDjKc0+GjnyX96SMIfqamUclAG7N73Xm8=,iv:eSG162gyc/3sru91OfDI+C1/LRLatIlE/XYlSMikXAU=,tag:QjqWzy2rEpQZ77fElKbpIA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
