apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mKw9F4IFa4uo32RPD8Ly2lxq5Wa12ZZPUnTXMhk2sk3yvMflmQgFzUIkYCvw7/C5ZIX/3zU5Br4tNMq9h+R87wYazRbFvQyv9NgE4hVGf8F13nIFeq37mL+mch/ghGr1itiPzc43TPMurNgvheEM7KZtj3MNuRiVse6zY5RZaRIlNScumRwb4I9TQMiYl7lM9wnuYwYLkfedmEGSekmEUYVpg+5Ku1+ghmNtOzMF3ntsbMBiEr4ytQA5hKSBSXSDenuIgv+cUO/4k5g9TnK/Wbdr3vq6zySwUTMdH5p/oJVTSpEnf+TxMb1EAHpqyljFaXBBmI0fLhfQ1kZzuTvFCxThTSA1Im3USlZ65f4lcDI/G4WCOUABDpwIf55jOgCB,iv:iJxuP50utuQyjV9juot6rqw2ljZCF9H6J1n1rPjvRoE=,tag:OkeN8zKIAjvhSwGVrxBPAw==,type:str]
    identity.pub: ENC[AES256_GCM,data:jWrXYWo+4bJ+5pUWnB5Ops+MxbIy2W4WaxPugLvp41Jw+SlDwhwoVuc8eG1JeDh1/7jMqita0fe+co1AUq7hZUAWkKm9bIRgfZKrK6bmHzhAM1fH76m1Os0Wq7LAjq1Kx/V//dlpougbLfYMMV7Rk89fITRlCj9n/GM7FhxEua88pj53PWB8O8t7VdQOAD4X4wTJK/lp2XzxpMUyVIO1lDKMUq0KMCHXULDgjFyDv5HwT8HrSc6uwvK5Eqlt5mfzND1Ll3M3Xh7eB5OoBA==,iv:wu+MFJsyb1cMscfMWzvfsPxtuSnIs2UQmOAMe9W/26Q=,tag:8bJBX9w4FA3wnLDsfkXVEw==,type:str]
    known_hosts: ENC[AES256_GCM,data:1D0rnbmtBVO6ZcMmOgbUvYzaEXxwvmP6WGMN2WnrOBxCojX6NsPUvZXyD7JjWzarlvmxgnlGDBSu9D5MWSv5EfMiKDt9IG442xVIroyMhzeZPEjPJGC0ylhNtt8/fW1DPnIyDR74lqXeXOd5vU7SE1saLDGCF1OFiNjpXYnAttRzxoy/MQWH50TEAKLJLLMtZrkB/mvo1fo3HFN/4z8QfPzYVjqfB/YGL89q,iv:yvL106MktJA7xKpbobzupFPpbJzOmm5v/LrGjliAqxI=,tag:oJpgAzQS84F2oHc3gxW/FA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VDdNN3R6cXhBd2xhNGdD
            RE40WG5OYTd0aEhGSEplZ2h0dU1qL3JtYWwwCmpDV0hwSnhCbkVmakhjQzMwTnlv
            eEtvdUg5K0x0NDdBTzVGWkE3QTBoR0UKLS0tIDRhWWx4SUIwTnQ2U0tpdDRNZzVt
            TWEzTDVpSGV3UTlHdGowbGZwdm55TEUKsHXftcyTNDVM5eCTii/zu4B9W0IoHVEz
            svBWbQwR9HRQZACHMjKLHRMqfhUBox5Q4kD8RNRZF2R8yl2uCat/cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T16:06:51Z"
    mac: ENC[AES256_GCM,data:2PY7xAtjA0cJ1EEAPD5PFIfxshbe/OltuqNu6+LIKAgEJYd7lWi+IuEpwYlNl9BRK5/31I7Mi3oejKIN8vj7Bu5VVq3BlHANcf9SpFCgYoqCDWM2uPF9sSPzIj5UrxwroBNHdgF6POclSaVulJ8IiqBtKW4L859tuf2wGQEep+0=,iv:M6cfCQuLi27PRe514foJ88wvjDEu8wvl0MYcOLfhxaM=,tag:c700OesrhfWXM73h9qiHnA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
