apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YGALb+4C4cSjNcTGLp12oDJZvDMkBcGLvUJZ1/cyoeBcxcRiR/SW0Vi7iMpml6S6rh/rOaSvl5NfaYxXlWQdWHuT3fxCB6UBrayL5j1kYk/jfqg7uOGH+F8XWm7lwPJjM/iX7GI9OokAp0Pt5fSo3+jsjgAjHy4J7fOLy7LBtDt9gxFYoUuASj7DbFisNir1gfQSEoaEh1azXcxtaus7ZPn+wBdKX/kdR34sXLBE3MWA1rj1UfA8CRedf4ExvpTGW04thsPacGOGtLB0ErRbNpb8D9WVKN0UtkSc2e+/dLTXe+c+SJ1BGaIVs8Vy53X+Iy9x0s+emwykIwKdEPoC3QjkRURkwJ6Qe81403Cp9BhCfxUl7LDx+EiXByyQ0gNq,iv:6MDxT51leFLaY1BxuyALX1tCx0VYDAzHz4GnlW/DbiY=,tag:1dIiuWRNk2cr4jwr7OmAPw==,type:str]
    identity.pub: ENC[AES256_GCM,data:6j52Le1JfFFzsyoqEHxy7pWz4yL661NOEZ0ZkoBktUBZsj1Uq/Lf7/0UmXnYp5oHOY8JdGjgimtHtc/iRARAWfpxZT+UzsgzNWq7XOwhxrcQLD9ehAN1gzerGaCYwXhf8kUW4iZgUDAP+EiQvZ5sRiVYn4rZcgWsClHdmzi5OjnO2URbvzVjnNUguHCQ+m1YmcYY9OqXdfK1MDnkUvhgH/T8Avfvqq7I9SVPRmnW49C0/GEBwMydAl8g3NfzDAOVhPQVNXcTcA6DiqBLMA==,iv:Lw4KxcA2qYCjPU/mo5vSrrvh4+U7my03aZXITcySEI4=,tag:a03izSkhEnq5PyQYptGoWQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:o5fEYUJRnYYoE2R5zFR36CCv+qPzQE4l3JOMD0NbeXqiecye9whpK+XrSZUVdcAHEw1FqD/hiJdgfPHAgDuy0o1lwM/AUcLS9fxBs6Z4DvZymDOHlRhEbJL5TVZnJIuHVXG/swbukejkOURbjtkLlvBZmnYTMEU6MyieFH4nDaRZHNen55FL72LzRxtgQt5y6oddpv23xuWB5t7uSY0nQOPQpFUGqj1vlCXA,iv:Fumcr7WcU6v2B9hWcc3Xq8MVfEAuShN2B0rST4B3wHY=,tag:KsueuqRvAYqT+5WAiI0kMQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRV3ZMbE5GMjRMOEtrbXJK
            T1M4ZTR3RTgyT0VBamNLVVZGYlArZHhzbFM4ClViR1h2RDlQZzhJemhNVlpqSHpa
            VlFCVXVPWUJHcFhKUTJOK3M2TnhSQ2cKLS0tIGZkZDlYMkRnZTNHSXpzbkxvL1Nz
            WXdTRTVVNmw0SW11UlZsTFZ5c0NSYWcKaNsOU3gNU/np6jGfs6Vs3qz5glC/uanS
            RzXkGQGSecqJQz0O67YQMAi4kBkB5iqsLTxEZbithZlKR+0eYmutfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-11T11:25:16Z"
    mac: ENC[AES256_GCM,data:4cu7uGRGbyp3miS7n9EUaW+aG7VQvJpPCz4gc5IsL2xLDuV5sVdTiEtmhP4hlxkuS/CZzbTB/4VGnGvd0x8qJTKwDFVFYYi3UzwbKMJ8gtUUGC5oRulzCPBGo2Whs3x3zjiVQmo7ET9zLJG0+Ec31F1YNKCYuoARmqah+xggZs4=,iv:luaFdannIVp6cpqHS1ql9lM/crLZaY5eetw7B5VpGVw=,tag:vD2lmqYu6REivd5iH4vzgg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
