apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hC/vZBL4ZAY1Cf+mmfp3a9axgPi247sKeeFaS1AWUIpsjjI8sBvpPwzRGeTtDotGLxKQwYVNCCKzQh6x7bnaZ5xuM1Q32UYV6ay8mVP8h4oh2HP4840ZcXHVxkGbSCfbpH9sBajwkLGgVIbvJUD/VaCrKXgeQ1Y93ABQIGimxP9GYOesmEMUThPQ1E6BpdE5WWRG1PqlVAJoWrq865t4hTZHDi6jnivTXmuNdb8lPsd0vLzMTeb0oKh8rqnBknyWdBhkRpoPQOtu4AjtO9Jb4a68q9bgTe65egZwfQficfcSxFckWQ80lJ6vrnWskDdpz2pNGa5C8fbwHt1KkcrTAEqqNX2DJColNh8R5nDkElaAdtpJgvIbB1IkZUrt2E/k,iv:WX1aN8dDBjgWhw+KPmDbvB34IHzASsjknCv3xIl94ho=,tag:+TZ19GXPhUeanVSs/Qe/aQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:8B3sh0Us3okv91zwlKhv3Hw5kb1t42V82jNLjcPYUYutdGxG05xXkkdmY9IdHuzxvfIPMvO/ow31jfwdZ5t5zq76sUcipO8xB8i08FzAUz4Agn8CGrC4e7LrgrKScpYoH8x7DhDMajs2G5gSC/zScbtsf2Cv9JkMR94zZFkbiNqJuykLCRYftv6dMICSuBJGj6kZg+ji8bJbUuoPbDXZVS5jNeFqT53xWrMj4b4+hhsmoJ8TjFDm7ZgN6NLHCKLrGpN/eHm5+H3NNqW4dw==,iv:wBv8BDeZUrN0nNp/WJz40jt6l9D253ByGmQHkhsLTjM=,tag:2bDgVYo0RWrLUzTm+aoZ/Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:ajvWnd/9O6I7Lgb4dTtdy07kBPBfDFl65BBhl2BnuKY3naCIJS9iCtQzC4o8bGbUkhPtyI1nLQikr7tAOZUoO4mHkvwF8zqZASutyBpeEmEuu3ZtCjLiYMZtgT5DmdRZi8w09jR6Tc7sbWevRKpNpofBsVMeuiy7KUgPcD70lJ/y0V9KsxLtLR026e5qyr1iodU5NWfrwE9rKeFqqtSPTdWLClyzsvh0EZ2Q,iv:0y9h264ZYYnDYKHpbD30kr8IFIA59CUtQpCHbNqI6gI=,tag:/+gDA1kIkSuTd9WSb1PM4Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QUFUSERRRVJUdGpyTTFU
            c1BOdEp0MFdaMXh2ejF4b1liYnQ0OExRb2owCmM5NXJ4TU5nc1NUdHN0TG4wQW9m
            ci9EbzJpNktCbkdhUVZqNUo1WHZXU3cKLS0tIGVkbzFwNEZOSldtSlVLVXp6ZVFU
            UE9sNXkwV2RBUkJtZXFzVzJuUEhXbHcKKiurF2TU//TRiGEoRm78W8bhg0607Ee3
            QM8WDeyl722Jcj5kKxMQawpvX6MebNkcPZVWbVgFQzHoXdZ7ASUnxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T04:34:02Z"
    mac: ENC[AES256_GCM,data:BNclvX0nfyAL8nKNwcUtaUhlhLiwPundcZILMM9W1jLlVhifO5owNwI22VejUeGszjWkP0eCpknlxCU7bx9CT7II2CbwXyLrF4oRbbAPS3CrAPGStqO82PPfq6SbrrJDWc9Wtrc1JcvtHQZxU6xduf8YO/Wb3Zqs72B3uz8csz4=,iv:74xGrM9qVdanKE2Q7lYOSW9nMirzWhjokx/rMY3di5E=,tag:fxlRekI9NB2KpqhHFBjGTw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
