apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KoCc0ZEayW7IEBjUBEz0tYvjG0rEkWvf/JcM1xw4xqFGbwEWKOwfcUApzq0e6lZ0ExhDMzvwLZLajslGr7A95aFpsGAbAR703qUZxn5Ff2luArUoidFcFCQ9erKSX6O0hhBZtCUfFiiZbgVwtC7ewPQZW9gnB1dfvWICIebf8ZfNFincqA2hu3ZiV9bVDXh3NhBSZ0n/I9K6niwLj+FeSCUL0jNWi1bt1/L1H7648w5BC50ZGNaALPa8ajrThtONMdfoYZMQ5PDb80UW3Objish0eiBEme62DVnqnBHg1GmMPnrmzWuq6kSjSLXptY7M9TYhq7LN17e3Tmb2FM985Z2zn88RI/TkmweBwGeVadXMPMW4wfCdFSwFNcWrL4Pq,iv:4cjxrj/qmCqqWQtYzVgtlDwkKGu0axZjYu5Ytmz5kTs=,tag:eiwXbk3WRUGBpyR4ClK5kg==,type:str]
    identity.pub: ENC[AES256_GCM,data:4d+RYeBkIMMNmX7De/iKJYC95ddl4IdsxeO0WTZvt6NaQpTIfeBwUybQ8bMkmV2K0A3hh1hnY3jSzwd6bosBsx7R8vv3qE1rd2w9XVTOhpwnAT0p1BmgSeMUEavd+/H99BlpIhFAyxS/d3UBaxo3LCQ8fs2apejNH8O5ogruCLPrJ68zMMJ2bkFiMUkFsvlL4zccH+A4oj+aUo/u0+4X/pvvGWo1iwzC24tViNdoGYk1eW5NofZBuFRkf2OfF+7TIsBGelBNpyhIauKBZA==,iv:yMAOMD9t3ZS7IO0eQTU5s98qLXo36/jQjF6jq4RgLv0=,tag:uGaey0BoYQVeMdKnVyPrZA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ty2Nm0BsLez3eQVSXvEcZrbfpurAcvnLYi08u4D7EigMc+q/o8Zv9oyIM4lAaGmfpM+ffqlckVAC8NUqNf1yEjc8cAhrqy4cOst1YIl4/UEqgfzVr8t+yVwdIt9obr8Ax4Q6Q2qODDIg667Fhp4yuVtkBjpjAg0/JGabTERUZ3HJt7Ljk9EF0OkcuI7RSbvd0DgLktBmQ+wX5LqPZ0TcmQ96aiDOwkqNLvYO,iv:3k46E68XwcAJXkWtrSgKkYCuu4WCBgEJsSaK3Pk+Jqw=,tag:mlIJpJSEynzFhdlGUKb7IA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNHMvU21yeWpLNzVPRzZa
            OUVnZ0F3aVpjR2swMnZheHRCRkN5SFJmMEJVCndHQTJ2TXJrL0RlTHFpV2pYWW53
            TWZCcDArNEZEcEg4aGVob1VjOWhKQkEKLS0tIHp3cXpRVXB2anlSVW0xcWZ0MXEy
            S0R6Q1dIYzUzZVhnWGt1MlkyajBDM0UKjHECOCwR5aPKAT4qpHBCs17L1n6umJCn
            8qfMiYzcfVExvZUo7Ok2RKwqTThu4qHMCGv1mzIkchjGg2H10m4APA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T06:21:34Z"
    mac: ENC[AES256_GCM,data:7V7TNZkzYSWaAE6/LDSBJDTnNv9+aIOQP/X2/sBnCbvEmUvyJA30YXv1OBLLcrsXgwzhH4wYb7u/wo6TU/FYr/PnUJbHVk2dTtsYAzunDUhCYFLBMGYujontVqTaq2Yah8/RGiUHqgS5FNhKEn3fM1Zl3Yl9ezOxEQo2OM1RiFA=,iv:l/UzSYqfVy9zrzr9cqNxNKlDvedl7zirs+1qnjTIN6Y=,tag:/0EN0/nlLYD0RlHKOpHukw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
