apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eWxeBTS84FfmHL3auOV9NZHc6oglDFIRrBzsXqp8eUtZu6VJAGETILd+BMFWZBHwTfT9AqlLkqerwkRZdexZbxtkG+OQg/k2zz5nUuU3k9PM64y/TxL2GBSaZX7BkE5BF1uvkOzQkbWhaarRjiXTYWwlfCm43xUeVZbYmSdurwEhNQBFhgMW8aQT1PhL/X8z9N8nZoIUrZwglqhpd/f0XSm9+yRjN6YX4XW9oEJIk4z+dQSqyQ6EXMtni629RqvhwowfhV/aQ705lUm7tVJGqEsME9XW6C6C+bfBg8CzghUQtqFpinnyr3KwALj9yZa5LCBong+XXhy8ROOJtkxVdPCDInqGG7vrmkVmv/kMHZ1Z796PAArENnRZBxcCthdK,iv:MGbHMLCxOJf5mjbguDPVxVImM+PCmB4Lsk8PksMFN88=,tag:qwOwDyLEkg8J/JkQIYHI2Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:Z5f1zbVWGOUM9eUn8Zb81mWmtl+kT2TdYBWOZBLYBJfFBI+t4aSnaMmrjtwajs4rasRox5b2i0y6Lv6/ljHL0LP5n7aaTnesrpG+OxpdSE0S78PMg5ut/wWm0X9qxgdG4aA2qxnb5O+V3wGZIXiy7TODfOzdO2OEFy17n/PlE9+ApNGrA3fVMbZkdVnMNhAWa5Hsw4UyP6QQxgeUa3bCxBI3e1Af7D/Q+in5fauaXbgRVfJJbTjD8d72HqkJVLYE3F5cZzr8IZXT3+mtfA==,iv:5gN1Yhus8BPe2PBUk6nAbtFK7/ypwb9OLcM3T5yoZR8=,tag:TDmo1wX7c8/eTWsYRZiigw==,type:str]
    known_hosts: ENC[AES256_GCM,data:pwP5Q0narrxMsaK7Nh7uEFIB92H2AlnmlT/Yi/Mg1Pq/zCR+cCIOEFfxtTo7VboiBW27NQmMaFDdf2Gg+LkhL61zwC3wDk2NG4LY/Fj3TpjJaTuoLuHlKt61ZWCbEfvKjaxdlsp1pHnUlYlKn56v2e3DfD9NA7dWPSkkn2dMKaFnBjUK/4Q/FmlGv0fzdqw6X0nbGZ6VkSMurMVAsXX2+vFp6PTgY1dPBsee,iv:wJTYfk5xUOaj9uXsRjacrDw4B44yVDHtOpdPe/1MgBQ=,tag:4wr+/TocA2QN+Y3hMpN/2w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxelVUUkdjWk83WmVrdnV3
            V24wWlNUaDJGUlhXeFJNZVJmZzcvdkJadjA4Cm9HdVRQeWZnWnBNWS94eGtMQnNW
            SHBLdlRsdjBiaWIvcTRaOXVrdHg1YnMKLS0tIGxXcU9pUEk2TUVTYU9yaTEva1FR
            U1o3NDF0OHN0WDd4WnhWMW1UT04wU0kKr8FeWPAFLrM3OJLVvXWWc21lQdG+oyQ8
            m7UlhTl59XHWW+JHF3JvclmxZCLbQ0ub6pxEmvIQGmIkLMafCoskLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T21:34:51Z"
    mac: ENC[AES256_GCM,data:Ig9zWQEyUJLstEQicV2lH2UGkHYHP99yk6VgCS4DM9RBdRwYgHEZCyGtkFYTimqrArWXFKCjsogoFN6j5c/K7+jETisaSDRd2H5y62r7JKj8kerYX6ipH1AiArZ4CVZ524RDz6JaXOW16ycRxpS1J10yylJr8t9oKox1TqAWimQ=,iv:PCIVM0s79EFJaeYt1m3hiUiDchjhuKAAfhilxmn/etI=,tag:F1Vd1/iA3N2qoRo/0INPNQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
