apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gOyZ1nIXltEO7eyShsW2KKTn+7bAd/BGrJQLy6n5+n5SvUv9vWM11X1tiIalaxsnltDgTxqPJ/UI/pEo5oMYQMf/OrdhshTrgL+7pKyuANw9d1Y1Riv+ej2SNDqW0wDBtTLyMUPqbuO1/gvGAHB0re7WmJ0959Lkehz6OKaKrJLfQ49QGs/5HLF3sajYcrMLh/PEpv26la/PMiJZkDRkEKZ9N2Ta8P8tmiOesEXWEBGCGBvB1DY8qReOT8SzKPAoC+ErG1KeXycVKGfu3W8oW8Ft9yAa9XAzMvJmUGT9skZTjM70KWZbuoQdz0wT3GNyWV8eZuA2dEXLqdzSvUkSNOxC1rSvPtspz7istvLRFVUW9Pod+tO3X3+WFQkpSUas,iv:J1W2S7nJ57Ptu5CtE87b3ilsV7oW5wi3G8FEP8iqqco=,tag:zWI1IS24dVBG5JFIDh7vUg==,type:str]
    identity.pub: ENC[AES256_GCM,data:14Te1w42igAyLCD8hoiiF5/CzHAl9ImynK8ETYIU6ZCueHyan2M48B2zpRGJVkzcS7RpGA3Q9eRxB05gsvGkyqTu+u2+6OayZ4Y6/YWPk7D+9yw+/fiXDQcL5hnOxFCDmy9xzgOerW90GmeZ3usHVbeC/R60Cx7QzcNCjfbA4yjBoq//i5diQECJx8yDU/pYpFAzCuQ6BmmB8qctGNxEH1oUs2Fyma4vDMYNHnqz1zxrq1vzVYspRuu2UcVzZ6xV67gfs1yopCHEYwHD9Q==,iv:VeSeGJQLWrrAA5Yxoe5xXQueYeGFu77716zHKYu3FlE=,tag:NJM3bmF3J5IG70wvi4ehSg==,type:str]
    known_hosts: ENC[AES256_GCM,data:B7qmbAUdlWZxeZvLV+TM3cnPpyQCXjOFVClI4Uo6fBSYZ2h92wPR1mLNblnQl6wMqrxg9PCcyVdNP0/yf4X/Vtxe94Ob3xPMXmdlC/TydGtHosL32QzZYNUvWwTp3CwuQsVgKDC0Fp4im6P8UwN4xoBR/ZvORoRAeGwqn0xysXUJKRUM68f8d26SIja/XU9V0Burhfv4ze59uhScFzMzDC0s7YWfny/iO6XV,iv:3crfxmIVM1hC9Efs74tQalu51JJiS15mBsPBOuA4KbY=,tag:mj5gTA2Zyjm1ubr5sncnmw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5reegnllyypk4t5522yvknfddhnjvl6tvqmjfzmpc7u9wdfrgwsxqutxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cnZIK0FWclR0cnZhSVpG
            VFllRGlESXJVaGFmQ29OUkxUd0xqeVlmejBrClVLakJOaitZdmZRcFFzbmtNOW5n
            VDlZL3VzekZ5UTVwS0FHNEV4UlZCVU0KLS0tIHdHeU9lYTVXSHBYVEJwa0dlR3VI
            R0pFZUtwaGFXbG5xOTBxbkRQQnNvQWcKJUeeaHkWLqLJL93r5o3KTI95UnHp0EnV
            YPynCyEnaso9jRvnOpPvPu1hpZYpc62gvWSL1wjMc92fnEvPLiVVDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-18T18:36:29Z"
    mac: ENC[AES256_GCM,data:FaAvCdwunEo0HltQwIz08/Kgxf20luOhT49FSVHJ/xhiF0+fvNLn0Nf9qbUml9colhJDM1kkRfzfy0MlWzeivmsHlZc5Srb+44ScQ2Yge2zvCn8YcfmIpDkaP/9tPOw03zrQHxU18pWyKsHc0BCp6pgqfL0y/2f43elEh5O2/I0=,iv:q/4YMuRj0P3tsx3EekeXNUdNVMJLHkiKGnA8qDPZPYM=,tag:/XLKirP702PjmiGJydCXHA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
