apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8qZCxEm7Pabk5/rCGFf9Oc8BFwDar2Jo75M6xurKPNHyPzb13vGTAu5YTGM1gaxIsfeEdm/HI4K0EYqStQWO3TSkyWB2gYXu/p7KKfVjcMBCRPPejEDvV8puDW+ISVQVvBQAU+5heuKuGCoHvEJP1X+0rokmJIoCzhyJ2x5VxxtkJD74th4dv5MUAxzi6QshJGaCR+2KqTPTEPveDujE6Xy19p2hQvahNtnYmQkZjpRFxEwC0JrTHqeEWEIxU8Ful5QJTpRWeeeY82sKeouIkbvUSo4cNaQfJvjstBJek8gBPyDecmjnAD8iT1HqyaA6Ez/bVmF6NjJfU9tNqxoIaLU8V6nD6syGi+pag4y2RzkdOnLNxn11Qj2Nda3RXy/R,iv:neU0JhPt6XWXCRDixpVHcMFoG4lNOaj9kgpOWQgP2yg=,tag:Vtd8JfA4WWqkLauHDSkwUw==,type:str]
    identity.pub: ENC[AES256_GCM,data:JPPE48PfCpqrXT2k7xAGuvALrBmFZj1vcf+LVGDO9jlbpox5qnjVu4RRiGz1BT7bPkvuS/GYjkYYTJgY2NpRNgdicCCNhToSqiNnr5vvywaeXQIBo9Md2ztgOMH59UIF2NgMNzWHHh4b+Qd3xpuMO2/IN/CCMA60N3Z2Buxsd7yKwscM7DFNXnltps2XV7Q7dxy+Md1qweh3fB823q2ODeCLi0RnBTuCf601K+f0IoZdXlHFOTo07Mi1qEwPqWqVjxbvHWB7iy/bl/7Jsg==,iv:0r0pAM1WdbesM067ezvo/yD/Ubuj1CwGN9p5RIut9ro=,tag:Qm/g6iOccyNGZV0znMNxXw==,type:str]
    known_hosts: ENC[AES256_GCM,data:LSa5e8MAGxvy+M66ElhwCSIiK3g93Je2Lj/pIxKD1GDAFAOvmSeD2D5PdUV/gpFtrPXx4XiSdivUWMGiaXTfxCaAiaZN15a6qXBTO+m4avZ58Cjv0pEdj9Op8VD+8C2X4/FRj65d8SgbOU0F6xatKiIvt4F7A0RkdFVOEg32iUYiqeKNRe6BfbAoXjeqwWa9AIhZ7s0Z1P2bAnlgBEm1rwfo/LeXG9SaoSOH,iv:Pn/Cemr1hGDOZ6VZs0gk1jd4muD/rP7JNij81wCqWsw=,tag:w7rXUv6zrzol1y2a+UUGrQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YmxPZHhLa2RGZjhjc0FP
            SWVzZzFCcXR6VDhrZGR5azhKOWZabFM4TUIwClkzKzJRZG04RTBERUlRNkZzU3hV
            Q1hNenM2QTI5WDIvVGFwcUxMNGhwZlEKLS0tIGNDMTBMNHV1aC9UMEJjOGxhdEJw
            SEFOeXdrM2NQWk0yanFiVVZGQXUvN0EKEQD/q2xgnVDpWlUaZ9NwTdbeC1Q/bSLk
            h6hTDzX6fsqHifqK/z/LeSsOp+vefpEKyqVGQZkl+ufYCeuj944r7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T17:00:54Z"
    mac: ENC[AES256_GCM,data:mENMixYJ4ie24cTWPufCQNKddW5hBf85xr1D6MOUjWnHwhYVnUQSaB0yXtxSoYWoQdtMkESy46scRy877P5TF0QrorgQd7IoSM0r/5e8ei8Tmtysc372piDfE2PHtyWklvHSgTIV8fxQq5US3kXBJMmDBs4ePuAS4uABT2LpY7I=,iv:OcIoc3nvWmjpNP7rvRtDjXgFnmuFrmtfbQaWbJOY6gc=,tag:UJzhO23VhnKxx4To9yrggQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
