apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/TWWISMxTE2YjtB8CqUcQDQq1C1edU1WXvZzLHguc2aPskFoCcw335ojr8lLprFUYRiN4lb0IoZ8QmhpqDjRzNMxM1KrplIncgIXANeu9K414Xa90tzCjXPWYqbtzyFOpt/foX1MDIxKJng3gSJEpj8NRsvxHr7bV6RKw5/f/afoXrNXzQeOmNef0E2cG1q6Xi9fHqYnS7t/9xmsyhp6sjqgPSGDxBPUbqnzmWCUajHTJXBu85rKBib4aIR3CNo17cTFX0ePERkQXlnMSf6tS5mMAdKwHTtWkK9PuyHC6a82YcniCro85lpc6eJMeQKaA0flZUznyEIarGonS0N683NHP04sDWp/IC/0JypE6XbPltF2yi0jPkNI3zr5aIyi,iv:Jh5aMcpMotyk5aJbldABLTHw0wuqO2dF9aTupai7AoU=,tag:m4wkC1SetIL4jzG/1hCYwA==,type:str]
    identity.pub: ENC[AES256_GCM,data:sP4wqL5omUYIoaVyysIjFKRiFmtmiwsG6RBLEuUrYYzPl7CpyUwnhv1FAK5gBganHHUt78GHZz3QgL6OfqX17O3wYob/epzV87Bzsxzm0/KC80AKpmrY3cEU+LgkHrNBnSomfrVDuYjFkGq+wTKmRe08MV5OX3K2vdJ1Fmv5mGr/yq2EQ+0PalLW2p8wjon8Mq9RVsYLB1th+QkRN1zcCL9VtLWKV/z0onnqNDLMVVUlbxfCPlRerDia2Ev+41dHulqNoD/uEfMQUqIDRQ==,iv:ZskGvETNNiEd9SIpzspWOiPxUXdycMHVYe7zHdtlSrY=,tag:8f4zfOtg4ocrk4ekPNYSdg==,type:str]
    known_hosts: ENC[AES256_GCM,data:m1nCMeM59FSc3Ry64XWCXZdEpihcKWKLhXb6tqkBj220RvNYJGOjKDDvb+C97W0FlJhc0v+Vsf20mlN9MTY87g2y6xneo1dYg78izptOg1SMadI5Z7kx93RFKHE+pfUfe0vXb3txxXW43CNJn2T3QSSwBSx2sQu0fuVW9LTumE+454wmMfWvw7zsqEHo6cGVxenqbxj3Qx0ac+tFKVdVoWwbG3GzNZKUT0mr,iv:a48q49Q/vMWeAI624QkcMy1TjOrlxcumCtChBOTUZbQ=,tag:r10otEPe4NH48jFBWpQJBQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VER5c0FjcUNyZUxDczN0
            QjJ5SW1XZUQ1M3NwZ1hDMjBuODVYdGhiUkF3ClkwektzaEMxS2dBZlg1bVdlOWtO
            ei9hVFJlOVcvaVpQQUlidXVRci9WZXMKLS0tIGRFME9FQnNHdEtsalVrWUpvZHhW
            Rk5NMmZpZ0RnTUF6RVovNDhGRGtHamMKbEe3ikJtwktOM3hRKQpKAtTZhsf00fcZ
            EgWAHHao6hOSgpvTCSbbRckvV+GyA1mzV/Jm5grc+pG8uCT6j0LkCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T22:18:51Z"
    mac: ENC[AES256_GCM,data:R14k4Ozui814jL3u5FB4VATl66ymvpbgIrXM3Jj/X+CBj/rUZucL592UvL3DX6BkzuY4xaFbMbtYwQtTSICqWfQXAUsPF0Yw/uzXUYtKjhQwbN6DXcPdqQ6ReN+XkEUMq737+gIiOfS5bCwzaCwxmwdeZ+D2t5Yj+XzJmWqeyLA=,iv:YXh60DbD5HAy3fjo9nAgghh1BXL0xU9d9QXLg5gmPRI=,tag:Vz7kC9lhN3wnZ7jYhoSdnA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
