apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QU6RXSZ579U0vWj7WG3xVadQ4+wofXDOXH81QhECtsCRotvQ6B2p4tqCyJYcGHOukCjq7YDgObfTH/lMlQwi7OHbzZRXmsw0IuCMNJMz16yFwyTEUC4DcWvNAi/cCx2zLZumdLPqiAOny87FbiNDfWF1JtZUzxYlYY3cZJ4KL2qgC9uNWqLA9Pm7EWCwZD17V8dIr/dPm/qpS4/YjIB+WHDFi4ydHm3pKrw5yNyNE340gn6fJkBnhgeuvXjkWi1n3FPVqWpATiRQkyY0RCZkZJEdLkKBUFLaGF7kcEhnVuvijPBiY/Wqw89Iwhcybt4sRbOimdgPAyivR8JiTSvVHLq4CfpeAXAXgU3/AhEsa+L+W7qg8AGf6K2Gv8MJZzDp,iv:8RhVa7EUvPboEuqeEP3H0lZRACHc2I+bObWTTFybPMU=,tag:ouZD6knPoEownpkOC8RTsw==,type:str]
    identity.pub: ENC[AES256_GCM,data:61iBtm8fxGggBj5zRzOifG+uRpqPlM/53mJSw4qihaqdbyGePT2Zxxe5J7QHoxcGVhO4Pg6d/kAg6wbtadFpq6q6JMrot2wuQnXjK31gJStoWY4G5JgS5jX4dbsWatNYgLiRTJMue70+s3/p4yURFEjsESaaii0EwA4DGRnYb4cUsSiiJNYONxy+eMqq8CgbjlI8zdneG7Lr3nVKcFiL3q+6rBEdc3qyf7IFN+S9SGE4vBTZm56M96W1vQoBsgV4KoJhD/yPwB8yZBt0nw==,iv:YBF4KAWJ5FY0DVA9jlNmTtjsyTQpilt2fQbK1ytHvJU=,tag:0oJoSIr7S7aDqvJK4FYzZQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:0k/hnNKQdd5dfk4exAMh3lKgAdjF3BLn7rzuwizTMCgJwZoHzqttpFxWAUe0KJUp2mh5K17XFBTT69gsBfQHLBBnk7plhXGk4f8xhi2XMuWDuhTxkui7FWpavUp6Ql4wLL/CeRiQru/T1LcIaIMjs74PHJKC5JDgDlCiFzj0XFAL79CB1ys2NNQoGzVGePXmDyz07FKuwDR+/b6FzDLwRHnn8b8JR3xz8Aem,iv:70hTGasbLz03HXUUQJDYUOe8tlfupnXnfhenGN6Vvdo=,tag:4rnnAufYDOHWw2xgIfHASA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuT0FLUzNNN1RpTU5EYy8y
            THpKRHI0L1p4QnJPQmo5R2xlbkhUdjFCaUJ3ClZ4bzFocXBTNnZPeHV3L1ZQZmpn
            WnJmWWtrTEhmVGUzR1RCejRjWXhqZkkKLS0tIGplZXdIZVdTbTVhNGdLSFhwdDJN
            ek1WdjhVYi9sMExkOVhod29kNE5kWmcKKC4iAfNh0sbgA/+okz6zLtImK/U4LxBK
            jT2hpspxF6iN8io1Pr3ushJHb5RKNB7x3R35QUJTvqUNhJo9VwQTzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T08:43:40Z"
    mac: ENC[AES256_GCM,data:2BPw1M/JokoIArF9oGNjSq3j/fhh12jGz9BnDMbQvF2XN60ut/6GeVNPMcstcw1Yn/6DbLUpihpdD/ZjGtckuynDNaoMGUNOEFdcXSvKE4yRvK16xzJrO+0F8V4ec1S17Rt8hXgR0Qc2sqT+rgFqfdhjwHCCzvUPuCowJB9iZGU=,iv:Oa/adJr4biUzaknT9e4II5hHlyfOOB6N/wKm52CVNi8=,tag:yNPQ13Teowe90Z2pa+qFng==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
