apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JLchDjpH2y9QdkEfRdk2YVy7BcZVw26pGCnZl9om3q92UrXw2C+tE6cb891V5TLSh9Y1gjldkZIGVvnT8vKFNzqor/wP9twQCQMybMAb8+YRUNSzsu5YYNrNRKgoffb9riO07EfKNDJmMEstZdDsXI7sZNWZVfb282OkqMaZ4xZtCLau6zfBtQV96cJejNPcNQg4gYUfKMjWka99Y4T3Cv+NbOhQP/CVu8ePQVDcrRu5PfriXzDVESoxDhlIqp+G41vPLXAfEkQjF65v/D34MZS74b6Hly9JRfoNsfLJA8Qo/hmdDmwCwhIbUe49YWySk8PnU7CRf+qZwOhWypfkTSx1zJmo8G8if02PcnWFAWgPaLkEyb2rc+ee2stNu0V0,iv:UVcLFOp/ZfDnbLQq779d9Sz4Vod5nMflB16Zk2uT/B4=,tag:E+sVVa4nygSa/6MBITYZVQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:l6asmqRzwPta3Q39gtnHSDmoyao2NZKkw9J6WQf/G3XxwnEWTAISRMMry9wl+OLPdrAoVEOPaVwEQOENiBXR3CefVSOqYgtlUAr+cBFh9Q9F9/vENh5RUZmbyIy8OOLhOPLojtB4x5I3QmjqRNaHV5vW54ZM9SOnQFG7Dky4yrWp1tYntyx3zpqxpEZlThsKcb0NhaY9K3qjEJNl3Hzq7M0Wnz/SA6TX7z/59dsZCZ1HlW3rRcQHn8+JgWongF5xv+V2p+2aFD5/IuTJFw==,iv:BgmRlJoJBqu1FPUHf49Y9zqGD94/4OlkLTdnnFJKW7M=,tag:49LLPLsp4LNWu9ZwunEEfQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:c8kcqrHwpK8pWhcWShgC1nUHw1n0hun3GBrMIIGkESydlCu4+wbRaKpb+rJNg5Jy0c+bYCqGiDvp/nGfa44AYMC38LjkdJd3Zy8MSKi4Zmxc2BzIKlwVDrV0ESp4UX23DvsQ86yHZvJIyChpRrO3bzHltb342ssmR3R+9dJ9ZDMytMNhvgJnc2cX+Vowh5MOCaVKq4CSYO+7WAUAGZtsT35fSd1Cl3/htFLc,iv:y4qh6mDSkmUpJldpOpA6YoP8DdlhT9PsluhtHbw1nNw=,tag:NV0y9fglTXhgMhbXBQP+RQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMVNFSS9pdjUzdnVhcExR
            WkdLUXJnRlhJTXAyQ3dlMEFYYjBINW5kNHl3CmRwUzA1MkVCZDRYNUdJaDJQNEUx
            WUFOL1BzU0pEeERwUUg4MzE3NDBsem8KLS0tIExLemlqOERtVG5zdUhHa3pZTGN0
            REtDRlNYN0E3dng0V25PbTZLRXRiYjQKI7H/6n5ZU7ez5swdGwFMRiY90dB59nTX
            BxVT06pVnHgZvBBawhM0y2g0XCnvF9fDXIxNkNBi6HMi1uORxszN8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T11:30:32Z"
    mac: ENC[AES256_GCM,data:v5ODpVKM74orbkECKtaTuf1SHBqbgv/0TwkDCA6ZHo2pDqcQwKT6oC5xqsPLEpgwjjWx7iiHSUf4O7KXMn+dV1LONFPNrkIE7tM8caB1Hnsj/6XS+4GokSZF6dzCyYnANyes6QLvboCuJHF4i0dnl2VCKvvEV5rLSSN7tvooa5A=,iv:l/ckR6eaid7F4xPjRFr18pbEmgcJv5sZecoHcF8A8Ik=,tag:KuC4Rzo9g3s9XeZ67mmQKA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
