apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PCcpPutzEobE4SbcDOK8u8SW5b6xuCjOb1n8UJNGJC6uOoeqKlzJxe9psgV7lxJ+A7QGRkA47Np1YCybEbCr5y79E/AHxH/58hsm442W/1FBJuolH+lciPEkMSpHm8YY6upiom9zlETq47VgV5DQlVintHYb7AX3zQfAusGSJaLAGVCxW+IoQzbTBkQYJaqYJEh9oUjaR4YDUucvKUjqTZIGwC/nRzUl+Qy+oqK0R+WEJ6V5lzx65kgEWSUrls+youZKP2q64DQPyNShyfUJKJ/O9u760mVeQsyruGMg4SDpmtTHeJvBijXOBZzq6xQnqLpsXupAho4TISPHhqqwRE3IcPVK/ejtdQzCDfVB1Z7Y6SEL1jHFJ1HUrrYxLaT5,iv:hygJbilHwS6mr04D7H7dwScU1ya3S+rK+hk5okiGZOI=,tag:Ztfe3/652nkVdZh7Le6blw==,type:str]
    identity.pub: ENC[AES256_GCM,data:piEqCazjeveHlq2A06bbukIpChyzLANEBeaoDZKry8skv6cxy5+G/aZ5bg8R5N9zYckPv9aUgPe8h0VUl3hPSR4swc46MFNAiS0g77M9AZezY14LQVikbIme3ic1C2EMqNLHEihMOhve9YAGktWxvT5U2gBnKLjnI9taXqXD3o/UjPdgIRnQBGpKLAnF/nA/gmg+rGavLEZQJwudvhe7mEQPjGNsU3dQerhmqmvIUkSp4xPCJxC68TjpT4rwq9bfenbn13le0yEXJIyqXQ==,iv:inxE+lrHoeWInvt9/C6NFAFX3xsHMzXydEA4niuIbls=,tag:L5OFv1/pxNiObfks1Qnk7w==,type:str]
    known_hosts: ENC[AES256_GCM,data:E9uzAGrBldt3V5Yhjx/66QpcmD7ZLKrPBHRZ2kvtJNmRjqBRRCQbaYcepJmLDx3cr0grrAnj3OmM6bOazDEpx7u6J5EsmNFB5UP1QKc0dfLCxXnxwK3IMVAsU59adPnGttxZ+vpW2nJ7Xtlb/mk2tg8lPSliAWYq74fUYPWMRexV1lSrR9iyzdQIU6eV4+REOhj8jUdu5hffznb6Gz1qaDpzBU8Oce3IcNKY,iv:7S8h/bvNn4cru0auV6Jw1u2frEofEgFhwpk1E1S8Yzk=,tag:ur1V0knAXGE7LpL5449u3g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcDdHTERNREozK1pFdGxM
            SHRUN2g4Z2VlMjN1T0lPQnlvSEZoSFFLb2tzCkExM1pZeWpDUHhlMno3d2FkVHFh
            OG9jMHNGR2psaU5wbU1TKytFVVQzRjQKLS0tIFRGZlo5MytEVktvNnIxV25TQTdS
            b2Rvb0dRYThUOGFvZ2lkM3hDZ0duRU0KueLQRQnDK58D7DYo6de1/oqwyrU5VQBN
            PrQWG8E+QQntlU4eGAYPywunkG16+dGFSOkJ9ZBhHc5Lsphi+wKpdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T15:58:51Z"
    mac: ENC[AES256_GCM,data:o46wAO8TYzjD8ahlRO+otpv8oTdyk4W1mZhhiL+vm7+fYH7PUcUI19w8moFn0CzM9RXPV72yUDwE3SQmVItJdlu4yDvbxmVpmHoUFwNSgBXcwj0Rr7q9NLvLi9iO3n45vZjWaaZdjpHriMV5kMjxriQw4cKN8bUAGtHzpuvJCx4=,iv:1wzxIrAILaqtV0J6wxptxHB2/tc/8iGeKqvMsMrgwJU=,tag:aL3isWA2Nn0qEizwWpoFPg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
