apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Lp2LSHrUdFkxa7nEehGvQuWYgaWb8LKaDnJcodph7tvh7eDGzoS2/bJzyxPmpTw/FY2n8Pi6eHABY5PXo1REhwY0D6U5KfL1TDlcs/HAlwwAYlK5z2+rt1A13VQsL8s5HagtzLLUOzT1etcL35N1mDqgSGkRjyLFjMBlcyiGqC/o8KsLqo9FeTpcpI36/1qnNr9V2ujsAYcf2u69GWFGrNEzYuBuMYHd4DCCB9k7G6WBPMiGiiQPUONLlDZPe9OJ/UBo+fHJZaEzNYKfN74QvroSjbgxZLPcfZDUbC3oiBEA1Vdvfd4P8wdaHZrKbOidnl2XXc4V3HRm4xmlDUdAvMKkcwnTPsmuKxavJ0MO56ItnD8Dh47LU9onZIUCM1mY,iv:2zbwJSkYs4KYlL7+khfzeyRQEjKuvJyeHlpSSr9rNfQ=,tag:tCSCGYMz2gCOBeTJ2gmbTQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:nspAM0aHpfRwrq8HSl2ua44kGGZx8YpdqXHoIigzEcPcVPv2kt2tCik9NGKrpGQhOiywv14Qjy0607IO/pcj8Vy4sCza3vWWYg3RgfdWsU2RJb0byiW2+WGEFuLMoiwNvnZziG+iIXw1PT2kC+6BTyTCRSbCJtl+Ff+Kxd7tu51rkbduJF4+HSvMJEjDy/xw0NPigxZarawqUnrE4MnGcK+dj0pwlAEzgfFm97tjGHMJLbuKHpfGEdpQRhC4c8qTfKHlbimn1k4y+tL8jg==,iv:RIdQutVjNV7WRCqN/1wCfONU/jVhwrbirVQaXjA582s=,tag:BdPnxcwdEkzp9fyrfuV9Tg==,type:str]
    known_hosts: ENC[AES256_GCM,data:GqMG+RbiwdujCtqYsx//b2oSY7dyOMLZ2v76fviARwdlRvg7xOdMocCWMF1ShfFtikRL9cPMmhtP+EYZVtFQZtA7Q1JXTjJQ7blikRlsRC88bHLD5/0Q0sjNTdvcAfCFWZlde6VFXjvzxX8xfn2YV/Ou6B9uv4O+g14XTv9f18X/hv4uSFeinYVJRD/AurlKWoYmhy08guwlAd6q5XzQqrOMTP2JZ6Ujjoh+,iv:W3I0bO8Un5tg8H3g60r6T4NcuaWjdrjQSkX83PSP2ys=,tag:E6etfgrCRipQziWwwZo/ZQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNXhyV3NxOWlMY2VNcDlH
            c3AwVktHVTBJNmI1b2Y4bksyVDZNS3NQRVFjCmZJSnRQanZJendUQmlNNmR4T1Ix
            K05EQmltdmJTUHV0aXlLaDllOHRuSTgKLS0tIG44bHljb1lZK2RUV3gxWmJWT25W
            aklPQmIvbWt0U2RBZDc5YkdYem9BY2sKxtoj9q2TVesMQAQZ1x1CFTSqplVuuaAv
            JHjTwhR/F54yrOGypFklcWLWjMLCrsxYHTRgQyxF8q6zaZbt8JAydg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T10:53:50Z"
    mac: ENC[AES256_GCM,data:hFgeoUe76vrsNs+NFCgf8zph6jvYS52eI5lYel1UIXYgeH1F1EdHjUwU9UtfRAEjZqmwpGMSWxzTfbrBhvGHgQmMFWIGzx72LLoSk6BFC2DYXjkBKWMtEjoo+bkW69KZPNzhA4UHvijjC6voUWoWnQdCq/F+B3X6M6ewNIKCi1Q=,iv:N8fJJIsIB0QbePUkoKpSv81lbn8vA5c3yN1W/Uq528k=,tag:1wiavZZ2umD11LC2gxAdMQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
