apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fna3oaLTL/j/NjSDzD/9vFkDbp8yfti5Co7gL3XrkzK5YORt/b59qF3aFKjOgScsGvBXDlN+h9WhrGzJr1QZrYwPW963ptQCHnIJsYoNWIssakorEqRsxwsL9kgTv5SdDpvuSmSdXMRzv1oOm4PSHcrymUHxSJ84/E2SZrLf22e0iapb7HwHN3yELhXQ/f4C5sCxkfA7IEvDCucAHijEtmwo2j9dXRv/A5SaYeFB+4MGcAS/OFuHmd5p0DEjknV38ImPQ8zNOATBFlW0OHTbzU8BlH2RaXAI9S+m5SjOOw7UqSVR3+oAVCXEMII99WGvQ/U4jc1mKQR1ofn9TQR8bS1pfXyFC6FzsJiZeiPoUudhqTzoPSOjhBhe7hPoGyKn,iv:T95l1wQAv5TDuU+SCCybAv0CmMyvydpkfNcGqOI+dFs=,tag:5XrTSZaUdutzpZh3t3fnWg==,type:str]
    identity.pub: ENC[AES256_GCM,data:moBegwmAERmuSbmhwbrTAZ1CBndJT3QCwvzlOiLADJzqmY8jYRDFFM4blJ5tvLUwhaIqAnwdIhzDER6SpCXuILKFTpAG799bBuP5n0zKJHO7IQskmTLSi308SSrRtaVnkOP/UlJaLwNUXO0DzMutM3krSfGuqzRGKIxMwVNudaSZnQB24BjLl6SSuzH9XjXAXIVuI2p6cKVMHmZtyoSC6tuFow75RArg5VM0Zz3qHl6QZGSg6ViBX/PfV1QKrhCYeatqplnfi3eN36UE2w==,iv:KztJ4eCtWgiOQPLDauhm6RNAD/8LGMmlLjNl/kdVI+8=,tag:6lCfqg6GSpsvIkztWPMZZA==,type:str]
    known_hosts: ENC[AES256_GCM,data:7JVeVVGg2rUvq6A0JjRKd/aBBFNuAYUTqPubieEfkQzrr8mcVvv2DcGzmuWeu7R/aSZhiG3xm+vxqH7a82nwZKDZwNwhW8N0/6KKwIn9KKv9T88J69vo+wb4JwnwykUe7tN+BqyT5ebU7SDxrOo6Ud68j0fp9r2sfQHmLDgg7gieIsxOupHIgP4VnCGXDSI3kCbP56xZXhdLo78S/rvfTlfoRYkvuhtKb81A,iv:jUK7D9+dbvxr3m/FrhXiHhxGk4eyQb0kPjtv/nX3LIo=,tag:O1nznc/qrkibtKiBlJDbpg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcjgzbmptVmJzd0J0Y2Nm
            MXo5U0haSVNUa1cvVWNkaXhFOFpDbWlEa3dJCkRreG0raVI4QlRYRWlWYzUvYU1a
            MzFBc2VLM2ZCNUNBaEdRVERKclBtMWcKLS0tIHV1VTh6RlFrSkJNTHMvUmJ6VUdu
            K3ZJMGZCMWlQMlFtUGR4aWxnS2dLb1UKnsfhKxqerA2UoS8L47A9YQKAWhyqxPAK
            dKy+2f6C44EvI8U+5zkNRzX2iOksAu9sVN4OYXvfa8uO0r9NDSN8Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T13:29:45Z"
    mac: ENC[AES256_GCM,data:95oWRosrpHEXn1pZVaHUgAh/zo7uZOEaK4tXxlTE2nQAZzu2DHP2ZuGDPMzSWFMXJ4nJ1/ZSMM52B3J8E5aldTkHClcPF7YFt9gYsR7JdLrJNHOhXAfXcfyKxKnKGZO5juxFE/XK6pTGxyTn+RS6pjAsuBAl2PEqp0U6K4krFOw=,iv:g/Zsu3jTHmt+OboO14u+ycqStitFuMWtbcfHzHUIlgI=,tag:7QScQsGwga3m0W1WmCWUbQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
