apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:al7UPA1N0sq/Oq9guup9zofE/NubIXn3RpbGlkwBM+XcW2Z8YgbqO7PrPcBO4FAYk5yLi4YrjtDRxHt8RwpHGsZF0TWAouVcERdhy1TDMtezCxUCpTo4JGCHqbS6SFvuoqU7iDENbJeLnikHsume1RtGQGpKoyEfnJVZL/XfWOT3mm2jDmYeVhlsD2fIpIWfVnvxBPi/oOOgCOgmZ39p1R2vqTJEEt91yFwY4Zb0250NTsC/y0WUrrrgdvDMIq2nIriP14jDR0GBNieLmpLk3UuCMJH6/bqTv6oHP4iCzMdi9CrAxupzdLNqR0yPkc3abJJQIBwjrJczbk1CcBOQtrJkth5h0dcW723wKUslMLyPUv5GMPkJKnFW+tXfNA6X,iv:MXEQNE87BWQZMddHaZ+CjWBubozgs310vaUfSnU1Jew=,tag:ONExQGxR/CtL/2v2mRi1aA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ecVO5lE71PnqO5Pn8cMmEv5COpcIkxlpVhfA8kQDCazN3gLS2yhev87WMmCNACujAUKsOuqz18HCe8RPKSseiVQOSmvPXA/m4KS4x7PWY/tnm6xm4Cn1mAYge7mHOn4QfvMSo/sXGFaPQaNllsXz7LBiBPV92QB9cplrht//+8J/GWBgfhpd50v1xi21eSE3cF70Mw0nSA9w8eE0woCK1kk1nigI82fLb2zQaTskRM07y5WoG+UL/UEpYoR28UlvV7Ulup5P/o40huG6Tw==,iv:+MUWiLDri/hh2+rL0+LEYprz0BejpbReFdty+sAeoDY=,tag:DvSefefQQ8jYEZXdiGhqDw==,type:str]
    known_hosts: ENC[AES256_GCM,data:lY/aM3XW3Qv7R2M8z0CND53Rd2lGBl86x8SQjIXgc1EdkdaKJ0acYXnpqAH/ODHHHbTaNPmRBAmkNJeqV2y2S0SsPzBxG/0VQyKVBRSht7hGSL0zhoDoBICZhbWNOcV2zS0UQwK7ka/GErZ/t/257AgXdHY8GpMAkALcKOXik4a8DGr44DhP5bfM6Hxam3U6OzMgwDhnwOWMoXMGhgHg634huicv4MKNVGQA,iv:F392tDR9VYu2yJySNJ21aMox8+KArLnithqzvJk7gIE=,tag:ylhSQMfFYLJcdEKVlZsmgA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWnJSdjNyQ2VPVDlKbE52
            Z3lKblB2bDY0ajlDN3VkQnZ5Um15WThUclgwClNvV2o3ZnlhZ29wdDV6ZVZLTmhB
            RXZza3NpcWdiYUZqT0x6TjZWUng5QzQKLS0tIFhkVFllditINnhvVmZxaGEvNzhk
            ajlNemVpWTk5c2VsUGpVcTFPdXZ6MEkKmOIXla0dL7vQ3jRqE6OB7K3JUFQ4bOl5
            34DVCW/joKLpM2+f2eH1bnsKXqV9ZAXKhOVJr/+n/kNlll92gAvdvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T22:44:27Z"
    mac: ENC[AES256_GCM,data:It1ZumfaPs/8poD+jKN2BjlLkBRTUzIAVBtKzUMPriUGzw+lYT7fwxHlqZH7DFS0aGuuuHDrVuTXp1SY9eVllWhl9CCc/MglQUgeaF7LkWW8UzvPmcPdKqQtn/Q/PBUS+RjZxCPzSFx3v224K/lAl5jF6kFHr6dnAOCK6U3MUTM=,iv:PphGDSkFDmRdXbbDYve9Fqbud82SEqn4eZvQ9BfwiDI=,tag:1x6iSH9Rn410B+gH4ssUOg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
