apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:a+fifUyAOSDxHYW9obWVGP3Z8mRc3qT/qtU51c3+8W01XM3sph3UyPhgW0lgsP9BtBEaEMxqq3JCD1blVXnJMX5F6iupa9NsaBTVuw3msQ6S09fAa5ifhCygzjBJ71x3pbmuILq2kUMzQQgFOHDinBBfSFhP9kNRWiO2WcmiOLT5HLiRJLyTcVoVI2yyGOA4F4elWhFzknvDGGlU2OzG76oc85LrpLW13NcGwWmGvrTMG3f0jin3BrkIkfNIo4EYIff8iLIM69cuLFNveNkxOEd7qy5D73gyZVV5BGllaU456vsfVcqSebE9tCmlgWbH0DFseUtsgRa2EeYHK6vAlxrIZO0wjMPBYMsikdm1Z2m5+PTObFzbdgN06nTMM9qm,iv:PfH+afESggijnhfGAHQHWAwZGJMUQ/eCVSzmA9Uw+Tk=,tag:LQ+SuX+tfB4uFEtpoKQgCg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Y5q8no6jhpf9QqPzGPln7J4d3DWuiXJBGwhG+BUuqjlpjtSqxUgmJ812ixYJcOSrgLk/JW1TojJP+BYIPjlSWhqhUbSiVHEOYrH4xKBO3XJUkjEQc7DMS0MkrUAdz3lsLG0lNL0cyiCpIy26ZXAi96JTqwRziLia+/rjThf1Ukbe9H/VGV66dQMZ1f+GV9Ki7lj+C1TqV/piYup/L5irj4PB8rfyKqXwYHPFCoyXnQWIJQGA5xOZS1hsM5fQjsbcYG4+/ckYbKTC2nDItw==,iv:2bsh/Kof0yjrIfNoVaE84hHeXgnNXpIxdZwmJgEJbTY=,tag:DbfZhgPyra59mbqbKAHm4w==,type:str]
    known_hosts: ENC[AES256_GCM,data:wkiUiUWfXwBIu+kNLAEf6otDJsyhKKj9uaf4vr78lHLpkeUdP92ONJdajYmd6d7CH707WlJv9xHqivzQU5clzKuGkv90BxmRJaZS4WILbShQ6oAUZ+UQqH43OGotOWvpY7ZG2jDZsNcLak3BgqyfuIlhqYLJO5jRymjsJeH5VivlpPm8f76veRAH6yXZ+f7CMNNfzbnfeI0bdXokapi5aDCV70/VbETpAKNd,iv:BlmY7a/5tStiXNGWCAB+1bjJVjpDC0WxTwBcSMnQuiU=,tag:pij8hVkqsXiqSvpMJ6shXw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKU3JLcFVkVkgyMHdVV3FS
            RmZlRU9pNGhIV1VNTWhFZk8vZ2ExcXY3UEZZCmhranNVM0NvU0g1V1lGSEhwNlk5
            a09SQ1ZVZDZZd3ZSSFJmTy9oT29nZ1UKLS0tIDRkNE5SeUFOUkJIS3JqMVkrbUMx
            Z1c2TXFWcTg0aEVscnBrUlQ3eXZLVDAKfuMwSET40bhnCzRIG79xNbltB8eS9pZr
            1pWf3vuy7Hgp+AW3BC8EEEsdw50qZyWpg16p4sJmwom9VZf4k9YzNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T15:38:19Z"
    mac: ENC[AES256_GCM,data:mJKP2Xp3vNbcphPlfXtcCxCNyGXkgzdDd02bNb8LprsFpWMgPumT3zJ24rsHG3MJOGZsOKI9umGgvoy26TkTIP5nddtmqH5b/BGnY/p9YkcmjMgbDM6wwocNE4mBQa/JhjZQCqdhaJ95pNw/MexEBMPGaoV/G7GQVPyjCFd+oUo=,iv:SQ544iZcMgbZqzKZnsm4W/MWMcGAdTgogJVj3ro8hUA=,tag:At1gjdHiMr+DKIDu+tuR4g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
