apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4U0Wcjf/l2SnrgVjLAwJKuUudhWJbvFdNTxCZ3VdZ9EikEXvfjukSajGYXU0XzZn2NhFr7BOjNi2rLlw4HqZk4FGHI7GQM9MTzW03XrUyOAcAQFmfYdaikgFmsZ/0r31RYyCyuZ7WW/yQKVYpnmfMSYv1HoYbUMWpaJehpshaxFhqsuI1VFaGDZcAhylsUuhjawkemtNe73MWesitTsuFnQ5dCyOpz2jX9wST8ENWo7KdUIrGhrQftloX5PQDj6BuQOucnFRT1tjpz9gu7bHXlaeRNc0w37LhELbdMIqcIMab2jLPTGqSVhHuMU0gaN5PreBgqypToic/zNWdJafRquUxNY6YS7ftFwfhR8/B0gN5efIxKwm7QYKDzCfoR6r,iv:6a7Y3aAqnOHOS+l0CwSLOAS3w62UdtTqCphgptMJLp8=,tag:1Jtb2e9mUae7gDwh/ZqJ6Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:l+1cxQbA3N0L1ysAKrXTSxJjUAha1NFerwBb5eTmkpWisap7Z4Hf5g3KZot0ykRDKKZaHn5Cmrp1+HZpkJDUqR9CaLnunn6A6FJfeKIJUIfHgUkEUATEDYieFex0B5MN37pC0jv7DR64UGMxnlz/87z8nRLkCvWmXwYp0CZEa4VD3lfP7Jge0zZYFK8P09PvJdUjLXoaGePCcO/Z6Fnkgp+KFfQjpMZWM117IEE7AZo3NdRmUisT9VNJBjcYN7mfrz2IyHEtpeUtZVxKyw==,iv:r6+bwgUUNvE04RnVklg13WM7OHHzjLj88zDRD72mhGA=,tag:Dd3Wmteog4qFdk0mOJ5ibA==,type:str]
    known_hosts: ENC[AES256_GCM,data:bZ+vnPm+RlqcwBex3nOyQkrPBrgnTQUci5pILnzNiXVtTg4Ysuqaj2VSUcxYIjDVocfPvFjl+1+KPbaaMA47pO2J9mMEChDZ2F/lkmufQfLn0dIK5d7BSAUCBToZsmOkrH+Of7cuSf7dAhMQQXViVdTErfv6nkohgZNk4joIFJ1WOaCmk6nlxmINAJLKSBwOZKRg0+1bhnucOSTp9VwEgRMYo+gqobakcHcE,iv:7Mfu1HU7Xyvc2e5PzYgXbh6yjMTfvazDuXz4XjbV3Wo=,tag:BjqArKV7if/1aiKIyMiDwA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY2RPWTRTcnJJMk5XbnVi
            RDlmWEp1cVk4UTcrTXhSeU41RzZpaHQwb1VBCmIweHVheUUyMTR6WnNycEtoTUlz
            bWFEL1gwamg2WklPMkllZmtvOGdYZVkKLS0tIGI4VVc2VG1vU1FvaWd4azVRRGhV
            NXo5TE4vb3VtRkIxcm0xODhnY0drSUEKsncizv7cWVp23qJJED0XBOjM911y2dOa
            smdFaStasjxRu45ZhCKJ+yEeyDG50g7+Mz9v59XGUpTOygYaMRid1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-09T10:22:28Z"
    mac: ENC[AES256_GCM,data:Fqh4XshHsaseYU/syv7aLgJZGReQsjDKqZ3rwaV9BS1QKGoGhWcGAZb5l3E7MMq71yoNBXWir2f8qEO//nDM3l5wKbxr3VustZU0JaU6JWeWsP+Rb4nphVECR15SfVQ11CjByEnh4EhdPWX8BAWX3gUX8jJTP+1gXLv9o1Esvro=,iv:HQB/YKzzIkjfcgmJUiX2j9yOlb76d8h4+D5Bgb0aUjo=,tag:RifoaO//HJg3A4pkK4hbHQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
