apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:z7Zf9XlPavDmYux18BQYS0wqMGRZr4YWZlHy772HHdkh1EFlVRoUnzSoJa/Z61+8vP4OgHPTh4SzRs2K6Ysqwzixtv08xCheWzuObFN2Z6GTES+dLZlXxoYUhZTa6PkSPE2oqjFHakIN5adAEAOGaYom/GN80pMeKxO4NMlDxFC8QYxxgXQCntGEzso68i7uAWZHuEszeAsjswY3arU+px9BzeUewah0SXlMYn1es+9uOBbFvVbuYstidIyK6qEkESjNwuWC67mNqSy4EBcNOArOfJBYBaPzj60X7hCLYWVP1SF1NLi6tPa0IePJpKQ/9um9K0R3qP2GiFtQWW1P1lTAK0sODCNME0aan1ty7aVOT8js3MZ+lk3aWvipEySv,iv:lXvjoGCQmHB0ee0FdzFWpJQartomaeH6TIW0USoL3Jw=,tag:4Q7GBENPROVxWWE/K2o+hg==,type:str]
    identity.pub: ENC[AES256_GCM,data:eHTBxKsI4g/CKZbJysUXNl+rn9NP9nRqjN/IEkDfjjwD23PtzE6EyAolkAuprnB043zKWB4UwEr1Q7eoV98FxFjcTSIOFOOLStkEcyK0d8QKo+yFoesJSMwAGYGsaVjeOWxv5YI1zU2xCyxM4pZKUJ/m9374grrZ1i7TQpylkKQzX2vNcuzENvqU46m0k9GfpioYFz2h8O5uE5R/7qjwWEywvKHmCU8q4Up1eROYhlhgSEiiqnQDIDUhFCUbERItTGpij5E4T7rGyslrmw==,iv:EVGiqMrN+0mSyYTkhvkTSEtf3RLkV18DuZuwAs+nhmM=,tag:8W9BY1VB8z21uLaBTuFl1g==,type:str]
    known_hosts: ENC[AES256_GCM,data:0GTdg0bQ476pHLn9jw36xC/NTxh062Z2lNl+T8RKvN4AR2CRC0jOuHrOtSEM5lBN2SrZOBzh6jKq5cHvHMP+N1eH7jHxF1ygUVFRdwt8AarQjXypF6T7GUMGmDeAL50t3MK0hLQet2v1Jeye/BZPAq1drFUHpcHk+Sr+npQypzVbj2GopxApI+ZrDOoVLvtLXkiV85z4K9pKvfBIqhvSA9RABnVOGbmKmBxq,iv:oTGLjQZbJYYAiI1YXGNYPw21PkACoRtfd6Z3QyJEUhc=,tag:oSJZtXF+D0iqvzA0zKSarQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVCt2a1hkNmZ2K1dZMGhQ
            aExoMHl4b3RMNDFMSkZKZnRYOVNiNWZITzJjCkwzaEpCcDZtRFdOWHhHaG5kUmhy
            OWRER2RoZENQck5pQk9rQlNlRGY0WncKLS0tIFZPTHNQbGdiY0ljV3hKWngvMWgz
            eXFpa3dteGV6eTdFYXZWbXFodk5lRFUKQc+ni7Sqp/rw6a1R65s97AVBKLDmcSEe
            Z1pjtR08+wIwC3UPkkaq759x/mrIW0+vpbFKt/kMHqcEuBL+SQt2nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T17:51:54Z"
    mac: ENC[AES256_GCM,data:i4OZAbWyXsUHDa7YvjGllf9ztrLs2xDofs7+49Wsjj9RjQ+KtInX2Vq1XH8x3s37XtkQrs09ZaESJ0w2qOWFKfJuYlVbifW/C91ISO0ksr66Hw1HqSlclyNFhkJiezgMIOMQ0Q7xoz1PLJBt+1+tExKjDVpG8drr1quNdAcu5+o=,iv:8v1VVxPF2IEfHu9SFZf0UFsjb+hAIjApVkLoHBDkFoY=,tag:GH9FjfRE1d8ZmK+wKXP88w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
