apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wIjKNthbVcdCSsm1hdpOPd9aYHEWAE8uXxk3I11hK84g+udYSwkGWYp2SxWxNZAE7KNyAuLE+fbvbPbLiw/CQpZBOnHXa3ziG4S/HDQSqyplWo0vfKGctKtbOGG730CXHhx4ZvkKGz5UOcs2IwrKmaPDU9b5sAa9Uft87FjAl8zq6GZxPwFSc4BO0sT9eLOZ8dnAhMBw/F0iUlRn+y4IZaSszuQZH5f0AWhs7+7MTSmWVNtbmNtFK+T6tzH8jsD9AMXiz15P4L/zKYaR7MbPed1ULFDIRBF08PudaNQZxtn4CKjxRSo07+ztHkU7T6TqXuFCxAxOOQzAOaYhkFfbGLUt8D0XqasMUVbhFFAu+wX074lGEFJQd7TqgN+Dg0dO,iv:qbowkzmhoNOo3eFX7usCkkUfy/htR7OC298KteJGTwY=,tag:G5HTZD7gP5CgQACMIPnvLA==,type:str]
    identity.pub: ENC[AES256_GCM,data:z8SqdkOz54TdDblhFBaAX5xIFuQL80APElnz0EsQYHS4KkF5apHohcf3rJUqkUQ9ClMN7WQ/mXDXUYpAj4UDsRWOnqMQc9aTeAKrGa+T83jNcaa4ifzht/g4MAqdnIEUSrWB4DfBQj03w379CUYmSa/UlodhxgTeBfg9XixvVL6Doc1GO086/7geLZCF+vJgISZciDdossdxefByJdbH6i5hp9aqMP1EyLtaCuFoVZOi+HvTrInQ2JN/b2IRDiNsvMniPj1qvz52+JEC4Q==,iv:FwfAYQy8ec8h70Udhm3WkgL8jIS2CKOcocAFPZvqQAU=,tag:NfEPSop9DtL7hZMVuDQGDQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:2fLFkPWyQ3Yp5w1sCBYCX1cxB3PLz014oqL7sf36rpxIdkjoFV6O5DUEa/EodNjvF+iIh0J0V+a6gqxreTsEUoN2dZz6BjCgsziPtLXt2CwW+Xp2UScJ07OJkqoV9JFjfEzPqCgEEuqdH9Tt4uLZHaleJF7KyO4HVpRPb6GF2Qv/neDu220/m9QaA7GVWpVzehSDx9Q6rccRCZLNnpqlexf5xXhPJtkZjQsY,iv:/PoCw3KGdpJCowTYA+brEgbAO4MxDJg03sYAIYf5HFA=,tag:UmdD5nKGanVqdOmgO6RfbQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVVdhRG9zbGZSc1dMLzBS
            ZXFKeE4vQjVQb0Rwd0d6Z0YzQmEyVXRQQkIwCkdvVWlWWGlqaWlObzF2NTFIaDY2
            b0x0M2d3THVSRUlaKzlnZWJSMldpcTQKLS0tIGwrTWkwRlpic2Q0NU5rNk1NaEF6
            V0lsZUtDMEpwVUducHk0Um9tTW9lN00K7dMINgGnNoUG5jWAV5iQOxRXu+PeTMj5
            fUR2kjXrXs63z1iOsCaHX+Zgh7v6V8wFzhYD716srh7dOOkBeEJhvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T12:07:09Z"
    mac: ENC[AES256_GCM,data:zEbGY85n9A22bCtmTouadYYVHzp0iiAMBaLDoM2CJPYJUgyvV8O61eMUVyLjzTCXDh31D+XiyPfczG3zNfIuoh6aFVfvr01MXiJdgF62oNqqPq6Wqa1Hu6hhcQ4AtfBoce0PhjQkJmI+pI3XTOeVE1l9k39sr0J4piYY6A75i/w=,iv:OqTHWBAG1kQqAp43k3eX62eR6iDWFDuhDuf+ARvzI2s=,tag:xyP7wwBHxDax/vsFdwcc7g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
