apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3Dp2jo1HEFiriYSyjVATmatBIoPUIudA0mTxMF/6+fjmHUHYwoBPO0qZpHe6Lz0tXsHcXcNBCRoMSIg7TBu1NA87J4gAGAChsGlovez/Ykh2aWzTuTBm0QwU2fRDt9riHmJUFmpY5SsZcJRdKYJj1AZLs4w71gFSnl4lQv2Gff0qdynm40KknmENwoBVDF4brFLSKWGp4RRG5gQyPAQsJuakKzNDKlG5yxficY5g0FWQW/lIHk5BGPrDrOLFPp8q9wIRnktZVrtFs8+iQ1AMnNyUQ4WK6iMvRZDSlc8yQMRnkMNfEHyTd33FPs7HitWrf/uL+XOlbvEpeaZEwvLk/2rZnxg7/19ylT0RQW2pRnhaoH4tBF2ryGNRHJGsFWq/,iv:aJ9HKZeSFNcum13CNhLdNIoiVnasLYK8OF7wIV2HL8M=,tag:IW8TXWWdcQzUOixRHGrdxg==,type:str]
    identity.pub: ENC[AES256_GCM,data:dLljxsZ9rrevXjaLg/ApumLUMxRLSOvQ+eL2Xeb0RpISRgVKZu84Gq0R3kn/ECXI/m2HJ8R1F8ZlS7Sa2N9GuY4O5C4J4hvH71t2uzhlthFI78qKG/jLdjtBhBQuF62cUXOq9+wyjtRXnGgFPPzQU9gsUrit5dl//HZI/R0THY4Ey+Eko3nyuUtuc512fw1V7ZUMPa3SgSF85NmKrJaMU5MmbMaeeAgArRIwddC3QVEqdB1cmDSA9KoX/iUsb4/5JFgiRnC9JgurYf2b4w==,iv:Z23nptcIpD1Kn5LH0h99eHiO/pcvSgXu/sCxHLsxkJg=,tag:C7SiyWOJ15GgUnywFyk5lg==,type:str]
    known_hosts: ENC[AES256_GCM,data:1Oy7AzyLLPAuqCsZAl3xmgKoN3x0PLJPATRczPmvV1IqEu/Px04VwEvRghCBEOQAVC6SWe/qqJ9wNVG4QsW96xelFWE7cr8yIm33EpmWo+cVHNDnqhx34c0juiUkgHKc7mPAp/fL51QjPS7ARzU/Nw4e4usPd9FURTmk81PTj1OPqMKjuZzZffvJ3tz58/ZfhtRJEDq6jPyX6Vi9M9SBoTefHLaHr77ndSaV,iv:Kc1jOvKia+q43ONaHVhsFDNCc2WZPNWq9NYYF4+DhwA=,tag:y+gT4XsPkGFv7H9sMblIJw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dzdySUZhWGFCcjBJekxM
            MU5CdlpSMXh6V2JVWGYvcHRvNDZQTzlKN1FVClZuTkIvSnlTbm5NT2tpTk9vKzBS
            bzNBRWs5WkZkV1hFYmNHeDRFdXN3WEEKLS0tIDduWEZmdGxTUWFJdGNlVUpkZWJp
            V2pYaEsxaTdBUjl5NjQ4VzhWOHlHbU0KTvjBR9qLRAxxtaJfs8yMo0OXFw7NswuL
            RC93KqxgHAI2WS4Jy59vmsHksY6tHvm8VPn3nJ/QizqYQkJqWLL0dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T06:48:37Z"
    mac: ENC[AES256_GCM,data:3+yJfEbk90OpR7jaTyzkdKvD+VGkBQLkoHCvQRQMVMdpK2C9ITjLDwXNTJqY8y9s9vt/MQfbD2oNCBgEFWwNydZOMoO9X5yejvY4d51G5XcjgJECr8BUH9BpAWyJUdYAaWoyQfEiwXGrjHFR3JC1nleAWZxFPmm8PSNUhl/kans=,iv:9LBMAnlcFR9r54rR2f8XbunAFl60UerD7pTPLhMJQqo=,tag:0lUIn0QunYZ9gUcP2UWmCQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
