apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:V0JHJIdzkw2m371HdVjDHI+mtYkTCo+RSP+HIq/OwrRZVJ98x323HcFPlrQfiUKiN+X5e76Ui4CASmLUMRq2dNcC/Tjr8IoQVMjqT3NEL+4iXVHWIpbOlieHIjLI70vSlgSeNsg9raULIP0dbsLDcckMZOx5HIK6p1DpkbQV2M6jiWoZghYnKDlje+bFVQB4Z5WYzPD5TVnMUN1OxHb63gu1rywRcoNbvdxUpgER8CLJKCpq4oUPXqcogZDvEtMbx8zfl50HG/B88qj++8h0uvCb+0A2YnqqQPJXItJ72CgR6rAhLXDWdoKnq9AZ51ceJFkxkg+hqEhdo9PH6X/6BnZbBYutF5z1AuJGRQBdzyxp4K+94qfAQMs26aXPOIqI,iv:3WlxAET/Dm5PLhTQhXLyqblLbasQwKu1HBm/jx1uebs=,tag:2qWBexOieKmLCUaHnmx4TQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:SQkOL62RQ/gehFjO2Gg6b3YkR6teO2DOqNDNbFS5AVHL2dKHm8XKhVX6+7tMhXxJdsj/aTdK7W2hzkNRez+RG9BC3XzS374idcrbiW6F5NtfdOkOtylToqeFc6wzYVzEV1VsJgEmlT05PNw7F6vLcMryLUCrwrc2odtTkusE3rKrLDF9uTkda8we8UKZo5sXqjO2Vp6Suyh+OLj8TH+mcXcQHDQuh1EX1h+0bbMKMbnnGg9MxUU0qWhMFu9dbUo+WOzWSiv5mFylbcInwQ==,iv:dvs9n7Ax81B1ZLfU9TNntn/MQvLJL78OYXQlUsfCuQU=,tag:ewg7LWmX8sTDSxQO+0hpmg==,type:str]
    known_hosts: ENC[AES256_GCM,data:smp+vZPqIwXPOZ08OCUXpmXjALoClTe2UJ1SAG8zNG7wyaGwUBP0iIhGtgDiKVMl4aZrVpZ6rxIP2BIrQSa4Nc2xPMT5bGK8xyqEsFUUVj7O4NLFdXpxVZCciKxJVgFrPSgnmA/RUn0C6e5E6ROpxxGVL1FTgCsUGVCI0GlcZpdaNT8V9DDqBdeZw5GVMcgpMqu1UGi4v6EKO5VAx5iJjPIuezo08hiT8Egn,iv:SkBhJjBY8xtUR4B1GRQuEqQqOI6QgNFcy8dKmRhVK9A=,tag:TaLcjqP/b/mtFcNm2LoRmg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtY0RMeExnTWZkbU50Uk4v
            ZmR1NEtNQk5GbStSdmpJajU0NDRPV2tLN0JvCnZQWVpkcm1qaDRQd3ZOWUI0ajU5
            eVVYUjZmWXo2YWY1Nm93SGlXMVRVOEkKLS0tIDBtZTB4SHB0STVlcUUvcU9VV01s
            Q0lhWXhGWFplUFNGejNoeXBYdmpBVncKeVD1z2N04QiM+yvGhvPb4sj23XeHf0hL
            SiP+A+aV0nYJikrlSO+S6aEBz0nnogR7p1vE8V7NJ5+U7sLZ1zSv5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T16:20:33Z"
    mac: ENC[AES256_GCM,data:B2EK/cQvbYYujQ9c6t1+sJWcpr2cB/9xIEICSKaugef5EjHSMFogAX+GqsDSMAC3ddK9jHt37zC0Aaq7f2kx1486dU92clGZwlB/6adbkXfKSkRsbh3O2hIQsr7T2n9QzMRnIdB/iKqiaYbPXYki9QxcYvnpY1FFmr3HTPYaGTQ=,iv:aON9hupHqI4Kv1YLe8p/SWipZreGWda2zTC1cZ2VMf8=,tag:U8QMnnYNuo4VCTdYWw48Jg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
