apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KbSxGuZrIx6o9zUnE7ms4vARFgtgvPm/IM5Zfvsln79dYNeKr94SHE6qGadAIoV1hA083zFFDKo2ecqpV0JT4VQoGQL2GlrQJZoGkf6qAyG9gAgcjOOAhdOzhooL5XIEIrZNrbh/6o0LJxhL+hgWhZKgKGZGKnJldJPjZimSB0b/hQ8w9IvnyGZ27JW1YSxr7v06UNFOQ/IpmyXnDHe+jlVCW31qaOUHRIGvFsaZEOcSj4KpJ8lEEEdlYH2N/TGMBGYix9+RWy6uvkIFK6y1gbt48nQpmR2c3qacLJVuKytj118DHXSSm/eiFFZ7P2gD7xDWxtBl6AMxoU6ipwnjEjBHDYkAu1RxCJgz28cFAUGFuw5xF9Rd7/8B1bCEwGbk,iv:8S3UYppBCC+55pyI9/bd1Ui11p4xCsh4l1/2TCK3olw=,tag:Lnb7ldPM0Ra2P28VKQqnQg==,type:str]
    identity.pub: ENC[AES256_GCM,data:S42Y6iTl99io4p9cMEXHNr/tFoJ6/1MjWc6wVNbRJsSTmsq3vAInkIImnoWbyMfWMIMKAWimWOZBbuA+wmTo2Wo+4ymHeQg6Wd/mpqp41tTgzcTtyIVPb3WAk+ln/w9vNDGlUYvdP2/T14xtnu9xZXmfnhGWnJxXuEfdq/inQxBiK8++Iok0UmKHTC0e/4CaUgvJ0Wd4Qh3rqHI7q/HfzdPvAvtWBshU4RAqQeISF8iEpUkBnF7k5S4b8+Hi8C+3f3LQPwUl3t8JG77Kxg==,iv:YEsbjImd0r2b3+a7xIUMrc1Ui7q3tWkGnkfzQ/xdLGk=,tag:XfQ4bnWTibLn8BRrDu9c4g==,type:str]
    known_hosts: ENC[AES256_GCM,data:5hqQGT8Z/NnChqk/GP4gw4Lefis8kYGKrS/LEIi+JQM0bZnunWDf/3D7GoueSfqj127z5h5jZnTE3Z2JmACK760QRyyObcdHRrliSHdcDSASanO1UX7QmN2A6qY1BFrzdSZfBr9nwEQoKiNvSNO/J024kLcQiAhNCsxSkXWzdhmHp+4tEqpn7Q/uFJrU/W6K0rdAhVVcdK57qawpzWLNMo4xHmTC5tD1dG5Z,iv:JLHpUlRwjqKJRtlmcmGPvaMbizVr8ge8yeS0E8r9Yp8=,tag:A294sOS0WEvjYJL+CHmANA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cStQc2JSRFJMaFBiZXVB
            QkFQYjFVREFMUUZRRFpBWGdLMVNBZVkvUmw0CkRicWMxNWtXanNJbExuQ21JSHRB
            b0pEdWdsaHM3bkNZUWF4bHB4bmM5ZjQKLS0tIE5PS09LNUUzRUVDU2xkRk9YUmNr
            VnIvM0tYaWhKWVd6WWVMZzgxK3Q1UmcKu+/YOnJgTeRgFO3zKQRmA5kS0Nlv6IaR
            3vCc8ZFoUjxY2XdO9/mYB2Hfrz8ZrDNfrbxGpz+qfzkpdCyByMdsKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-09T19:55:39Z"
    mac: ENC[AES256_GCM,data:+WwL3xmfaLumTOyOHNkOdzEtumaaLZDvORGV3+bren+A/l8qWlorfqbp2yp0kWf+PHXP2Yst/A75YPihm+UUXIWTg9GjtXdGAJHV2ZexPx9nTtoAWC+dBz47EiJI4WGUiiHJCXyXUX5j6ZEF9hygPaGyrs0MpLbz7uOcNsg0Sc4=,iv:W67S8MYms9+W4oPCkq2fqMDDj/s3xTX3yD/Onkzl8KM=,tag:t4BY8bh3Xi+TgXT3jAnBWQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
