apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OIj2pihlgWyUJjBQ1Y6pjT4F4f2sxPkPHkR3EFqHiX8+VJJAM9HJkATyA0Vh9/YJ1pZNyPZ9kgmYf2yWm8wh9AJrMuN9Zh9dH9cLbctnKWyIaXqQ+hY1MQJQNIgCEXT1TeHo7UelaOjkj9TYsMJPWBGZyqFMXy7OrpLEAtuFkMnksKZJaseEW0xhqE4Y3MLHXJp9KteGs5f5SW2WyzqKvY/72xkC8aiw8k/5A/pffSPSYjhvlVdbYXHxpFb3+QKD/QveN7OoHeTrXfJVQu4JLTpM2DoFH/hRv9NZwdeXXclSnPOvo/0xDiY3eDinIGG12Rq/mjwjvfG5kidag5OQ2IQeKHfYPt/XyvCHicAuie/ALwxgC5EuDlSEGUeHCwdt,iv:65SKseS7sF5DKoCGFlN3//i+IA5CdDfTyuCNJYxDfG4=,tag:iw2Keje80f9DJL4dPUqbzw==,type:str]
    identity.pub: ENC[AES256_GCM,data:OwbMTAHpt2IEg6wL7IYMcgcyQB5Lotx89a0DqmwWDhKVLW72yHJ/cRURAWYhjcBj+jVGjAdMnjMUjSaW5Ffja7D3o89DOFBVbTLIkM8TapBwmkNyiwcb2n0dzfRtB4zQT6K7CC0cCmrvvnEpQ+AR0QOzkAp1ArLGTEUIoVpKvVXvGCMKdWZCTRlTjDrsHi6QArMNAnJHzpwivhNWOyuf7FRQ1nshHoxoiHsQHfc2ttxoZltxP3Mff/35+V2JWuIrnU5ZZiO/yP1o9PJDbw==,iv:t8VLB0MzZ1RNt0vO1aJEVNrNO4gi0cXMKiM5AuxBMg4=,tag:y1K0udvUWe4LsiK+oRa2Xw==,type:str]
    known_hosts: ENC[AES256_GCM,data:/OAT9JgU1y33VsiTKvj+JvKQy5G3QI4D9KZD8zLao69WqUsT13/TAGUjhrrZERM+xVbB+eDQSUU+hFQFmmfEGgp8/X8aSJJRgN5U1d4Cf5X1HVKnCPm1rzRR5Ln6XQm2wKlt9N0iK28OIZTNsY9R0L7td5orHI9F9xJHm8wr2T6AwcgFq5NmPw9jp61lQNOcnvWVOBQQsDjX2DK6Uy08s+tUek6Eor31G3nG,iv:XozwtitRPTb8vm9oZGFxzHv6WqbdhF/e5YHQm4FhBak=,tag:81uJn6GNx+ZF6FBsfhs+jA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLazU2L3pKNDhQVlRmYVIy
            OTRMUGQ4NnJHTkRmZlpDUjdXY2FDTitMM3dJCnZjUU9aQnllNmJMdFU1MkUvNUhY
            VG5PbXFzb2t0M1o1WlRBTUlxblFqWWcKLS0tIFdnQW9rL2ZrclB0THdBRVVxRGdj
            R0ZGdDdZUVVTZDRkYWFPcmhINGdnak0KkrxbzNXG7/N2rOZR578cAUAQfAQBzO1R
            Elqhza8KH2xoZWDbwD4pf21WNG4u264YqJlu+sslnSxDElQEx2tTZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T22:41:19Z"
    mac: ENC[AES256_GCM,data:rJGONVr31LbtzzniwUXmQr648B7ovAzOWSN2UjlzMyt2WRpd6acAtnUuRCk86WfPTnwErXy5EKszfIyMtUcWEFC7yePVvYckiZVuSU1RYNYEW5LaQf9sIDhTAIv9MoC4SA3UvbJ9ryeIGZcIzRfd+NF79bgRJjerQOysP5usyI4=,iv:qZLmPmL+jFDtDYcRujBRuALZPR8/pGobv6oD3q4Q0Dg=,tag:HQDNMARy9pX9Mj/nfC+t+A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
