apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zyjz9WbSqytD6OkJg/DwcjI8961OqcAC+bnJG99VddnQpYPn3pINUJEZC2+t2w2d50eBW1KdXClXPLDsvn4YpPNR/KKxGrsF8MOXmWOuhVs0MIA+5kn1MhMMLsT/Oueh7GxxnKfIBaw/npEMTu6DNsb1aE3hqE2VgyLA3WOQRIzAfhXZpTAVYDvvFhihUAqZUKZeHciodwMHzJoInyGm82jttstimeuL7kJs5YyPsQC3mVUCJYuoKS22gv/RwetyqsjqXOOfJJmGreMnuFEahglgXiqTo8QAeW1paSVZJPuWdTte3egAyEsPtfsD43+P0hgic9cxeDFhpGgStQ+X5PXf/P+UOaYjCHjcqzx3hLxU4INpTL6CfRndbmjVQAPm,iv:RwLCqoGLh70EliFldWSAI23nF/GI1zcDwegh05gjbfU=,tag:wEWoF2uG/tXUZb8bhdr1gg==,type:str]
    identity.pub: ENC[AES256_GCM,data:/p1HXCTAZyBz3wWZQtZnQw6NJ1/Bww5h3KVIo7D1+tJMWmFq6M3JQxoZpwNlriQU7ODigQMiUsNX6oHVRy4qLwDtEwmUjXgakgaIbmR/7kajpC1yvOqZTHsqGrdhCsmcAEHZkCDQoN08r7pxwXjFwGI0OHsaX12sYR5Z3rJbwrm9b0jo548VBQWv8LMYXh6TP3Geu+2AdKQCt2H5fQz5iahJ6Crkl4zeAqYC3MlGA4mQIYf/EYK+i32JpIfk1W62XOV7fsJc5bispiBurg==,iv:k00e14ubQfLCJHf0bFpAlnqdqrdp98DheCMo7XsjyNg=,tag:5VRQ4Ajkk3BJCMCxHZLdrw==,type:str]
    known_hosts: ENC[AES256_GCM,data:52Oh24dKh7OJT7FrYZTEKyhSM5aK/z1m/Hxv4pd5xpyhEaY/zv8Z0CR4WqBTP4E6UeNoBiW+WTLgwDabSZgKvEFv7MqEBtyR+shIucmS/rZn8MrgN4h9dZ5yOsawZzUyFP4P2DUMLkcBRXP1vb5Oo4/wIjlcLMNNO5qPxE77Nvc1Sm0vbBQos3etkla3yZLiYAh/K4Z0JFgbQdO/8hO7KmihJuJBKgDshHE6,iv:94Cbdkdx/FmGSFPUtH5e2wop/gjSYQ47KynJOy0901w=,tag:E172MF1JWfyWUhEZNq/aJA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOFRJQ0I0VHdVcHl6SVNq
            SW5rcTBFeXNSZytlZCtNUDhhS3B1YXUyMmhJCmtsZGtEdjlOd0VFNytjTDh3alpq
            UW5yVDJRL2NLTzR1dHFrSzBYdkR5K1kKLS0tIE05WCtLbUVHR0FXYysySWNMVWlJ
            bVVWTkhsU21hMkl2ODVMVTJ2bXpvbjQKaLGldc4LpWayCXU9430kEP5XCIIiZY9g
            6aBF5yxHOPon8C7l16hKHElB7OHFwgxh32+AjjUPHr5I54TZVK8FsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T08:08:08Z"
    mac: ENC[AES256_GCM,data:EyF2AjrnCkHIjlwDINvTcLyyMBHfgX6fIGM2oZ3ItYZ4q3dHJGntL+CnlzKZcKnX78WfIRyGVR5740BpiKn3kwrvNLWYHkX7Xp5lciQ7XnHagJmTGTiTynt6Tk5FIIKS18X8YZPfjDl3PfvDX+UGUmXMa3Ys/v7biPqo0m2UdLA=,iv:t/PVYR/qMAyn1SXFM91yNJTi9VSLEr4mkQVcfS5NtRI=,tag:iVWXvkXXacFreuYyy4HmgA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
