apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ES5rOINSSsYXnV7Vk5dpcds6qhAiozVaH60IS6lwZ3lGcJpoRrCJLOT99zBfJMsABKbn4h7xjWFwpPcact6LeWerEr3UoAeIEgI0TEH7o6MHoVqtZfRR2ziKQtfoaLHtUYE+f1S1qcaVPDEARs8mRfjdN5nUjWltiihNdC3ZVqpKCFcJOCuGRAPxSmb1votOw58UWX926r4n7ENAUldsOBUxhKgpgpNyXOo4rvjh1hUkS75RQptrsO8zjJOOa0yZfCj29Wy7ofa9q9WZl8s0FyCF3VG7c0LJM0l2dgzmVsff0oBjjdHLMoAeh5ysLQjAuT7CGQFbJKuXVuJbHx8P/45YYoMkiKeTwRKZkClQQ9t5rz/Ce2V/lFt9TSMMd2nK,iv:8eKh34ytAbLfsVCdkWf3QGF1oHV1/UgiwXF49Rzjx8I=,tag:IejG5QCOcsf8ME9MgGMN9A==,type:str]
    identity.pub: ENC[AES256_GCM,data:p9yty8IVmsE9viiNJSKgXUNCHd/ymtbnOnK8tYfRASKPJuvdh2IKwU3wBwAbViceYVIy1XE2C1CQSdIAhmLGc0NOMEOjzq9bOcOtecybKoaJEzAWRvCC1+UOT6waV3KHZfjHJsKE8WpFaMCg4fQCgH/iM534c50kQE/d2jUX8927jb2FxZ9aChhCe55f60v/JUAiWWO1vFSf/i80yIKhNeVHlvnwnfMwMxVCULtc/enTs9Zv1zDY9/FdKz/Qlh0XU93q8f4aXGV5Z4V0Nw==,iv:3JJzDUSRKfh9mum286O9gdv2LHpA1QLzRG0ifqsI87w=,tag:/9E1Xvw4hHhnjYAmiHopGg==,type:str]
    known_hosts: ENC[AES256_GCM,data:lg8TebVD7ESQtMcVfyZN1njUmuJS3fchACruGQxS5V3wjgk5UUXgw9ZIqbr1KN8pTCSWyKdQB9SssIhkNi7R5zw0ZOwMmHDZhhtMi+ljpI/ygB7zAJdcvCCfX22rhK/xN4giW3+Mu1ksMxcCYr4A2MUrpdeb1c7mMnZHVUa3doMWhyJ83odaaG3NCjO2QrAPkleBiwRccOU8SCr0ufpCAe4rZVGPPzrRWKJt,iv:URAiKus8F/dfupg0HQrbSrk6Sp/uB122dVb+92TGSs0=,tag:eLz/4ynlizRfPs1UoStJNg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUN1pnN0dtQVp5TzhDK2dC
            OThjc2hQVlVacWw5UUhaRnNNbjRjQ0VVUW44CmIyQ0lSKzZiWkhpVHd5cUk3RGJo
            b3hSQTRjYUtjcUlLTW1oQ2dhb2Y2MTAKLS0tIFhmalN0WWVXVm53Vi9pelNuQi9O
            dTdQT2o1RGhaZTN6ZEZNT3o5cmlTalkKeYTp3CfoTFNTHoY0xzR08+bS7qwX5AFR
            wUAwIQ6EeQ3mql4cZRqpIrb2bMtDwZVUxU7fBtHFIUmWlAHhr3ulVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T16:52:56Z"
    mac: ENC[AES256_GCM,data:w+H9dcoqypO5B3tN0+XsWwwQG7IU6TkFFhKoy3HHRO5u6Bv3VyITEfE5p4m+f+1rGS41n9f9UCqe6uLtQxce3oJQGXYxtBTDQgkljcrtH4MUlEsEjTPFh2gTdZSrYsru82qOvUg71Pz/6w+1A9Ot/d6pEApDaMYt9gkD4W+QupQ=,iv:Tl3f41tvY9Hxc7N2n1A+T6wlpbFg41cXQHqX8OIrWxU=,tag:T8Xj4jK79Y6Fg+Fk7EA8dw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
