apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Zm0Nyj9Awa/zdj85OvNLJpuVLPUDr1660Q3/+as2Q5kSX4b5Jqbx7Zt8P2lCe3xyRwy7C+IrntxYa6afJA6VnxxbB7rwZnOwkCGVywKBm5T5Nr/YBbBwh4Xq3crsXDc7dlbRhl7v21nwCs3vsvd8ONBnC/qRAfLjpx+rKa1yOARukFplgyipYgy9gf8kYLKEPe0+cIRtIejBdI+nQgjnx8Vg8pbub+Q85s/fTApsGAT1mphctkdMbGgbpckVBMxwrqcO7JQ+W+zAId7tO+ESEtuTECcY/USVmQz5tXWPqn7ukHNclKzAwsW/1V/47sjSI5PfeeHXW+MBNSOa60YZRAI2mROOMJJ44VWRiMM/9psauB1KHHvtosuBEiX7FQto,iv:4DbmtLdKYqtCVn5lR0CFXCCWglOpBA+9jZXXVBXLkpE=,tag:KqJvYnfroodWOBButCChrQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:yLxcoyrWGVLSRQhspKH0V4gK2iuCST1yryQrPEPPcn5Bf6mFTh1hgIpk8xayO+2RXrdYDli94xITcE2MyFhg4nr44erL2xnCBA/1Z46FH/n01eUrzMeBtbKVCcAU+uTCSlfld1BNWb+gGNzJcBRDMc9gHXYNK/J3k9gKthB2JzIDPqKOgRZwSGT/UawMwHceq8mv9nEhqlEkHnFvRRMuTbakHBjTlYTd9I4z1d4idvcmgaJXQnJwoD+z7SPbrRfh6ONj+/xSRTRDXwaK3w==,iv:4p/PT6GmSFZIx41EjfkDIMgAVVeJys6FHwCaDjGGMJA=,tag:/5cgkxn9du7Lp8joCekgmg==,type:str]
    known_hosts: ENC[AES256_GCM,data:aBighYmVlK/Xo7Ls5mURxSJIOTpj/1qdNo18vSHLA4zIzlJioekQilC9NVCE9nyF6YkEalYHcFSeqddlAtv8n8ohubuHSbdurvJM4XGJ2k7aZeNV4v79IejXXI5H/vX2B25VpPcQiywWHwwEn4s5e59Bhijpgft+cdgahKvmzVXq0vCxkU13I5UMUz3Q7KztC3jgeyrXCfdCJ1DERAZJYD4e7r+7SkdTEYDz,iv:caiwxKJMBD4yL47sgf09uAXsOjmWymwZov65UdEcYzg=,tag:y2/WAnUVaRivyJ56vJWIFw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU3JmTFBuUDI3K1NVMmhQ
            VWNSSC82YlhsL0ZqbFFHeVIvWGJCbXRaVW5BCnpVZ0tOVGN4SXUyUCt6MmdmTTVY
            WnRNRE55WnQwKzlidDl0ZEx4OTBjOW8KLS0tIFNWWGl0R2Q1ZGliMU8zV0dNTk55
            RnI5OXpRM2RXejUzQ2poQmJMUTJ2ancKQc2YbqQtN9CUKHGkVlRHcRXObzruDW70
            0jnt74Eh2Jl+kyxfv56sJLA8HX2USXxjVOI1uIJZ7Nx6eflxZDawfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T16:19:16Z"
    mac: ENC[AES256_GCM,data:+xCV8c8/+r1qlmC8t3ghgnPV3JA2w0MF3gaGmNhZr7be4XXCETk57wdd1VweaSmtDruIY/CEutur1Cx6O5iy4GawbadFYrPm6XWNTea9o+3E3OXNuJpDBplwt4JGFTY/CHu0LGVXGgfWEsgWbfT9FTlDBnJ/Mc4PeB6r+Ol14Iw=,iv:TvYZ7zfLs42HeDd9KUgli5lzXI8QY3GgnhT8Iaw5jLE=,tag:soKkGPitq4EDc5za2AVitQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
