apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hNi0vhHw8P8WWh7IJm92ZhzaGDvy6fwJhHTXMT6EaJkYdMmRK5wy+em3lBmJN6CA//s+o21q6IHHRZe8MQDuJ1EbgLYUNi/4rDdGnQ+PQwVBpzZi9XzL8UAvu6jMqX3qWvDditgo0ZIj3MT9LsS3uxz7+THJpQr5Ec3gHiKtsmv10UxTkRHy4fgvRi+rgFLrMztVl0i+AjgIijTPsNvANboeGauijH6/r4ZMpPcgXiiIX7CoG8kwtKdHPWJrBbejM8YYhx67zPmCEDJzn9YrLAHPxunXmZ7BwP0pJXWNBZUmG3E+NqoVuhmTtRO32yt13PFHH9qwKg3lPQhaTJ/Po47yNi4diMbdEG+zfAbJhe9h6opIZ2k/PBMVZ0MjhFCC,iv:l1VblAgbTysPzu2AFi8sZyfhD0GQzztfO/igmuTyYb4=,tag:/hAwy1R/hAkgJwAQcIT8Dw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ndGSvA1KlwR6hpOf38PsQj85JA/Km2bIzMhjdOqMk4Zr/MMdJrrWf3ZTER83ITU8XgS8Djq3wTax3z/wRAaRBfp+2xRfO54gL6Uca95eMmEtVc5BQMCPTuABZ515GLm2hgkRWVV/DglISF/ZncZn6nyXcrUZptQ7TzF3E4vDdzFMpLn1dMWCgievfnwdx1n/8dIy2HD4+cS3ts/0inCyTxqKr1Rk+bZT2nl3dDgtdDrbOLU+NdIQuJfktWdwACyHdbn5lft4q7kJvYSC1g==,iv:dmqc7VAGcTw55pTV70718qYl5OwjHW+kX03bPrgNq+0=,tag:0HcaiYu6yWGa6yA+XhntYA==,type:str]
    known_hosts: ENC[AES256_GCM,data:8s/GkWvo7g+m/GwR/pa79C7zBeqiK9PU6zyqfAeZqkegRMV6piPWLt91FwEyABdtJ7OHgulHo8l7d/qKfm3CNKeaotY/hFIvXe1fgPCtJuxbXqZdHp2Mew9zFw+toGYAcxOOTiP1I9ZKitRgXGsrfDqKtJhH7uX00n62K2KGUuzAEZlsdBWdB236MoiyjJHGWr93Fme6EQ05KkrSm7gVbwuns4IrGyLUD6io,iv:qEuKnm0CqqOvTAbZ59ixV+i4WFjBGMrnbo0Mkhu5s2k=,tag:4tk7NtV0jJBpN4Nl3bbE9Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZFNLditpc2sxdnFLTkVI
            a0o2ZElFaG5reU10QlpxeVJTeUxKZ1hjN2dRCmlqS01UNnhqUUNpbGpuOEJYZElp
            eHVDdE9BMm9nMWFodkx6VitEM0NLblUKLS0tIDcrQ1JkU2U5M2RiZVU1TlJrQ1hy
            c3V0czcvenZ5ZHRNVFpyYzkyMWFXTVkKTgsYkIe51c/okTP78KmKkohDpI8KTxe9
            ZbceES00xCgXO2hdCXA0y9KS1oPWXK8UZk9+8RT0M+vDbFacJdgvjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T23:01:16Z"
    mac: ENC[AES256_GCM,data:AqkgayJgfGgIUaE8Dxy6dwtx2ytGNqrfxPBQqUJIL46mF1MuSoIfrfTqX47hWDS/8Pj5vM43zECbXn25YP8ZxsBaYjMEOeSJiRxUxXmkqbo1TwHtUZ7rmKDuACIGkomMP9uqSLcocfqQgs5BpMe/23b222kCrtndaHrbflAVBQ8=,iv:nlDYBVHWmPbe8RUio+UVLEZ4XAY8fNXYuZOt1c15ofc=,tag:NUXyZVfPUGcFhPgvmu73xA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
