apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:a4/PMzy8F9k+XM92GDuvqTqsW+SRq7QSUp86M53lCzlz/J3Se0QULwkGDzgEgvmLlGkVa83NKs1xrKYgD4WlTxNVMlV92iFIcIEBbydgXMC3boChszpnq5BzvfEjgV0Avynl1S50fYFIV0HeSPMkZxQJ3AzqihZ81O8UHrRKNcxg/fBkapQYW0da1R5ZZ8Muq+eCKa86tZGimgng4GRNImppGvtPTRkgzFSsvVqxSLO61ENi6YA+dl+EhZu00LsoSB2AnDZLeJUrETva6tuj4hq4AIT5FNwLuP0ZRPfjUg7N/SPln24EyeIobKM3fjnBn9tbFZVDa/e7nPZ3sTRFILnyt8Cbjweymm+wRCgP4Sj1fY0CpnoD/IqNPiwfEkaN,iv:AtHmf/r9UkdSuscrN2EyLYLCckM6pTfQDCk4lrXtdKo=,tag:VhgpuHk4V2OkRJkp+P3row==,type:str]
    identity.pub: ENC[AES256_GCM,data:swUeS/Ppr8SyvzXpqPJ8Io7VNJY3GQNfAgANiA2Kk2Gi1GTB1E7T+8mDUkW5iZLhkEcvmUKLR9MS7HmqCSOh/7E1TS8kRS5T8VvsdejLdn2XnewRhMpR+luEJR/45B4gw2w/TQGwAx+HumBqx/mi5+bxIoabsZ6O2sTGnWH2/jWiMbD3CfcX4Rqc7q9qsr+SZJdsE1KvsKnlW18LpO1m+0x1FQmzqqwezn8vhKSnvzq3Ry24JwTCA32VQ/+8ub3j+CUzNziE+i0SE0WgUA==,iv:xDWpFcp0TjZ3oaqVzXaoCVR+4rOkJv/P1r04a2YFoI4=,tag:O+BjABqJRIZ5jlKQEllhyg==,type:str]
    known_hosts: ENC[AES256_GCM,data:EPiGVrqO7WSuDnF9NTxh8i3eQNZW9WFyFRG29/ZI2K+TGPciSOBPmMHSH47UkHNxyqe3wHO3xx43RCk5ahDjdc8dgeRN1nx/w5s4glqf7gxZYOVsmc2fzhCeIWjTwMkRwCXFO2kxRO1bK3Ik74QMvXPpexC7n3OSrzOw419etkFU9jTI4/Ip1gQU21FtaSPl+pguduzUlcHqKBAGs0eTUmDKJrqJWiSthTBX,iv:dfnC74RaNw/MKjgZ6N85IdHdjoi69ZRaNB0DcfXZnr0=,tag:QU2fdALX+An4aZ8WvB+YGw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQmcxVzQrRElVZzE2c1NF
            M0ZYa3YyQTZBdmR2UkxqT092TTNJU1kra25vCkU4ZW9RZjhhcVBQSU5kSjVmelNP
            ZGt3Qm1lUk96czVpOVlYVHlSalpvRjQKLS0tIFJ4cU5XR2VmR21yZE10eDdsQk9m
            d3l3M0xGb2FXb2lBeXBGemIyaG4zanMKTTOZnTaD/b0MJZu/V9vpirSZGz6P24I7
            tLneSuJ+Iz3MiKKneffhcjLiOWeJOfOS3vRPbiuVI1HD7xov2HqlaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T08:18:30Z"
    mac: ENC[AES256_GCM,data:SfXGJZR7E5jSMGZGIPfEEhYJK2W3OtEWoX6ZP1EgOClYT45OvMsps+MAe8hBu/X5j8es8PuKCDaf+0CUsnrnpTele5lXQTjLxGR4rLsjtVeFT8neCOqjwY5h623ay0mpWBrdS1WdZI+831nbRBgs7MI+04+wdqonyEQmoyWg/C0=,iv:LTSgXYZBgCC4Xczvm9EzOb6CCP+XCIH2ygmEWjCEeZw=,tag:p1c6t/vC6oRGP6bU2UAGmg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
