apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Qnq89TbfDfaKvzF44W83nCPTGrQyVdrADFxyOdnAB/KQqMbvAkPozY9K7yKSn4tLJSmU8966J95HFUaCiAJzfRblwuJDR4r/LTDF3qVLWvambkYinucWItWhmaqIqsa7cJsW6mu/YdhAcEDuMnSMaO65v8FdkPep151IUrlxhX6g0+vIT5raO5CCganQimgXTbfmhjAleRWJUEtSM77wFlXWpUkW7XJvUKLlxklTKgLY8NTfyklP66ihQgL6bMaUH0ULSmuI5ZJeHlWdOAJ4KXcAoGWiR6h3BkXcce18mZR3g+IMr7RO3WzVkWmiNv1ootxeyV5IKPiU2PfMdBWLh8iCDUWO4YgxIMWilDXBzU0XFos/Uua/+Bj0FmHaYj4Q,iv:exMX6fgoXKSdbpl7Ew4G61AZCX/H6ZqH58HvPntNY3U=,tag:ZB+fV5EXnRmxK5FaUs/qEA==,type:str]
    identity.pub: ENC[AES256_GCM,data:UJf7FMS/gtSTV2GoUUyq2A30xU3RLeXiMm/hVZPY5WpRL/JL+7jpvWYYTTgst7NZiQGweyL4QKROS1Gr4V7SZ41pdyl9WYm8QhZRDUvjP/SEo6NEbBVaQIlOfJ5o0fVrE9ETky4WMrtT6u9pLrGgUY10q5ipjqrDSq5Ia0SE60ejLE52BoaXyvMMiM3slfdiTz346zlxoY/MBou8O+BvA91cEhkTqnNOGStvfLcRzuZMiophHzGvM/aF5+Ef+Osz7BNWep3WIA2yf72b4w==,iv:0wNO9/eJMUPE1AI3W2hPt762uEiBuAztaGIzDVZ2lsQ=,tag:u4uXmWthQAHPuQxZbuxhTw==,type:str]
    known_hosts: ENC[AES256_GCM,data:QxGxDT9CS87GL7S/5zj+4pRniY7tfaA7G7cWtBrx34QWK0qikmMbsl0Hnotwt4ecqXl/SGiiOr8mjU9o37swcqXFAH09y+DA59+FNdoBN+YccHftHj98uq0bhZiIpJoWNNFdivUt2tSE6lGfibmvjvjhsTg07HTS7URY0E+411MXRAmwsy2LxW1jLDXHeJYq0JGLCUuDsZJFEIfcOwTfKLDUlF0kGx3DUAWc,iv:Tx4hOTN8qtgRqkViw0Im62AlMfsjo12DLfr8Fit1Ec8=,tag:Fn2jGOqS+4KWkiDraqil4g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTTZ0bTNHUm9oeFlkUDFh
            TER2TXdkVmR0ZzF4NjFRWEtPeU1RblZ2bXhNCmZzWkowamtQZ21VaHZiYmMyckp5
            OVAxYStKclZkOTA2bkNMYjJsNjNoYUEKLS0tIGx5VFcrdnFSK3VBMzVyMXRjejh3
            L1NidE1IZDFEWEQvUFlLaTFyajhRdTAKFMHGT9QHGqJyW+qnpySAFn5pflilgrnp
            ftp+kcOp1FVLAUnY0bnxlChN8Iinuc2QW5UrL+7lj/bW7zX+ZlyY8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T22:32:24Z"
    mac: ENC[AES256_GCM,data:OW8tMt0mkctYfAsyhsQJdiNiNAF6M7HmcAqtX2/MHt110yZO8En2BzjhtEqIE5dxQgpXuU8vQ+SrhFMtINya/5JP1QfJ8GW6Ba1PRLcSteysMboxShlXiPnbZptOP5u3cqIABnxH96dwgH0lGFjMlhAC3uoq7MYcDMrjrpaFcwM=,iv:6UG3+qwITbIwR0+kpOu9DuclOoA+a/lNwqxPwE63SuI=,tag:1W67Bg/i2J16y7pe9hOGBQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
