apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SeN5ZlZLURukZCj7aWn/8u5rAiXNsVbvsXGSF6k8pJ3BL75eUZF+gIRPHMkT8hxcR9AH5yS7cP/fn7y184SxNnVoFyGPeEVx2aqxYd1IALs25L+5JcHbfz7IhAvNd9KcndXoTV89FOc7qSSHl3sUdOXQcKtDXZ2ZbWtnlI9vh336jAUYw/aL8LpN7IIGC9SahU8ZmiX6vGK57ySss5jDdONZhDrmr6pTO1Ay4Y0jz8xeR5siy5sSxZlQOEo94dMU4DG7CrrvIRrZZ36/AhlXmdQ0kQhfagOPBlxbfSG/euwgdRvUPWzOTkTNcqOGPl6UcGs7kHG0V0ty/KtUgOtO8yfh9KIESnBaAbC6scusqG+jJJlhJ3Ken8r12Zc2FS/T,iv:xIBWFtw1FYhufY4zqUUmQojhcUBvpXnTaZzUvWP9uto=,tag:+fMUJhVneeqoN1paIMpthA==,type:str]
    identity.pub: ENC[AES256_GCM,data:581vcujqUqrz8XlH50ipILsu9a+486L8usCr2NAXPivpGHJGekB7dW28eZCOsVU7w22eAW+c7GGB68mcQbNQWrlKD4Ifn6oPCERZ/inK3zhECA7bmJstClzzGCxf0CsGSm6VsFZhSawdhKRVXSebf6rIgcQSwmblmbA9+/nr2a2egh2Kmwgar5tJgvO2yZMPwXjpr/yox5ESx7bgpBlClWzNtQkVFZH2VTEjo13v95UTxT0Z/ulSAQFRgBNW9BtV1BotMnG68URAHGtpBQ==,iv:oWGi7b38LZd0d/9YGW/si2St/Tk9Ybot7+J3ebaQj9Y=,tag:dXmk4ElOKIHqxHyDHye7Mg==,type:str]
    known_hosts: ENC[AES256_GCM,data:M7efqIhi98sILJwyU4jqX+pnwyz+lXxRKjS+5tnsmqMY7VJtSDoxB7jAqgDIv8zO/ZYqqFAbPvKZFueo05JWEkJQHz/D1VUdZl5BRsmxBrfRM+hdw1/3SsDfe91/kfe45GpEq3qZdvjeusbRbflYVAB7aJdh510+QnjjGxyEMCAcMGrf84XILYjdssnjxamVFrB2GLjzAk9BlOO6EBzVy188x+FPF27qatPi,iv:9hMduQ4cTJ0/4X/RhpB7excUwlJPbBiUw6zipVgyxng=,tag:ab0Umng11BmYeNPpuO9GFw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeTZWcHg0dVVFRkFWaUQw
            ZU5UUW5yL1FmTWs2aWJUMWVZb3p0UmZYS3pRCi9GSlN4Z2FMSmhnS1pnbjZKL04z
            eGN5dU5CZVQxNTVJWERNcXFxaEFrbHMKLS0tIDhrZ0dNaWJ1amxaVFpqbG41ME5R
            S2x5eFd2SE5pOHExeThNWTBLMTJxUVkK/K6iMAK3ZXlqss06wk6/ogj+MXCTQsD2
            PQdeSVUdNV8RPdz3+e4d4aM94RI8u3lp8SGfKDZerkXf9TLQn3Bv8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T20:49:49Z"
    mac: ENC[AES256_GCM,data:/mIJ+68S4dVk/bbVy/EQM9xgeRr9AeBCKDkkjiUiVHMlgBNgOFDhWwXy8nX1Y/kjtLXq+atc8AP4T1D3Lo/DewXmxql2aUKP88pv5ycoPQUev5cJD154Xmmq3uFwFGeDDYqtT0xq+GpTCXBzsM1PQBQ60i3xl0obB9ntZdadp8U=,iv:VbDCFjeUu2N834XRFxHlUSBlEPDM3la3YwGGLD/s290=,tag:aO4yvkmSY4+8QzF25AdXMA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
