apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9WykELoxyRzU3dFUVyg88ZGw3+oNnXBmipFnioX5r2+s6dN2NoAym7vvM26T2EMWnjIJKUgLIvwSA33e/ZTgaqSKsiIULAH7d5hHt+I0fcUeEaak+jOXKZNZqQWyfFosIXy8nDts4zGbCaJxPXL9Gxl+KlxxTYdl4JtWNJfznAkHMEDziSzodcJ84Ej5aa5tNBO+DnT4tffjfHzm+TEEGRsOIaPgZ2dH/O/EAL/4pfJ8R0xDRB6M/hBcFnnJMUQixzkitVXIne2VHweeaLik7WzgVtvR7sPc5roxLRGzyZa5YEJ+O0RY+PjXzyo3ODGmHYQPhZ9wEwlPOfPuakMazP04TmHF/YTPLEgkDvIClc4M7U8AhgWjR7QnTj8qyJgX,iv:6dcYPT65Xajz4x+Gj1QmilHi20MybHgf7nTJLM2xAVA=,tag:22ahtUw0S5UGsNKyKWMVUg==,type:str]
    identity.pub: ENC[AES256_GCM,data:hSN8W+lXsjB98H9VG2f1+XDpGGUmyiZ7Doo+dQ4V+jVm7ukduv8J/aTqNVBcRZJoC2obQdJ0opg5nVh/27Oi35g/f6XpIXwVyj+brN8u9JyKCUXo17Ip5s8DoXw9Coi0d6Q/9esAwmS8IOj9gKRuraqzcwTzA/xMUio5wN5nsp5HeE/RmS+mF4PPn2Z3FujT6KkTThGmKSYplkE1bdlAIUh7oDKh5RBShAMyBXSuif0QKGrS1JVB9h+IV1Ye7r2uNkREvg+GX4jtnIRDVA==,iv:CzE4npPk9J/6cdM31Egkh6K8lK/tHSH+B548dyS+m4M=,tag:WvMFYWW1pL/P4LYDxfCcOA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Bp67lMv2v5pETVUuck8Dj9Nh6+nTO7ObpM60ux2Zvgy3WRG4NvckkmgGGXBEnWj5EveJ97lE6Z66Gt6S12uk/QyyNeM0dRqy4u1OppLgLpv6D9fi+0r1NWG1yX2bX3KgiN0pC3bjfhQyaRmLvx9IvLtkx3ZyCDvTDaTtJR79eCwGfs2fC7x6tvi2A6kST6wWoj9OXNcvzl3mNk0ph6bsIdu3+224tdbxEXXW,iv:sytfBPdRvdutiHOUr3HyGDemU1KcgdoX4px4oEf+jKc=,tag:FZyizwATuxsF+hyObyGvHg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRklnYkF1OHRHWHVianU5
            ZVdTTkF1N1ZXRHFyVGIxQ2YvSCtjSlZLQXhVCk50ZFVxZlhnT1ZwdUlySXJxYXA5
            a2t2d0p0dSs4S09JTHJENTgzUVRickEKLS0tIDhmNmhKT1BOb2FQL25RVFVYWGM0
            TksyMVNzQjl2U2Z5bGZPWEl3RUVKYkUKNJozgUoB26376inuWuIm3xB2ad8Q5Bpu
            5Si6m8PaqualhAtUGwwNnKbtb8coOhteo/Ef5f+cRUot+ylnkhDewQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T22:22:22Z"
    mac: ENC[AES256_GCM,data:VO7Y+L46mbS8W9tZTxQRtYcKjbq/Kp8Hq8WGsN4xAsVaz0MXTy0rxo3YX85dwkLrMYEVM65vIrkYC9IfkqJAkCvco2yneVRqNByceOHJHLgiRmXlbskU+WrtSmLUHJ0OfNe4lP4PNVw13l76+jQeHEGUs0dNq7Pwns6DQTnyoUs=,iv:NUbgyFfNbBVfoVb5f33be2DVpfyswQ56egfakHvTPxI=,tag:0Bfa1D1GhAVotFfCaFd87g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
