apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OR9zKVIKiCVFN0ns3gkBTkGY1zrzAJ1tR2/LO0I2L4ADzF+CNnhkYrXa26louaNJHnWEw5LkDUU2TW0B6Mvk5qwXtVO6ZbZbp4EW82rAYcpmS0KcJIqwjSgduNs/k9x25pSGDV+EKGE02DlNiO6N9J/IQErt5ithNr9ZXIl/bpTg1QORij36qmpZg48WB0TolVuEeglJzeSDxzdGs6TWOsxodUNPSvDdMcius2lw5kqSKHox+bIFnoUmFAO1QfY2fNI9auVuMGkqGKlSRIYR51kiQtNxnbQeM27BKWL3iY8QcU6FlQnSsjVCHOOckH/ciA7CT0e2QLyStjDlMXz7a9DVjlt/CrwE5e6hN9VorGlSuvIpeB3VuJQlWf3b8kXQ,iv:fV2BsxXSeX8xwAnAh+piMnaz3soKTkoPJTKclh5y2AI=,tag:PmlecKWIjdR3gcsNj4NVyA==,type:str]
    identity.pub: ENC[AES256_GCM,data:EkxWpuM2GBMj32PiMlrz3LlB3IzSShlnVSTa4F2s1Bjhg/UUACz1B1F1HwG9IIYWxmkPV6YZN/C2P/Wi2dH4Ls9SGGWyIHKxTLmvssZNVqeoWxMAyVBKnOjIwWdb135UUusLHHUpCYdp0nl0FZFqiIlLSuzbkK9iiNk/AoWstJqPGXaBS7nLkeER5sq5DMcsq9zQYtEnDb+UZWX1cprikF0KTindFgxscQiIQuUpseZ4GGexYP9DeH+fvc8CpCmSycYBp3vSamlnfC8zSg==,iv:bXkjrTP6L+XgQhWHCGpOXFvT82dPxVy+9NYXoXksbFY=,tag:73HtbwMyIpygxbW+u4dq0A==,type:str]
    known_hosts: ENC[AES256_GCM,data:Z8Jnn9MWY7ooYrN+if4dIrnYh/zzhtojcrjak0kjDZSmyOSuD/bBF0rK8wMo9pcePS1fFX8ApvN08R4Y5u3rYpVGj0XJZebG/46iPW1gV7QQ976Lo3wOLeqkkxjkVH2qu6dDPkV5IeOQrRitMy9LSQU+4IfCtbnIQzHmMmRZ9uCjPzVyLAqVUHGr2UbCRBzwZpLA2UITUlk6HukMOD51dWEivI+4fD5GTp/n,iv:ekrKlZeaHSZQKjIYl0ZJhBbGKYfp1GCqfNFkIdRXy0U=,tag:oEZ29ehnnCUePV/9wFisPA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UDcxbmlESG9uVGtzRDZN
            alp5ckZ6NnArMGlpKy9CekMzQld1ZHoxTERZCmRidE9LTWhmV1dMS0hjdXdFQTdT
            MXBRaU1HQUllY3NQTjVITW1CNmhUZ0UKLS0tIC93SEo1SWs5M1p0dDF1SC9GUStM
            M3B1a0lEZHZhRjZLb2dIdHZMSTBucHcKNfiRqR3ivibic5q+y57oqE3Y/TPSxvdk
            xIhC3qCwwK8eR4/nD54sx6gxb6LZMYu1iFAcPNSYdEawbzULPHCySw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-21T11:29:49Z"
    mac: ENC[AES256_GCM,data:MklC2oDrwhP8Kf1Q+BQSzkwHIpB4OaXFekboPWl6yUSMGTrEeM1z9LNMhhXXceje+jX0q4tdJ5hefrcBEsHRocCxPSfCAh4lQCDW6mlpzLlnzwbf0KlbWYFeX3bu+ab1hRS5SNS5V1ohowgI1MuEiseKQ49QbZrlB54YtCFpDso=,iv:favn3dgcXPApHv5aQj9cfnKnQXrFNyuaHygVpMv574Q=,tag:eVaiSFlhUOKXVwklUkBhqw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
