apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vzr5qQfcK7cybHGqQizhe6Qy1PHHAoGBM027Ef8H+c+woauXCR5MI8V/FcegRIBRNy1sqQXm4XvyKBQAAR1RTSdcPT2xZ8WTCdPw1ePWnaLlnV5lGvmYPKD3voDA/lpky9PY1I0K8nZImb7IracTn+bY7sotxTntg/k8S0R/BUpcaoAwR983grZNGQeGBkJMV2n3CNIylE88e9AjH9p1z12ulUpRo8cC9Zq/LYnbYug/Iudnqxk/oWprTe5jzsTkk9zeGYuZBujgiPPBwV3yi7pyGrbWwwRN6t/iXlcDqaT8wmrGjDycTUwjRTRJIGOdxAJo3oU6/Vdx+8p7boqRim/vxzwQ0qDszEutdmafyhqtm1q9HKD8TuG8NNlBOO1x,iv:z4E8+m15HH1VyJM8bZWzQRZk7huk5PCkmBny0IW8iDw=,tag:pgAy5F0iTeTK3fVCVrBWcA==,type:str]
    identity.pub: ENC[AES256_GCM,data:YBCp2G4/797y7NQBPpD/KntlbVLTxR6aARCjSb24KZ+r/JxkqDrCJEAdzEzMDXx8/RYWg/ucrOEOtDigrhdNHaq5gCjTrjS4WdtkOqwXJ15HwPlQbH0d5A1HgtwwJlw+19YpylxGuR/Ih2bEM2dmUXzB6EKnOi8uQVl+D/TPB0sSVIFQUJD0rcPFie9ynpHiSf4mDrUtApXbKIEUggToCflcA0ZuOxNHcRk4COkf8wJuoNnhxYQIKMbTpXc5EPrsEDt7HSA8bpCD+PGGEQ==,iv:6cjY/qWNxiH1bQHfVL3ATcPArG0jMx9SwwzTLx/sh3w=,tag:EIcxBX9G4J0FMOOXUELKXw==,type:str]
    known_hosts: ENC[AES256_GCM,data:tTvqFsTBMLiGxUvqjAfOip1N3p5jQhM/ztyOPaexmoA4FKePXg0N3NnUqX+/DjJe9WpunQddNEtsHbVga3YzwlE5vW9EEeN3Wzm11kNqlgyw4LALX38YIMMqL0VN0nhy+qZLRjFj6e9zCkOBbIX9FfOUF1M4rfDxtG+U1CybX585AS8BedyadNIgtXmu2HAhmXR3IJW6YsJTj0XOaGcvFRjL7nCHcfuJKaYR,iv:HDPs3i+6A9+p7VW/oyc61JJJluyMc2ERRFWGygS9lI0=,tag:vC3u1SJZG7oCd3fKHlSBmA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S0haNlBpWTI3R0ZzUGFC
            SUEvRlFiRmtmRnk2dEwxaWJrWHVrSWRLUlFvCi9Oell0NGdpQkFlQTZVa0JpbklF
            VzdjNGNGUjlCemw5Zk1xa3hyMjBQSmMKLS0tIHB2MUQ3eFo1ZElkK1ZCRlkvd3hn
            bW1TZHBxaEFYcWk3QmJGT0hZM1prTDgKsn3EV357A1j6Dftqsbapkcaz60UxR5Wr
            egNlYbSoO6yywATHMouUGb9fed1lYrYmCzrx8BAm59qx82QzxgdK4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T15:48:16Z"
    mac: ENC[AES256_GCM,data:d4UoZSaCqV37+40cScrLdvzdrZ3H+ivTXzRAS2sD9G7lfId8WDO7An1ui+IW7Cke+3mN2ReID78UieebEAfFu2fgnY7bf/BG07ydF4ufBVrmlmceiAYY1qNpgSBVx8yF1v8n6m/kDpA0vGv0tRP2WkOViNZY13HGP+2gbewmfWI=,iv:HZAoAY5KDMpU1oEzOq82HOMkeM3ZG/aO5DiWZCKfTF0=,tag:R1A2eWphRYnAR5t6Vg5huQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
