apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mRDofUKzoHdAeNJSjzwV31KVL0T57cD1EBg9BiAr+d4PLE4d1WCrpzHU+/FCJQ2BhcV+IDRkE9SLSa9FRWJrAl+NyefRPHPhBoAp2NPJR1TLU1GWK/MF9qEpFjlZrlA7Kxm9vrPY9zyn8+oXMSM0H+FCv9wFnRh2WQXRh9l/Ke4E1jVkvgy80FdsfkQkipl7RAfKG0lXg5ZEcsGGlNNOVHvYrL6gDzusIoqzEIy2k/pz/EuSKSJ3HcBbHnLBZ9k1hDP9Tx27J1veLIcaAer+kZIRB8NA/vebM4WFtCkJ/JFGKd1U/66p98x4H40g/zYOGFWb+xy5LZ7CxJE8VmnmuuG06oi/986LuVk8FvOB4/3rjNstBahYF3IZaAOimMFK,iv:fF+FmDBfB0gmprWfjP5zmngq12bSvT4YrWugdVMXBy0=,tag:0WjcIifdBZoPKgZNffsRdg==,type:str]
    identity.pub: ENC[AES256_GCM,data:8VxfkKAVYc8YA2uGg/e0QqDMkYST0athToZRHzg/YzYHE/aPDjEBf8xDEBB75cYXJeGt7tRM+Sq5JPEd47Fg1AVUxW1geeKTnusJ2aP3TurJOx+OJRr2J9fSu3kel7ho0iwTFwPG3bI2EaeuZfBMKYqt25fL+WUd/1q945FkFLnk/bSH7wYcyb/QG/TJx1c1C9HyBZZA64Z91fsFYSJjg5PfaLf5NHiRg9YksLVqqeWpCt6fxV1y7hvbucLxqQjIYxLkYxzQwDbSLXfPgw==,iv:dMPiKDX41xsWUjmiqSyqu51wbo8jMPu9bK5UxiEP0fI=,tag:yLFR44wzyC5f2XwCz0jBYw==,type:str]
    known_hosts: ENC[AES256_GCM,data:knrqXvS9EyoarYbqe95F2CxjHzO2sgfYqlEPBvF1DnePHA/szPZWeMBEkF8ABP3mcN7GwpRvN7Lqzz6VvbhHP2vAyw5S3b9uwoyDDRClf1aqAyGZzzRUhcq4ZsWowkIElATxdM1J9E6QT2Uggbd4v2CAnHszO0S8O5LNLXrXpxcxa3vHB3EdF726ehAtrOM/ApclicHxldTryYKC1/ZSY4VdimqBlpUF3Q66,iv:lDqSBMDwkzkbKzn0Vp9fzB93DCW/qlca68cxRc3K6MY=,tag:+SxKJAWqlpQkaJszfL/u4w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKenIrdXd0QmFMWk9Kd2RO
            U2ZYaTFhQTJYWHg3T2cwVE9yV1V3NmZWMFdJCk9aU24wUkNJQldnUXRINHpUT2VX
            a2NGUXNuYjRZZXBQeC9JSGlNZU1xM0kKLS0tIFFrMGJ6Yll1MUN0R1Q3MzA3TUR1
            NDZTNitaNkhNWlR1MWV0QjRGek1neW8KJG3HPrLSpX5pAkntfuLRYIU1lleJ0BPU
            leDf6ukWea2GxHSIIq7TwwqxiFU8dPvxgdg+a8fvPYhxVhQVnmai6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-09T10:39:48Z"
    mac: ENC[AES256_GCM,data:+kWJNcSAcwUfuh5f3Aayea5Ys80+AazzrmVLSZ4A04UHOPyKzcRXMGfOsgtQhHjqWTDBRbamEPIfpLcoiq4PNWfBPtmUy/dMZ/Ur6HrnBJRuluusmBidf09akdHE7Xaa7HP2/SLvoV/elh80KdAg5yfduAxM9HBO9Koo5TGsXkI=,iv:kD1t+WNh5PncRrhN5tCw0W1cwuxABGBC1RPnrgynO6Y=,tag:v1Xkg86kgH9L7IrIrar0Mw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
