apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LQr5+JAotBc9PfveGx2cHnrA6HYMYhqTrsQ/f40x12enJPpbmAL+zH/H5XThDFYuBXj4lpIIblmUuF2er/POh3M5dYbgcPTMwh0SDlU+13vp+lEGSkU0XFolN9d8E6tmIRod3ZKJm7fQXGkUDS5qU+beK1NLeD+4i8DRLRvUfNgqVfJzCUbZR4TFQ9srTVMlRajpGW2XVSnTuueXXbMXYduor73uadxmzNUbbQQpjoSWhaU7S2gupOCeBq/3J05VLITdl9ILnWGo/m6AuQfoWzjv/VT2betzDw1oyj8oYcL6ezGORkMpd/gHg80rq6Pk32aZZXVbA3iBtvX6xD4Aqdui2bDn2CjuYSetthrINpR9YqfMnBsfOhe/vUuyQjIz,iv:4+3K0hCoLDnCyVyBDudOIC/gqqTz28WnPZ6hkMhp49k=,tag:I8ob9u4ueGXmYdyIi02F1g==,type:str]
    identity.pub: ENC[AES256_GCM,data:QjvXFC6HiZqskoP8Cm2zTIhnGWtnCy6QnxgswmfbU4Jj38l1ENpNr1GYdbkfzUjR+/TAN8yvUntuyw31yCCTPxf0kgnFCN0rvrxSIZKgFS15qAzs6lmW7x5bwKvvPkhILI1ugDRhkQb/bMAgG/p/ruasXkFLNx1esJqH2ghfsxhTi6Qrl7XzW3dzjoOmLo2TijySEfp9dwSlvXTExZgb0NwsmFGmqyrGMdwtSrscna/k2zlsBlHAQDXpV199yT+O/1kCsJgtngZsLxsqyQ==,iv:g7MePyfDE1wycP4waMTct76cCLd3MQ/9p52WdavbrZs=,tag:8eOSzvLaBWBYcuklXpse0g==,type:str]
    known_hosts: ENC[AES256_GCM,data:4O+6btPDgaRxMqkPHsf7pOK9MOROnaOxH0HBPMWc4EDbhacNN7cOVfC28QpXON3MMtSlO2eCGS8f4OCUycJT1Yw3OO+GM0tX79STKCKdqYwARHP+rD043k38YRegRTK0NHu+sIZUzWEtDljuaVX6AEozjNet65TB2lLH/BswwCBvKhPDTlXms31GpnK9Oc5kmzfpeAW8SNyi1VSvprb0jSMgTlodK7lK6PP6,iv:vCUHpvZ84+GMsGPyridSOyo6hd5+fkSOz6h+e85FxEo=,tag:qXHp4aMQkGbm5TnMOwXGgw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneW4vTWpPbTZlQXlieWxa
            dW8zb24vcmNuWnZMVUI1MEo5WmNmSkFBSFI0CkZiRW10cmFNcWpyQUY4bWx2am1Q
            djJLOFRqWWlmL3lNdktaMmgwZDFKc00KLS0tIHBMVmlXRHlCVU1yVU1Xano3azRW
            djh0Sk13VTlXVE12dVMyZGNKbWZZcXMKma9cx515LLVbYD+t49gSiRAVkyYmEJBX
            IebrY4clU5T0dIzKwwT3r8iGqnAxWSC4+Ts8crrZUbGr1zA6hTNTUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T19:15:11Z"
    mac: ENC[AES256_GCM,data:fFwhmEySRBxb4/Wd5uhcSGJtxQm4AJG9Qa4FovEKfAOQyIwvsTKiprDDkULKSuXBb6iQ5L/yyTs6Orq7KEUK07813KAm6jpRqa1YMr9ddSbItu+m2Qa29DGfU3ltNSgh0GcYOTxHZ0XRtY7ySUn23UQrdyzxWzsWi/870rxi2BU=,iv:1xGaZxXChpju7UgWCqFIXYFKAbf8MYqmsejTfOY22N8=,tag:W7nN8m9X4mogjoyorAa2Kg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
