apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0zF1FYKKpx4Vyg7JpUBooz92qhH1yXmLCWmMOlVKkaDySrPzk7iD2OnjsF+hBk+3Fhlsm24zsWGqmvOHcT4aPFnhpoSvpDjCNyjlCT14HWgYK2Df3DZ4n0sfqzLazDxemeIV2/UU2lEZQQeb+o1OJPtUZ1BDMQU9cRJEQivOCESt/T1OyxChLvyXc+56XaDyT1SCvsNvcelanVc3RZ2i5oFxeGtPA7EOTArCsWSIkuM92KSoFyzyQ+/OmIScb2FJ+Pl7Iuyx4M+1shL00IKhiDXHybGXLRRmiuK6e37mJT2gR2SvadXm8Yn1RgkNwHiTOMzDETA+MFTujdeFQHUWaUmCvILMlFbI76/MgRnVc9Y32lHXulxVxnET90trEzAq,iv:1kISlAryGVpDbXwT2x7aCkhcJ3u5ex3GiCFBbc5kOfg=,tag:bFGaQO1vVQJ7w6r8bHqbkQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:0Dtk3z97ShwNr2nQwtwfAjwOoD3Byf78N238qe+yla2oXCRAc8MT8Jpn+Y4BoXYlJGKY+7ZVg3NX+EZYsfsyuewU3ahDoWXwCQ/Ug2acZddJLze1g79fBmDTlsb+4LGBW0/uiPVdH/xpY5uxg+DE8Lr/e7GeC7CPEra3q2PbDf7utXPprmdC1T4rd2txder1VR2cNMBM6Fl6L4VeXIgax7rQPTkNkK5XnOFY1Fr0CQXqkuDxREBjCMR1j7l9PEh7NrY1rlIDYIuui5jMXQ==,iv:GfJUEHAlCCMmd7YYnyJWp09fOhZNNhSeZp0SuOIdzqU=,tag:MizHpIbb4hFO4AQdjJlQMg==,type:str]
    known_hosts: ENC[AES256_GCM,data:2tuy7j/zBMRvlc6dxlMDWDaH2KZlaeonvNPpHSr2YR6fZbq0gMEAT4vODxZLXJOZiZigYFDWPTu0IERN081EarHVSxXBEuQbr5/8EqpZTJ+tWVyIhUkpV6jwat8Q3Qg7kRiXXk7+pwksE2A9YhJI4n2HwmGUgL+W+ZpMQWEH4B3uqoHIj5Rl/EztNlR/aXsbsdT/+NADXn8wfEmizo1LaHNpgXC5eYlitOM2,iv:K3kYPbbYFccbYTCGD+Mka+2xZNo/dDQ6rmhjrYfUMlE=,tag:LW2Ea0qpGJnzdyKgXl6BqQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoV3hGSnVVVjlxY1pOaTd1
            aHQvWHZ6T3lOZXVlbWdLOExUK1d0ck9YZUV3CjZMR0QrNnBlMjh3clJ1OCtDdUM4
            RG16UW02ZTdHSEJlbXVjb3ZiaWVHbEEKLS0tIHdjeHlFZE1FYklRVndSSnNXRkl0
            dGRodjFINGlkQy9kZzRqcDJxdHUxaXcKVAN53Hwl/12btomMz6w8/jKauQH+4mKH
            4LlG0TTkLexvBO+UKfFBbg/ZVWY+Damf25iT8PKJgZZZR8ej38A9kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T21:06:29Z"
    mac: ENC[AES256_GCM,data:DrqFayvGrA7Rxu/PBA+H46cvsPZajpmTReJDBrSbPI3X5Pq+lTN0qECyzitWRUi22odx2WOCD0oD1EbhNr1G96ssLn9PzYIRE+x3QTfGW2efW+LkJRrvlNBt/4tBYNoJ4AQjPPHCcYboWfckbEGaExaNJIsp+NdRtnBEuTCS+3Q=,iv:cxb3piMNxUL9KaG9+LKtDhk8ZnD5Y2HSFAEdIDuP5lI=,tag:XUpkNXAr/7rz4/vls/jcBg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
