apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HiUBXYRo+0Z72f3+JwFxNuQVfIS0/B6D7mpyCOg9oSP8V2OZTdjxIHfQYxRB6fPqCSJkSPRxcOBFs3/iyqG8qHEOizlbnSWsyT5+by/p2kVYg2c5PL0Eyxv8fRqNRxSYL2RImeEzMqzfr6l9k6fVPtabDFqYc8xNaF0QKP+4y7CbCUZ2A09ybQOgZI01z8XDAaKoUmfSNfyVDzaHan0FmaBDlfu1+HRafO8A18+GWdUJxeQhBAmZzV7m62ZTPk/o9nXyWpF9N4gSw1x62mIs+g6ZZXfSCavTvDfC5CXspbS8aO+nnS8m9L0ZZHUi5L/ZcQgAacSb1AnnAvvF8z8BNYYEU2BX8sceE1O6mmwEynj6PUYg0vZ1p4xoDixobM1t,iv:Zv8AGzDJ6trrZ0/ctwo3QK7r995dtcPVlKYITixSgRM=,tag:1bRdxv2MChbN9YxlWvcr0g==,type:str]
    identity.pub: ENC[AES256_GCM,data:jBZyNljkNiaOsXdLUV4T8SI2sMjXsVJ/WOj7uqr32xN7iYe8VQoEn0qPWgsf/7kd6p1sj81j1ta8LIkPty/pvT82Duh+vQKeGhRHWh4YCINDILSovKRIdXzMwU4ZGRN+PBWryBbFwHDFBx8kIeXcsLQ1SfX+vC/OH9QaEvdP3oDrhcOR7OKhih4R24hUHkXKGJwSHysuWERzg+wDcLR+/W4j15H0CNQpn8MCTvJ160Nmef0qEBOJymU/MmcsDjzokNfAja3GJ3Q8jAhD1A==,iv:DkrlO1fG9FMtZcycmtEaBYgV/4m8hpPU+MGGq/JtUlQ=,tag:DkfDoRX76S3sYDNNyphykA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Irh51W3aJOp8CtfJlTGZuzGsIc51fL7CLTpzvcGnsMu41thlP1dGL8H2stj5POVrnsrW4txDQ02B9Im2oIBliZr2zfO6PaS0aF2l7NXzYqZbaTbKn0N6dnhnJAm8ji3HUCaJdy/vEfIaM6A4jYxNUXNq/g972UjkPRu+EOUhLHJIKLcfMTFkOAbULqUb6GkIYjiX3AvgIxxr0KodrfmVo8Ebr/31t/bPf4J/,iv:kTVQPg1KFHoGD3Obh58vgmHvYBFxx9S1EGxnJEP8LoU=,tag:BXvTR3VzWz+SF3ZXdi8Rlw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdHdLd1NXYTBRdE9ncERr
            azNaamVGYzlwbHhoZU43Q0FST1p5OS8yaUNzCkpBM005SC8wNmg1Q202Uk1rbTRk
            VFVHNUJ3cThZUHlFdVFwUGtxZCtjcm8KLS0tIE5MUmxPenBFbnFXTW5zU1VVK3l0
            OExqWWt5NkRmanNndzJOYWl5QTJ6cXMKaL5JSrf9xvyq6eLuVugtD5K6nfbDZLbd
            hQeolHXNL/OT1KlXDOK6bXwMXlO0bTX9UaUZprG0IOCWeV5QZ7tPeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-29T08:09:34Z"
    mac: ENC[AES256_GCM,data:1a4wfpBQkbYVmUXWpwYGexD8Dq/zgrUEdksngoy94G08mhLi0WI2ZaajWAO55v9YXmsSdsuvIpXiZ78xwVHaIHXP8zowY0U43cyclByZipebBFElmpDaeQvnFwAIrsLIoEzX2L4l1FG6VL/LQyRAjeMUFBSfJ4VLRAeAQD2klno=,iv:/2d54/Qpj4sB+xNzeAczb0BaMcvysoF2TUD1LP64l58=,tag:Qgp9w4f5qAu+8F+tiwj1kw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
