apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:N3yYWAEOjlh5ehvTPDF/A94ATkfZZW/ECcHwmfYRe/XUxxv/HfZ914kSPVpMp1rCg9y+BUXkco5THTv7Oe2aSLKv406OuVv3HUaxB7r8bOr6WMiv1U/9QN3GD8q6y6/j3Jxryicrl5hOpVLHekNuC5A+6tmUkv86hw4F485gUo2iTx7GtKpM7rIbKShStU1tVecFUmWJWHK4bgiH0NQ5Fwwn1/voB4er7SR5uJRsr/zmnMTQJvzV+/bEcDG9FDjEWNDTuxN0IjLaDbSlmte4cUF3ADYW79iDqiMIM1onrLx8g/mw6nVBqEqYNGvdgZZc9ZAP/5u0ZHp4B1fxRBD437tJiqLGc1j7AReO76tU6ERyJPIfoEK5r2cEc4U3n2+t,iv:hdONQqA+/Z1L/jxyo+g3hICRaoVTZezXjb8CcCmKrpY=,tag:5rXWXP2TKXYO2rCRCXLGuw==,type:str]
    identity.pub: ENC[AES256_GCM,data:wPpt3ukpJJhmk9rJ0FdvHI768zMuKvNsGI644p8/l+KAexYyPU9DL/mvcHgXdSKJHNGjBekz8gaLnUQ8bbOAs5qmZPL2OxCJoaZ0dJJlL4YZVzKeC/LkEtqdMb9FfNDR1XsrfrpA1ggyzneI3hF9PBG3/+Rv4OMEUcbuyIeOFao/TQJ3XvNu4oT1a66dQtKiZDCINxCcgtuxvIz40v8uCR30Kdc4ecU86KmrJRttwr2ryy0BzGBo0876cag31p7yqqlD8dqP0SvLgWznzg==,iv:lVlgHszkjK4EYviBspmwyVr3FvE2BRSn19GTUnyCP+M=,tag:PXRCQ+77EMHwJB9VZYWVrA==,type:str]
    known_hosts: ENC[AES256_GCM,data:jVvDzM46Qr4Ck9SMUlpkg2BJ10QdAqF3n1AjlIiAexhlT6fPTvnQozX9T34UWWQyDgZvBeMs3ItVSSw5HpDk8RDNkryDsuw81toyAlstVMV1AJp8NkaIZFkFJuEEzCaxJk/dbjhXkHKM41eI5GTTkykIhb7c8PmfGAeKTzZludPNunNiwwgDlT3htpz1yuqTskGkP9+SgBsOO6PpOgN8isLaqCUMrzUJXWJF,iv:gMUlqT1pW1/WFxOya8F1seUZASQ70SG4TKDiZ7eiOwo=,tag:Ib1ZbqIa4Y8FwoX50F3tnQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5reegnllyypk4t5522yvknfddhnjvl6tvqmjfzmpc7u9wdfrgwsxqutxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNkNmTEpWV1ZYUE56dUlL
            RG4vdFR1eDAvTGhWVVBRSFNZSi9PaXNORURvCmJ4Rmc5THZ5cTF4N1lBdmhqdTB3
            R0JMOGVXbHd6cEdBQ1ptOEI3bEtZUU0KLS0tIHFDRGFHdjB5cURIZFNQMGJSQ3ZK
            R1EwWW80UW1JM3hKSGdJNDVyS1pqVjAKoLYrqV+xRPkAo+nPa5uJxezAJDG01FN+
            1Dt3ypI3WoSgHLhZjNTU2bkSNxM+cHgJMpxA0OosrZ3/fObFUzMMAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-18T18:28:54Z"
    mac: ENC[AES256_GCM,data:EXC3B39t5a2PT7HWGDyUgvwJNKMpko7A7IhcDG0yN0x5BJL0YBPxSn+7EzmfQEO2n+0xzQj1sGT2llTwDa22TQKARLeKCpmu32eFgvibngHs7qoV53FFnzWxT8sqU29bKn4FQGl8aVWm25E8elTg/VZNVYVJ7e8z0//Q4E7eQ4E=,iv:Ev/0RGC6wbMrGRNyDVe4EtStMh2cMbO9mK7isRs1Bpk=,tag:dGY21YsW7I6Ld18/F0hetg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
