apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:EsY6wteCzBPOTVlrG42SnG3y5N6UPvkf+QKow0HdLxWdUHaeUzjs2qHosawjjN6NIhrWm4Qg08GfBrSb6mdXTKL5dGkR7YxtaSbLnPR1DMZmFsDbZMEPQT0dCdngIlLHd9Ox1g/BmUOYo2KGHm+T9r1ql2RlFQD2imGh41fhN2VYviH4BLtLgTzqKh6nvQMXna+gJyPc99eet76/LIIfMYSrSiX9K8S6Fc3bKRAELy5MdFP0bYM3myYDanx5Bqem515wru7YJk0RT40634eBKP/kxAnFyQ5uVMA6Z2wFAsMWJOQ7sv1QEsMOcVcxiwP1Cu0dAmMc5CCb6muQXhfRsBbnHGOs7VZ0VAUDvniu8cMLzRhwNS1tk6FkMiG+W/jx,iv:KD6+BuLsYe/z5Y5ZMGYCKyMwDL0dHymXq+BqxQ6LvAQ=,tag:HwEcFMcvXz3o7AudQsXuFQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:RkGf+9DAz7V5qyFpA5cSmpnxXIfMiXQGp3gWphv8m4FzxdnyuLO9lnc8SdTySnTqqWyaskDK8n+RonUQ0914cMZ3GgD44J8W2ewaDUDf+ePrPKarbCSuRS0WZ4nk4J8YEZxHg35MHG+AbNInis0BYNoyNdV9cVOgNH4QZwtoSy+Iz4ardWrTB/Ff2fJM8eA/z8q2CDskfOgxwTJ+/+RREIgDEwjj5HADIWoR0qp/jw7Z5Fc/fF2/sX9m/yfdoYNEB3w53MeLngGYYO/5aw==,iv:dYL48by7n95IGGScMGiVofGyXpnhMQ6b1g8acHXDje4=,tag:xUTh1tD5ap8eWnl3msY6KQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ntxaD8PHoinxtHzECzJwX44sl1nchU8k8geMtyVuCvZfZjLF1cwn7p/rn9OVybEtZX72NpjEp1x7dq3T/uyv7HUFhzqqebXuCC3G70nU7UVmzEjeRGEs6QVbIaLIjnF6AtOiOvWZmJWn2nzkwTo/9o7bU7O8j0gScQlgKROLgdDDACtFuNKZpY1g8U+nKHcGu11vj3vURR3WQUQquH5jh8G1jIJhnXtRniWw,iv:hiqMmw9lZIrmryol/LBCvtKezbrH2C03eGNAV8GPPsQ=,tag:C38iCizIoyp0UJ4AZ0fQ3w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeW92Sm9vbWxqcU91bmoy
            ck9yWUtJd00vdVNJNWdYK0VyQzJjZytsRFEwCm4zUC91Z2x2WTNjWTl5a3Q4Q2tK
            VGhvTnRRa25pRzhoQzVnKzE0TkZQMHMKLS0tIDhTWUxzcG13QXhiS2QvVUFZemdu
            a2pvTzdzeEM4NUtTbm5VUE1sYUdMUVUKxWIicWawZvUOEOWJf1NlBBeKY9tEo2cu
            k5FriDHkn/JzIsEHVEs5vNR8N1wNm/twwr+/HNaJ32q284EqzxfpYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T11:37:45Z"
    mac: ENC[AES256_GCM,data:1mvo65tYeEQyJvbZmDc3yQvbPXMcasCltmxUvkrXVgsn7tMQJyA1s1qN8jm6lkixhTXLdeWF4Ajg2HPFgutI/guXR6W55pu9CaBUQZ5HwCCC7eNdheyc4jwYbUPYw1l5lJFp1M/R1ji5d6R3Hqp20dsQErKKRsjMEVLw/3h/gCY=,iv:XPGfkPMn2Utujw/NJyiJADox/axArSsTHAlL98dGhL0=,tag:jXLrigAknenm2fHmNkd2ng==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
