apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pH7MwJ0Z8wj9XPn0arovAowpM8luaqFv2SRG6BKToANR8FOBHyBtgHNdNwAndiUmugquiadBDb6CPZA7Tbj2rO3I1W0deJxW2xM0uXumeYc40QpycIm+YND00BZgCu32enmmAwztlJxdv8Wiq+l9JdrJYOPF2Gtex5rPqsDQ5dijzBm6QL2+yMDCsCpo5Qvsn3ScvCY0AMvMZfJBVXKwtx9XoR+geio6K/5ddQn9j3PqGJUSfOHeEAcMivUrEUzqcbHU7SDvsrFKGAtXsKyrZPCNz2ITiQxIcHSg1cojz2lnZ+/HONL9QEh3a7n6PS42xYx4UzhQ1pyR1kR4mk3Hn0S/NFGtOQnY4XFlKDWEgp37Fqave99xJDLSlSxo2Zk1,iv:mIyXrXxR3FNqNXlicsJmvEKrOpDOMYR0CsG3sy1+PP8=,tag:k5w0rsRwTxSv35HdXgR2mA==,type:str]
    identity.pub: ENC[AES256_GCM,data:DldFRxNAdmFW90AnEEwuZX1krEsI62YYf2S8PFqzOpFQsPKbdw9xiXqacF31BQrupPn2quHZyXNvJwGjCfEkrFkRHuAmGGlXu68eYXz2K1JqMsDHtAKGQyDrI+WsVPYbEm3G1m89gp0uCt/pTJRr5o8/HOOvAPcuabFCuF++3R5CPnzTKZj8c/m1/A3tUobQUZPah8dY70wT5WcmoIhHWDcP+BleULI+y8wXTqZtwAzFITCWFJV2VUtVCzMjFad8BF/2ySuDh0ox3SLHwg==,iv:nRd1qIHpiC5MFd4GHaHucwjvBXmnhmX2or6nik2U4H8=,tag:5GSzJP7EjwXQVbEDtInM8w==,type:str]
    known_hosts: ENC[AES256_GCM,data:qo1iCGRHf8OeiZwQt/Z3JIOP8gN26V/o++cZHkhKdEHztJo96KF1lbhW2TKafJhn+S4wQm+7urIrsVZR84p8NyvnN+JaJSumiimNZp3NJC6bnhGMW20JYSxRuHZ2O+BpcGkKkF2DQF5tCcbM+aK60EIqBuXoaCubvM9HC2JpHljn0b1lBgPp2G972kIJoiI4QwiDgB9YJef/YabHrn+apSzKSrhXgFu8KHeh,iv:feHQdg6npCEPbk0HXCbDU0WqQeQ6O5tSilZR63gMhUw=,tag:3e8Z4vQNGBbcFVRcUqpBaQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQjF1UzA0U0ZzOWgrakFK
            TXNLTjVJYWVCeWoxYVhEZXE4M2o4RXd1eW1jCkRHTktQVXo2Q3NVS0pzcE9MY2l5
            UEdwOTF3VjhPbFZ0dEZNVWhYa1hoMjQKLS0tIHhOUi9VKytEY04vczJYZjVvd21Y
            YmVqNkxsd1Q2aVFWV3JVdGd0RktKZGcKZLOvo+NQnRQLEeUPumd9yfzMrT1SnCiu
            8jOEt208zv6PAU86ZJ+kJ3BIWNVktXGaruQj2orZQ3l3l/1KdN/g9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-08T12:38:42Z"
    mac: ENC[AES256_GCM,data:F3J9i/nIgXbE45Uh7TPn/Qz2hEe1JCU/m5tz87eX1MWE58iIGd29lV9TtZTlkd4CEWenO/QqUMElpg6LHl2MZc1a/Z415bSmAGDUkBm70aVXdInYikHZdWZ1vwLfxoj4ujdQ4TLm6JwnhsKhvp8CxnLc6Vr112hhjUqmYcP5XH4=,iv:3GNsjVCy8t3LGpFIZz425Q7gIRDgib31lzAK13XYrEo=,tag:7vdVQT2Pnb7PyOhHaFwbsA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
