apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1MAkQfsMNUJ/aucqjb3C7MACavxxhKyFi+Ob86npj0vnZ6dpjAzt+JFx0hl/YIyriAtkb7MHg7kXmwF/ofob/HU/FckXhIGc7+Gql4SKp0AjFBxMuXDxw4IIvuwaH01G/GKa1skvfy1fU1bdUrd494/kL6ePrWBLqNlx6zGjc3K+P45GemRd66coqFmxe+xp0y2WY847IaLo3XpkD2GOFzqnWA5UewgS0OmwYbjUx4rx5wb+guRqf5aKBEOGhtpjp04F+DCX2c2MBpwM3MggukCBRi8ZV+sFY/rIM1QSj+Fg3z1zouW0TndR9GP2FkSAiYcN555lhh5SPt9Eir9KvRdxnLuYIlscWwz+okI6RazCHhKA2/o9MhNw20hi2ULp,iv:xnTtpvHjgyqDV6SrOmCkbMjWjNSg0w2yGHbZeYCs97g=,tag:fORszHyUTTKc5fS2R4Ch3g==,type:str]
    identity.pub: ENC[AES256_GCM,data:wUJSmM6jtbL9nzFN/3Av0VX+fykIt8Mtme6oVJVyt40MJU1dLUM5SKnrXlqpfcRbOW2XD6hgoL7wifqrA3RaoFaC9S/KZKMOrI8aaNPeCfW+KmVf5MaTFG7LnmgpLBcXQOd8xDz1hr8oxAvLL/WocD6pVcINflFXOq6b09Cp4QofPi++HZgw/P1pyiad7eg4fNTKK/l1hraa6whkYhIyl1yjbgA1ZQMINfxzWwGiB38Mv9qRFuuxdAM1FNguYa5xKkRGJjJDcFt3Opgwpw==,iv:Jlx8Z6Rcj+qqI14NM+eFuyuv/U4Bimd4D0TZN2QqaZ4=,tag:t/Kl/lbajMOBjUPIVsBq+A==,type:str]
    known_hosts: ENC[AES256_GCM,data:K6CPra7v+meDAVQxF5TTpJ6/BB3ry6EqFDVvEOTqHvDc34XAmu0OBUHZ+aNrYrjcFujtLv5SZKwW7o7K8JdqIOMzxUbP/WBzr+zc62wbVbVSG6Mt9cc0849CuGtn2R+kO7UKk+FtSUKnHA97Cmv8WbWmj3dsJ1nMfKxCTp09dQvwHm/W+IoW2KCW9fm3V43/uLmJfIY/W7LBpqOECgOQUoaa0jaRecCk+qC7,iv:q+iBWibWPZbv+d2Z7YNna00VVy0Z+NHcK66/Q6bKz+Y=,tag:Be+w3/SR5w9f7G4T9NJeXA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSWVEZTl5NUNuMGJTcVow
            QXZkVnRrdXpQeGl6YTNDQkd1RVppNU5vSld3ClVqK0d5Q1R5eVZzZ1I5ZllITGJ0
            THRmbHY4YjNrUzU1bVdYU001QUZmMmcKLS0tICtsQXFHY2RhelFKckJWYjBHL2ls
            cDg1c2dISWMzUWxJVTkvN3JtTlRaM1EK7QkGzsb1yZ/l3y0LHKLdJepduyXch5yO
            wmPhy1svSu/WF7g75bKqAuWTDZ5x8keCRM2LLnZStiy4tKFZ9jFGcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T06:22:33Z"
    mac: ENC[AES256_GCM,data:oRWnzP3ngpAi2tFfAvh1aKFXVM0SWUNIM1FJ0nscd0qEgX5R+cM2cUA88533Bv8n3k7cbKNS+kl1Y64lKvHXweYr2WiydsHIPQdfWV+NXW+CXhvUgWVoEYZmXwjJD8A506P3gw72m1Taxy+Ul8eW6RZFJQAsPPcxANDDZacT4x4=,iv:JXui9qYz9i0oeILywFC/eKqQZQRICICZgJ7/TWIuvOI=,tag:l/Q8qT3rtGKigtALcKQD4A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
