apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yQD7wutIpbXMgFvcxCazUdxFpq4hUpJvDsODwgEcOGLHit9RV6Sl5JOepfBvzHyXz+gI2kn/H3U99VQnvBtsNj4W81+rxviu2u2TQ/4C8hFlyrut59rj373vuoXBQd0Pjjzbcpa7ziVyImpzGfcOgzcvHgm7nAZovQxgMZAITNt4tec20ITNoQrPy4VIRG3/2dMFEkxCFtxWd+/e1od3vmBtPLdgXoslU/IE0r2Iw4SIurRmqgJ5wnLnlHu0Esf2O7Hz8rxqgmnM2IWVU1cQZaNUJBK/xJb03t456gYdGcGmS/vkb5Fhv78TDtKzp0rqwHh//ShGcBuulLloYF9zNXsrT6FQghu+ehp/8Jye1STPdRJbRGzKwHfknTNw11L3,iv:D5nrU8CvRGg32gpLuVO5o/ebKlNW0pISVrRAO4rZfH0=,tag:/x7CMPHfjX4hSc+wP8Po8Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:TM0v1nU7pjD9wwpqC5EFfW8O228Ay5W0ho83sx3Xe73dHB5k3cc8ziuc3hgIGSUyE5lZRRY33TlzbVane7F41glPIk0xlVMkcnsozlXo3aD/pxf302F3g2xAGU0b6rU+WwjxWhWWDB5GyXlFB7X1lDA5kxlp8Oo52V8peclDUnLvrCILgJm5PCqIaRi0hSC6YxU0Zk1o4Abu+Skily/rIhESLha5nuuL62NvJok2pd3zpBgsTonp230hc1RO7VRlsCX62Bp8PeT5I7qVoQ==,iv:ATH/+aKBC5ZFwL5eg/YSv44Dr51MeNelJ4S7sykFW2Q=,tag:OS7sU44bHLGp82rwOctmMA==,type:str]
    known_hosts: ENC[AES256_GCM,data:azBSIT+R77yfVtU2YMEcohslOsu9Kj2pTbkZrmSd8w9K3mHWXcDTBgW4AumeDd5ncg8dDvNo9Rl5rKSI0nbaCmkwy2zngmV1gmERk0+2HvQAtlCCmmLI1vrEsb92+sw3/Aa7LCkkWZKCTO0gFHkircxIRb121N5j3D3bORYvT/B3uuv7AYVhNbjSPlodKUtSEDubFN8DpKvcbEHVyAYYGwgryD8TL9zTooJ5,iv:PQQ4bs1AS/RXtEiR0xEkiENMCrgxRx+ShR2Qz+IXbzg=,tag:x9gzpxhBBw+E77fzIAweDg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMnRCNWYzbzN6VGlOS2xJ
            M0k5WHNDWGRTenBDcFE0eXo2TXRHOG9BM25rClhLV0FHOEtndHl0cHRWZTRkR2JW
            MFhydXZjV3FNZm42UjNXOHN5Ym4zV00KLS0tIHlQeUoyMFBWUHhZLy9aSU9tRzRv
            eU82MGdFWG5pQmlHNlRtaFI2WTVqc0kKHPfWW7uxdsjtiNBFfv30hbSq0+qBzZzT
            ncTbA3e+10G7X0npeRlpsV+ItbI0M2SjYyxbh02RwJmSdztTXAKQtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T11:27:40Z"
    mac: ENC[AES256_GCM,data:IQhMaE7wxlO3JNEyF4ncppJbX6FRtsc6BqOStiih0XJXBOfTlEtQELA/OwrWq/vWHyE0bze9wRo9Rwo2yi3p2tsuplI6+kgZ/2nYVCMaFh7z8bMwl0u6scwIh2C+YQ1eOQceRIvOItJuP/GP1fqV5tv7eODyEK2dqS2WJeMNidw=,iv:YR8w3Xz72nd3WX0PFEdzxb5cVmkmAUElDIUVKpm1X78=,tag:wkwqP7cF0qODegcnc7bakA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
