apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BpYChaoJK13SRaQ2FtgZvyp1pdUi5z71heystOwDCYAQjxmfbM5KS5Evo0w7BlgHORgmpiHREsZOJH/T8AmtTNrQYmMX32oNDv3ELv+my3csqQqTh7VFlk5dPntjz82C9qHdrzTgx4wNQivPR4CC1MMacYDZVNB3YEJtn59U8tKIJY6INI1HVgFG8utN69hHj8G71Kr0g3q8WattHHGbhRqU1kt9en82UA0Dh0I49cE7kCt7PKFQ7wUdPgflHApdLFwYv+GonnGuYme0TaqoFIjRH/nU/PV9br+TvG9JPVLK1u5f23yL9Snfghan+edDC/1C7k+NrhZQ+WS41UIlkwL/z5BK0Y4AmF1noYZnTzf5sjAfdqXjtotZ5umk3tT7,iv:4TedJeUvBep+OzqEeFdWcnOovIhWV4w8qqcVKST+NfI=,tag:6gms3J8adStb9bRqeZbKFA==,type:str]
    identity.pub: ENC[AES256_GCM,data:hT0rj4HtrOPA760DzrfOvTG2r1zbw8MRal8ODmus5AI5fZp55ikvei7PYsRNY3T0mpwSQDwvZloEQtWHgYJ2HQVxtofeCmeaxj+rzeS40Lzde+sy2CGRKfIgvuuVG9CS5UKClIGwf2hm3crMnRPLG9Ajv7HcXdZud9FgMoCGribyJEeuGbm/Ga+0efNle7e4q4pcVc14m/vUlHjrPzogogQmBesPLGXFhvMxdRdzepRIzteBghQPNXWESQEPaRmQ/qoyfB8a+bV4EUU+Uw==,iv:E1HHePngyPmBv/xzY4VUMYUdbY6bsBfoDLjv9uRzMJQ=,tag:MDYI/R4Hv1gUY/mnVct3ag==,type:str]
    known_hosts: ENC[AES256_GCM,data:SiFjx21iJ1Ga8ylutCuPU7OP+xYL9ltSGauKZlCCHH9dme9pJmaj6pfLF0JsqJxO5OIU179Qf6PhyzDBbnQ/5PtsjoQO+Je+Xow4j9LhfKsytlc2PmAVZ3gAvS2km1n3CtPZRmoKD4iFJx2De6QY9p7SgPe7Xg3UVgC8/Dl4pMUfqmolZrrutH7o2xEumlNBy/1Uz8f/dFvOlrWjhJSdumtIbadoAUU/BT+A,iv:ODZ1gTjDUAbbZ0qxKcB2unRNKFwxJYiORTaZiieOpvY=,tag:uozCvTRd5vlmC9cTy+OWBQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZTNYQThTOHRwbGdBYkQx
            Si9XSUx1RUt4blc3STBLRTdPZWwwQzlvdUgwCmFMNHdCRXAwQnYraFQ0dmJ5ZnN2
            ZEgxMEZnWHpEUldmWHFjNXdwdWMzR3MKLS0tIDZVcFAxNFRCUW1UWTJ6TExhbisz
            VmtIN1NGdkMwZDYxaitZdzVhOEx0KzAKEDxh+VVPhihQkMYaJlsnPLIlt/K3uKbC
            WTV3QJmaPI6Knm/PH3J7mJiWcDnTdIBAQCzOzRlvEIWr+ju35wcCkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-23T10:15:33Z"
    mac: ENC[AES256_GCM,data:uLU/4P6HX4BiUcrBeS5H2F/jXYz0YRN6rrH9RmFwxlo7FnA42wPCZDKEm/BDTp4qmCLff4v+aAJl6zDK1GkBadfpA2dx+kBwG4HGt884rn6yAIWQzc7IUQQqG4BPznQwziGKnJSJefW7d6asiHaQGryI65xgBJil7tZWKjT7xN0=,iv:d6ua0g3f8AykyOTilqp0q5ntQxpDl1qyoNHwQ7vdRpQ=,tag:JG4lwQFaW+CR/RVnoxKdDw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
