apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VXip7b6fz/IbfN2KahTgqjwPAX8FjswTZyZCyNFRzhnFsFrAtjw3iM1lFSdRQZYxDbQ3Z2Dm50fUnZhGlwLt1/BpS8azT+How8G3xbWDTsAxVljyze+KDuVmAO1hFfUwOWS1cxqB0U8T04ydvp7bECoVJBj2sXUM+HCNhcDLNp40w81DQrGtSW9hS/EcxAF1mI0gTAekVqva+RoOxYNz/mYjnC2v64+kU7WjCSmJCW7wHDDHLyQZEezzBXA2m4jAcemA1vFL2ZHZl0fIY7UPcoAsT4y2iyPsGoWmiJhujZxTwSZIWssylP0mBIBNHWsLshYlrwd8kD6xu0BtU8VR/0dAsbZpe3YDTpxqSyZUwFhoRE1NBGKzuCEzA1HGE6FD,iv:liQedY2dxSnCs2mAZ49TRpGkDtzgUUbnpwYp6gEpRrg=,tag:Ljvcjp3R1U2VojUZtmTkrQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:XvlgXblSCNfOArcQgJ9rWziofAydB4YqmFjAq1CPiWUa3ZHFxxaSLa/F2jUED5dOVbRNuqnm0Y0VmvWLRXTy1J24QAvhnK71N6Ru+krAbvLs6CWctgYby7v99709NprMToPF4ER2uaQ1DfXediNK+eA2i8Podtr115gnXjmvvxf5YvfvZ7rj5MkIQNsR/mAnPJSVy6t/AdRSOh/QC1sETCSflCPcIMQrVP5FsPVFuEKqTRpsk9rUdFLY1XZ6xFjm9yTobQnoMr8Jf3YV9w==,iv:ME2CBwAUlWXVrmtPfXYfqmGaRFoMeMhuM33vlCWac4U=,tag:09DshG8ihJb/fzk0SufJvQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:NUrWI1wHc6jB+BLvZLUdO88URpGcTLD8bNeOwWLJ1cWeeNypr5K8IqUBVGlylBTqkauyVqIPUVQ6dhZTBLr9+tuvI3Vusi19xTi8GG5SB6O/2nct/DovCCwGN5qwaqCtgHCsxSXMOIL/dU+TzuMmP4GdLKVOVg6nPO51DNYdjCHq09pXXPGpP6YWYlqPOwicaRAM1c5jJy+fi2gI+87FkY/KkQYEzSztAoqh,iv:DukE1evf87qyWhTqZyVhWOWS7Uy7liJvz70jvV8jZMk=,tag:h6amCSq3lWTAgPqSDpPcbw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQXhqa3FZZ3JGdXJ6UGNl
            ZGlPUEJTWDdlTWZZMUp6OE94ckVWanNxUEZrCmg3K1Vyc2pjRE5FT0ZaaWtQRGtu
            T2p1NXpaVmZtS01Lc3h2Z2VRQkZ6YjQKLS0tIEU5bnNGQTdud1pRRnBUQ1p5M1Fa
            RkFLL2hvM2tpKzlINEdURzNYOVZMcWsKixgYndG7yJiRNZINEXGzwolXkcIjnGna
            a6pkqyvTx4t5kZQsVah6K6fXyQRO985J8ZLkm+9BpmQgcSygZYmYdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T10:40:14Z"
    mac: ENC[AES256_GCM,data:ML7ZDLzOIQIBqMZgTqpUCFjSHMVm0LHvJBZf/TIZLrJz1oKiIY3KRX4QZNoBZ91gjjQK7AbMHlk7GDTOXPqVujrBSb0k3sYLSxcc+ug6GI4Es4Hg8oCvEk1KBKE72PL86KHDvfNi2WqDvYpetQzG61zdSgvH3z2jVCoCdwh/toU=,iv:PCNqR4/vjV0Z8mOVBy8UhwQMzmpTuE/7Sh7wZJAaTho=,tag:JQylMFro3hpFiy+dV2PKpg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
