apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4DUp2NzAeAdccbqrd+qyCOYobWu5JQymLGjbHDkIfyXrqZFRVuDGgXK5dhksxM2nLusRll0SmzGy0lPi5Y6moV13h5fj0wCzFfL+JJa7FEnbnBAy/63afPqyMtCMvGr21RLocG9phkBAhSQJheGttf2nIjgatIkvm7bW8w1YGM15RShN8IyI5P3Wkt0NWyTCWG+JbuHPOTaFvZZaSPUB9AWUlvygyZdEJDeHE2tmbYIGEQoJnDOtYu6LzLXw5l4C69uIhnHapAByWlgt1umqc7uV++Y/93/vS/PCR98+l4ezi0LakXZrXkizVcFh8yShuAPkn/CGUuqwmoodQThLoLgh886Iwb7boxVqhn3JwYc2CuNEAzirCa/XbsPD/7UC,iv:BXkiQIgon2+KyC99NwsLqlwdb2Y3L0lKF6BaC3Sakvo=,tag:FMSKomuv/sUCS5PcG/Sgog==,type:str]
    identity.pub: ENC[AES256_GCM,data:DO0OAe+LECjZvKIZMfkd1PGUdvARLbwV5u/JmTXaOraRdtQCqpAUkLL+8JN4aPVxQTAZcHUwAeEqZYWmUWNmYB6rDT1dqZ2RTMuge1Cht8CMQ9mvBslJLWEXVUgOp48utw3CzU+iysrqCorpY6nXhkBGTy1cl0LQreOlrI4SX0q/0ixKG3/qJ2UL1q79omngAr2qFd+eOrHv7rmf7uQFOlqS4mFXs5JykYJH6cv8rBn839fjxku5E3CCEpd1JaiI2AIdAuF5mkoPC/u2EQ==,iv:NQqnEU1eHCkSTq8dQV5Z7V6hGauZ2Tlj0K/BbhwhNQE=,tag:No4ZtQAqFabbhClKu0wG5g==,type:str]
    known_hosts: ENC[AES256_GCM,data:KTF3O3WSxuEVDlMZbLJA29c22lfBUaVTvpKlNE0ExGrjC15WfsHCvi1YMPunKxzNhao00GLRS7Qx/d98SnjMJoBd/7F3txf3+yXgBQmssuxPGogFER1KA+K0khIsbO23iaoq3J6YzFcObGwyUsufNxmbWAuHrtKV0aDilIA5Hhc0ztJUVGCdKPEhOCWaCCMSEXyx2+iT/XTsI3Orf8WEhAuT25/ms7nSJH3P,iv:7czme7sZvq8kbYxH8Ym4qOnpa0YF2ooLqOOKDs3LNlo=,tag:/UgdLmZxlX/zr7GPs/Ji1Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbytWNmhQMnFxeFg4QWMr
            Y1A4eDY3NGZRUjc5Y0xoWHhCbFJ3MUJuSEVvCnBhTnJPVUpOazcySW9KRTY2anNZ
            elJFdFlLa2E2bmNQOWxpM3lYR2p6dVUKLS0tIE9QMDRKQVBhMHBlQnRWbm1KSUJu
            Q1ZDV3F2b3NyODdSSGdKWlZNY2w0bVUKoxQnWwEXFiDmSlqd585R9nsKPKJ7Hs0J
            n/Y1RTSloVA2e5AU5UZz1EI0XtQAEy8MspwyxsLBe6tnvHRVs6sSXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T21:32:09Z"
    mac: ENC[AES256_GCM,data:ar5F55t//xaPR8f2YtieEig0VD+SsrHbPCyUHVSMhGitF+LNanQ0cvW7yb3pDD5t5t7UmX9XK9srndjih0p4nI6FpM5TrVbKP7DMs2oCZcbdXE3gdKpSrWei6e//vjbWgAcBhR299VuyQUJWPs98sYst1WuD1JsqNzJ3w5SyaRY=,iv:Ep8PwOm1EwU/hRKDrUdqpuyiRb31N6dUx/pbQuKQrvY=,tag:qQKIvOY0lb6YYzLvl1GtEA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
