apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LZaii3KcpO8aO3RkL0if+h+FOOwbpgBsDD8tZUyjpV5Ce01BvMDoKiI8KUc4RDX6l0qV5NW/bOuqOwFvxInSHxrZBljEWrPl8qRjx0IZTofR6iB/Y9XOL+IqtvE+hCngqEibsgyVONkREoGoDUSr28BRbapTm+AQW2Z7w9n7G8GJRpMzv2q/v1SrYRTy+DFvIt9l3Mu14WaFgTy1BWhjx/kbRPCx9oSKp6nWiw/WTVHYVHuo6va20G48OdaPU8fKIHNDu8CmhxmOFvJeLSdy3rSrAOSdQ+BB3QOneQD8hnE18Vw9MjyLkfDxpWmWJAg0Lwn0r/Nn0Oo+jJlxe1+IeKs0NFMqQkrIRYlWXtaSTCtiJ1q4WswfZXFVG5efAKdi,iv:qvJnsSmfBdILVw0d0Hm7DG+mH6vzFeF0nEgGZ4nnIOE=,tag:7GumMPq+j5NWWiYd7OFePg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ao1z95PdZjBA5JY1jjWdhxxTDICs90zRAL4mZ0UqtfoPeDZrplsyNpsSE8uATVyEGLTIihOPQo30WScr8IQzUERDTQSN/J77r1R6qvUNJyJ3yr9wGoT9fD2WXjT7sJOqLCmbKvEFWJS+bmMauMhVkAIbFHTOnwh4U+gJ4CwOnWJI3+d4aHachqFUT5nz3ibDHlFyd/Ph5nf68c6i9FyJ9H2yGDNeN+I0RY6Ke3dbxCN/3aUn0yz9Gnf2JCfgjzmub5pr7UZqWnRj31F1Ug==,iv:WT0ObpiaVoyUcfunDE2YOBdPWqRee48JsDLOCnvkxy8=,tag:cqSZhgRMZaSJp69B5thr/Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:mKYKh12tp9nuFoNkI3CHI56bmcmPL28laRNKHpD09Yyv4dPCi+VYVANq4EsPMuU/9aamID6iI9zWQ6oPv9qFDw1emwAImOjt0jyI/ql2qezYea0pvc+x/e7px8FN4aiYJKPURCmMlAtVW6VbSBl+9ODJtHWWUFrjBGEUuSa7mSCPjzcahigrAWwGvv0elF4GjEGHNiagTSNOk385cpJ56aMPZ9+VQja6xOah,iv:XuIAqFoSZMMcdiKmkcKpfsqrtVCWLhujZ/5mi4eTEGU=,tag:rk0oqwbpbP0SEjQQkaj9Yg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K05xNWFXYkxLclVrSnpJ
            ekFqQTdvRlF5NEFCd1hzNHdkTHN4SHBCY2cwClVnYkpOZlgxWVYzYisyeStvNUpS
            VG84Z1FsRzVEQUFha0FaWUhPb010TDAKLS0tIEJmWG05MkpmUVNISitpVFhpTmxn
            N0lBL1lkUjZHSkp3WWF1aURZSHhDdFUKsGA9xZ7+D48+hs5o01SqLFCw0rMJQCUu
            Ag2PnW4f5zSWtOophWE8kIyDnP6vN91YVUPAm5c+jvxj3ZCiDvInFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T15:42:07Z"
    mac: ENC[AES256_GCM,data:Gs2DSQaxXwzKUY9H5w/vQSaYo+VpD4K03dNCRItTvfB3NI1IZvlVs52OuEeW7KCSb9Gu6GWcO4W6ADn/5y6sQ3in1R0ygLj+KRwqUuFjMSbXt4M+F1Ridd9Kn2y01YwQW7lUQBpkWcjwfrHCsHaqwCIo0067hhB8w6APbSMapM4=,iv:tzQA+A6XEtHwS8wzY+zT9vY4H4s+yIxyKdZVcOlguP0=,tag:ZoEppoTNompjQaAT0Jz8WA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
