apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tgBtMam2JbHBFpjJqNf8kHA3AZreEzgZmQvIXDXbCtc0rBYM5Z0pcoFaJ4KN5Rv+jH4nyZTV0uyzB7DQ2+o2HTlZpE6mjXY+cKwmWvN1t/DqWv103kUEz8ZEfDDy9qhFBMr0kzjaQZWHrW5EZgr1WnpBmJSiH4XR/WVhVAvwD+h0sRiEnOYsojWfqxciRgXeCo7QiFjm9YfY4CoA2MCUvN2+olTmvSPw0DDgVVu6PeFRb0lmNew5wDdeRFgkTy959zB8LH8QUeNlxyFO7CMRMBziG73BVJ/IrXRhNF+16/RC2466+YlQu9DxbdsCi1yhz73S7PO0M+Czzm4ibwLectzAaZd86l+rQPV8tvt8QAr+vJD0NHvKeHxlX1bRACn6,iv:ffnndTW4y99fsheU8NCeqm6tKs+Dq2AFEqiIFaNnuRM=,tag:UFIpnkjUA48SSW8ZAKBYHA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Fq/7G03XF689xVHw5OCB6oPLWPt1o89of0tOnBLf4xSvxVYq/nXswPMFSvMyV+7b3OYIz+Si8LpRccSC3EYwMb1O/oCGtykShU9r9m2eBANPu4bsBGMspFhWGeBzkY67J5I5Kh0OGW5gx5w4f/cOQRyj03PRkwBi5Qs5dGQnxL11qfF5BpoJ73RQe1Z0DH7YYHa1I/ecqCrljfqHVb79NAuA6mGrnrlkIljUywoWgqMUAt9BZ0u8I56WAnuvpO5vrMmNigr0lmcc3hL8Ww==,iv:rpWb9aGyvVXIzxF0R7tX8qbdlvLjoqigwD4m80qCKqk=,tag:Pe+VUTtgyU1xQD0gOh/ZrA==,type:str]
    known_hosts: ENC[AES256_GCM,data:jTSOfVdTRxElH7Jr29d9ZKclojQY2r5CqFuAvjdTjV+lFuyAW3rP8RvqiP0cgfXDoKWQcK95kygkx0mOa5XLAlaZ4VoqzabTpKP+EImYT7HiyYx/cRq9It2se8z7uxUAlYxGACbv5TBbKyA04R+1h23x6mnjILSDCQslWOGf31JpRqRyUV8sfNE1GknQ88DnYnNcM8VAkItaoN9YaEKXsHP8B2vcvomxDVwd,iv:PwLV3RjHsLTQgF0tEwz10v1Xnrj2VLj0jQYKKn0v5Pg=,tag:HBN7C2K/7WMrgPXk4ArPPw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VlY1OCtDMTY4K1Nab3hQ
            UEk1SWpoeFpvaUZmY2FFc0h1TG5GaERBNGd3CmFLUlorQlY0cDZERnFuRElhODI2
            UTlHTVJPQkdvajZkSHUyUmRpTWRKSHcKLS0tIHA5MnlTYmMxWHRMbFZQQjM0OXJB
            QkhYNjZSVWkwQkdMWWg1bndibUNHUlkKt4X3WS+hSWgqjynvFC9c8XkiQn0jwlcs
            OWMEj+6DY1m1XDnfJZPkIkB7rsOqE2ezba9QWAJ42naaM7CH4v1blg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T19:58:45Z"
    mac: ENC[AES256_GCM,data:QtQKjufCOs3FalkI8DfKmCtzdH8kJ/zXE48PRV5sffZbGhvS6EJvRESeC4JrbQueYq2cM4FX2Q+To1RhJX8MV6LtdDt0UYq+8MLSO5dfTaVlGNYl6fQHEBzkJ4UmtfXw1J74i9U32w6ZdFjt3+q8jxFHfci7NyV16vhFm0+CjRI=,iv:sPmZ6m2M1SZZS0HS82g11p5NC9g/RA8izXe2/OvsD5U=,tag:8feneuD5oHRtVThxJF21aw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
