apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QJXYLTowCTgH5ubsq9GUNsJfhN0b9mrjNJy9cUim46Tu9+mttvkmumSN6X6T2xHzjFwlEKNrYvbPUoUYex7v13StFmrAzMFkgnR22x65kRzVBVbJmKK8vBsAo6qxCKOu12ThZDXv9Mtn1f+3X8xZOjkt0d5z7HQj3Kb0JEAioQtJGI8CbALe9GlItFvVpnKzZD44fd+j3QnK2Mphbv7PpPCIfm5yZ5yKkioQoXQkZwlQnP++U8JwHdjgtUnVL46J8i+ALmrgxTs0hSQ7u/0+9dGNwuebX5KSooBuXJq9OiKlnLxeO7Xgpe+AyFaXNLw29OrxQF4ywNB7HxBrRoxeRRl6KocuHG7sgpg8USCVZ2YyC5yLQ6gzfb5FPjkRAVB5,iv:ZYfPs7y1GZpPs/QzSSny8QY2Nh7zUwTm2umsOjYOUS4=,tag:Eo+Nlt/nWseZjYZkx/u1HA==,type:str]
    identity.pub: ENC[AES256_GCM,data:N1GWVTADOf7nGU5Ka4zE2Qh/YAb6O+tHWUcqCGOZvjdGOIGe+jJALoYIrid2QO45C3hWuBz65o3RBubX7jNWtDWGOvzplW4eP1pkM5ebg/lgc4d1k4vqV8OhAlFHm9//pp9m5PV21fSpqnV1efpq6nDycbDPTkHj1Fn0+GcieTOdoIxjzmAaBkIh2fuIUx5iaz2fGfy6WVgHMxXTwl7KfEmOa7tRFTDJ/hIZJFwlWRlAenw25R7MEMDVxkS3Mb/bRB/08UzJDttn94XNzQ==,iv:b6g59BlF124uVSuvp7A0+Vl/9KyZLwDlPRKj9LR1jzU=,tag:DCLmdo1Tt0issAIHjJFaxQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:SqeIaE2ReIu656MjNgYNOkCUe6jBxgFx/5KJ4TYZz48aM8ekmXC6vmD0GIZ97TliRAW05QOi99h25OXBqMQOaTjj2/7MwfAL7LsBHXuXsfe+A7aZOwsWiZvlkEr1vuI8gIq6nTij2y7F8UDrDm2e8ohk4OfRIphmdHcunFfKldhBjgHM8KlzP3PepL3GQa7x2mKnuLkyPVN+iLukx1DxCAy8UT6KFTwCci+f,iv:HMtDilC0TAnQ5Ok1K7IhxH7zi9/M+dVA+4LeZ07UCpQ=,tag:l/HXY6ZCtTyzteujTwdq3A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTHFEVkJUK1VUelRjTEQ2
            TCtzRWNRN1gwekh3cEFkREMzYVdkWXJwQmlVCldBVDhlaittUWlQWHVIUmRwMlUw
            TnRHNDVQRXoyRlZkdkUzN01uakF1RVEKLS0tIGlKVmtrNzdibUwreC9heGc1d1hu
            cXd2dVBDK3hCRndXZW41YjdNbHJPckUKH5fQAjJhqNRNiyBg8WJvlw4Y/KRXYSsR
            YT6t2EMPKiQcIr36ui/rtUPq0OPPAMLa802CRCiPdfFFePtRKGNJHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-08T12:24:16Z"
    mac: ENC[AES256_GCM,data:SlslePYeP/nk4Hk8kagtQmBO2rFvvDysU3eMJe/58crFXEvzxQom8b+cKlC49UZ4xPuFNxUtxA1An64LuV2/4HsNEvV2F9lawe+kqwDjz4CfhyjzR/ZjZ6GosStskpUR2lPcaNLvp41CotZpdmt4MU4GC+tzy1QDmsu0a4TVQAc=,iv:TWAtijL5eFHDfI+lyiJdWN/SlzCaZUmvi90nKoZl/t0=,tag:umBPxOFJf8Rlq66rsjunzQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
