apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:cYDQW5gM4df/1YqN7/UpgjxU5IiGaGKjADQZvbXqTpTWgErOXx2hFT8x0u48DmViXorQjS594lHmAfCMWqwjXYMpTGIDAjDx+u1zTXQ4JeQlHHLPRdpIbwsGw3GsKKSrn4fiodWodErKX4vk+6FfXjjoa759JHpPMlH+VFAT+RkoOLky8FrsABp9/Io6OLHqKegCd7/Mjkfh1yqrgKYkPoeAA4qAxn/pBtHOl7Bj8tehwX++o+uJvCXRIOFgQewk4lS8wzXqmKwjih7NVGh7XYWluPkyo1xhg2PQZzlptIHK++xRD8FiCDO+4KPqCwaPNVj0g/FTtgDcQChrMdWLnOCQaJBsJOcHi1cqy30r2bpt9XKrBXwlD4FneLO7w+O4,iv:JY8gxvjTrYIV6rwwIDOWLJp8Hb4EDdfVBXEyFlz6CAk=,tag:KhB66uA0NirvKCLh7QWHxQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:4uXhLtcGYJtMnabgYHcmW1HlX+Dfsu2SXSXuwWKMa/EUFO2GXhHjAUZoo6ciJPFVfhHBHCmdONL05QI02EycMkgi8g6P4ZuJnbsMmmjY5YfBoYwcSWysMm8B9K5URDrwDB2dwBoXcL/0UrH08HvJQ08JAuJ0/A6nl0xkxTnWMISJw0z7s7MFcnKkoRRchYyzBPMk4QvTM1zTFWlzfryUrBZ7EqvRrdC3Fi4Vb1owy33TiigZHLGb5N1IC2OiHqisz419+VEI5cn2BDCTUQ==,iv:HNsGPJ/ldlBWwXwnx9F4OX0F7KBjo1gluWUU3Y249Yk=,tag:yaHNFjMjcVrAuQwUlb51/Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:XrMZW2y/aPWJMHcschXhqOsUyOlJ77SN8f3uCbhEfgntdfkMRvowdbzmpPh41vY1cbvB4t7BIihZtS5OcppPh94cpLkSgp6+GY9P1FL8Ii8AS6J13nljp5kzM6EUxMLrzpeU9yAdfp3xc4wfWeRWpp9LVVyenoPcl/Cr8flI6lamb1PBGjljxlrGxtCN2BrOwOukKqwH4E27MAKYrum/YUtTtvkg0kgchK1p,iv:/KsHtZDdY3f3XYg+a46SMau4eTsnLuuL+wJ3Pa/vvP4=,tag:YAxuUp3LBtYF+D+pVUs12Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK2p2bjdzYnU2ekFObmUx
            Qnd3MUFGcXBONE42aGRKMERpS3dwU2tjdGxnClRaV2RYdERnY1kyMGF6c0gyN1dT
            UStndWRwTjl3QWtqemoyT1FtdVhmbWMKLS0tIDRRa3pXb3ZETnVYV1AzZThBbmpY
            NmYySjR5aE9HYjNsZjRPRkFBZkdsT28KJhguyt1JstuAQrAsBGWy3IJT/shYIwpP
            ApQbLinjxWziqBxn6cze6XCVbj5ngYbUgQ4YUI2H20Ddhn87XswRFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T21:31:45Z"
    mac: ENC[AES256_GCM,data:gsCs7DiVprjBvZ0V5dpiLkgZy+VnQQ676+c84o0HWXltJIrcMbHhyGbi+JzJyORMIVLx5lcggcRSWgW7zk10f+xmbHfECfjyCjg8DpSfDNmx6tKr7/RPqCPfWtsaseVsvWs0qW4s6RBtAFmhG1kX/4mP5s/Z3ZtFPiy/nHI6L4c=,iv:w+1k5GlF42xzDcuPBqyb/sawQu1Uz/nNkez2ituuq5A=,tag:tNj0FCumkRwt+qsCiNmuCg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
