apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dZkGzfAXwMjaArnkeURbNinIE3a5GxXROBAmYpy7gNO9N4lbFnSnnEasQdvB1YbvT7GP1UUu0PcCDYVvNeDdvHD+h3BDXGbd7YwAkD7Khnu/+NApWqB4XXy8bzNtJSPOhUtf9Su3Jbne4o76O5d9xTwLfPVJ42/9aeYIER05L4b1amuhbN0aCXHoynCN7z5N++1NCotyqjuPjWOLHJ81t/AkVOuU/qkTvFHqnBaEp57e0PMl5wE82dGexU3xShe6NwlSSlNBCBaKwtjthXPIm0Y1q4cjGCcf654HCKOJng5fomZeQ/JKi7RAzH+0deOielDTDf2ZIkj8rmCSpKIL91Mf4Dvda/Cnnv12zgATwiJtT6mOuqNt48+eRvYtVerP,iv:gSdwUl6FaUDuaDst2EIaDhYE6O2L0O7DuJBeZZJLoW4=,tag:m2LeQ7HqsHdk6cI6ZiNUuw==,type:str]
    identity.pub: ENC[AES256_GCM,data:qaOfr2gnKGHV3RS6C3BQdcjeNajkDx2VeBIDDDkrINONYDoxN8qchfE1s+4Ad3j155Zl98RsTtulkVBazNBFeRlPCUTiR+iCWzwnTFBmi2uvVQWG/UiQVwwoTAKeH0DccLRUEjtbKDqHbpgac32cWWPOaS6GMZGFAgLFrLopdNjQ60Lrtdl4Z2HPxIRkEaYmh0TxaJE8AArNUCyx/KhLQ+nVwxDRSzZzFLJ/Dfm1axlEnrWOtwSf/rSAUMakMsCfPiEgRLmUZ4D1ehJlfQ==,iv:AgIXrk2XFkWsIXbRYgWaQ466vfhvYRRbuszZqTK28gg=,tag:OoqoRAqiplOqnNXFrpYZZA==,type:str]
    known_hosts: ENC[AES256_GCM,data:sPtL3BtSHxbprutW563SdkvVwV+CVi9+0tgvf1mrlNLmsF+xbDxlUxmmlQep1HxnKKTiWJTqwhx6UdHPea6KSrPMU7m8x9kACbkqLRCd5YEFmGgtFfxSNeo0D5ruG/g5lilmfpm7S5St2tFBXICU//IFqcGl5ZpQ+sF3bi22WdjWph3hbz1b5nZo8bSk+PE3K8U5DOi9RCAbBtkyWDLkJWoT8QbIh+elsvtJ,iv:EfAlt44ALpy3AMOFT/UQifTGG5V4qtXqCtoLtEIp6ak=,tag:fviMsvlTWNwUeWI0wdz8Eg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNkFFSU5CcTJxcDhlYVpH
            NHorNlh0TFgxTTQzUzBGNjdhdUw1TnRZRWxRCkttdWMyVjVzcmlhbnRuZUU3clAw
            NjkyWmkyd2VxekdBL1RTamhDTzJsdW8KLS0tIERucGhKY2tQVDBBR0xoSlZBSGx6
            bmhwc0t2V083S3IrSWRvNGJxM2FLN3MKr2WUh9WOGgUGZErAW5D/pw2Qre2I/Bdr
            TJBneaMUaPY3oyHFiQRxcwhwzh0UsbDkaMT7pY1mpnMpFlpm9XFi7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-29T08:30:07Z"
    mac: ENC[AES256_GCM,data:fQM6tCAbxfv703v3nGw0PQW7GORaU4VOwfNUG8YbkxGBCy9oNGqZZ4EV+PG79YYDeQ5fqXtFq60WkQjRQRxN+FjWFptSWwNPxFdBT9FdlayRepqkTLbMRSINKrWfcDuKQZnzaLRSBWA1+/c8PiSliCjYIsT5iahboihg7OJVnyc=,iv:OH36VItxBMsuYEJMEglXa3KBEpdaPc5YP+iNIXTOA9Y=,tag:c1GB3tSDzaZrnDwCFbmDbw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
