apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QjBrgAxGWB9K085cyj/9z8Qu5z/aEopv9H8CEQypJqw9W4kfW489VRF6+6xyyeB0TeDfyYmLZCmp+Vem+OvkeNqRpnCeaIGiGYD9d8uuJLaV+WNBV1uDAiQqGRYyMcqRAjrEwz44prwRSJN/Y43en7HVrcy6GzXJIGWOdPZdGdSk5tR/TwWTGGplHCPjBAGFVo1StBfApHw7gEouRipmpv1pSOQomkmTagD5/iREqTw3cGbavwuokhNyMoc9I76E8VseqHUsBRjFNCFDibiAr5+6Vz3j13mOqtFRk8x8qm32wtkSQvgXi3SGLO7i9vPaXXYgUPrR+hztMPhRlqAjk5txI/RNCm+Zfrx0IxiSv+Ucu6JqFQ02QaRgHRox0778,iv:ynfzZrYTlPAHZ6g0383zimxYz0VrvSJlS7lYr9o5wHs=,tag:Y6QufSs6rfsjaNnocInQMA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Tx2s/VAcUzbRYR5ejfXExkS2tqfWPdZ0kiWdItB+pK/YCA0Y7yfqgqjcqW1uNEYO+TS9VyWPnGZ6m2Yekstl/K1UMU8xPEQBp7e9Lk/zGfbFkCMh+SdLww7lYfAqpWbIym6Hcg6h9e2dM8V5SXAeyeT05nkvIzmNWBMMk0spSDTbmiXvRjjfOCB/Y95p3s+K1OhX/6ghvwBydoXNTrvx0cqHAas/j8a6pcZmDHfaXNCinDrU3bTRpkg1zzV5VftBx/IZhZIoPOC9bC951g==,iv:J3DExctR1ADkjA96AagFPbZ/eCsKSqiBEEiNuuG14yI=,tag:JKBJ0kr463Vz+EnEmWQWDA==,type:str]
    known_hosts: ENC[AES256_GCM,data:OaH12i+xSvMzDnbgSt/QNLxesmj/tC4oIReSvflkz6yCOYAmMIHwCdZnCc4ydMFQXZAcyWNjzfqmZHZQq4HQWKSunh5coLt2c90Dx8PPdtf/tvP6N6L9FR9kYDEs9IRtz7UuD0KuNuq9W+1dRI0czdYdwszMKZiG/tIDxJfuow410rVnlQ5cbjA5131Kbfs6BHQnpTAwvDkklWO/Sbsl10r4zAf+EXZrJRyy,iv:K1ZYnH8fh1/6s8b6Lty4MBY7l2S88sLyvg1I01Nc23w=,tag:C9A/9YRmL6fTS50IcG01ww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMzZkQWJWZkpUQ2lOUFlV
            dmJVNHdXVU0vZmt0UkpTbGxETkl0bHBEZlJNCmtHcFpzQXpIcTRSTEdpS2s3Q0o0
            OU9uSTVYbnNjYjlCNWlaeTgxNmNOTG8KLS0tIGVaSVFHenZxOFU3R1VjNmZ4cVBn
            SzBSMmtFMjE5cG81OUE0YXBUQlRmSTgKffk5m0JkHOpJ4yp7GeThwOSnqriiIk1V
            5086QNA3s3DOjCpNyFDeom/81/rGEy1Uxui5wIHadXa8wK3h+bnJbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T12:43:59Z"
    mac: ENC[AES256_GCM,data:8QpzpQyVNXWlPeftKVSn6d8vPywGGuSSO7Me0X4JaiF2UZ8Hwbl97C7Q8eYowYv3XS/tPvP2pLJOi3ZV5cVjlzEhU0Atm8CtQjyURW91kOJkBqSsYB9lBvLDfRszO5l4Ipz2S9L3rUJeSZyhFg9CmWp60e2T7uL83cXYn3CJHKs=,iv:k8YaqSaGtwp0CN3stQw1+9AgVHl9KuBCT5dXx6tW3Gg=,tag:0lKl9tOtnxIHCpWvKnOjbg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
