apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NLRcpJ+2NZEXlyPEg2bSa/tv3HGAnYFYYgTpWet8w/PiYtX6h0s8AwbfzKoQZuqSESKJQDhwgWzWSHEXNDjgXh2OfCn8Q1nClXm4M3PWXj3Ky5o8qfkPURaQKn7B50YqZz/LLyWMqJyh7xZ3JAUa1XtIhfv3Hw5+O1tRfpWA0Es/z0bOEEjHTk6Yz1O4+HId8KgO3Snr8wNyZhmGWWBRVFLx7jyW0JQLovp+SviFHL1QpbDhrczsc3zTxl3Y1WMltmpgmBf8y2w+azFWG+Rt/nBsA09yDq5ojI1DqtUkWJul5EH+hhR4fderOLyvjKZwpD7qRQNQfu/opEoFawRGLbQ3q93gOTxxxjcfVDrmaKK8DfMcY1YLlkWdRkMZ0KFn,iv:p6yVOIF03jkYyFW4wn904PK7dux1ol4p9OSjYpxiI9I=,tag:tT0/3hYcHIeqrHBef6U/IA==,type:str]
    identity.pub: ENC[AES256_GCM,data:QNC+uYVU/ElhSsGaPRvyYjXzoRD1pn16Q7HhZI7ITtylIJwpu5NTQ+ZwtHI6U/VosYFCNzLygmS8wTShvkbfb+C4/BDx5tfIb13JJG39K1K9qU3IsDH5ktezG0MMYI86MjzUQvPB8h02VVHIRPhNnsPpe83Mn6DyaYVtnuRTvdJxRWX5UOVNUC7HNgj6JsrxDd+phI3z9aGTKSWgd7KJbipiQzxp4uoHpXOrzBu9mRpPoNk+ADfwRW+lqEem0LoPe08bvo7qB7NagsVxFg==,iv:G/Xq80B6P4pBekUio4G1pyD0Xs8gz79J6N3TXCs8azw=,tag:PLSqyUV312K7mPlQDSKCRg==,type:str]
    known_hosts: ENC[AES256_GCM,data:/Zlt4CgVjpTQVxyV6Hw0fYUqHCiO77dspvytWzn4rx4Skb5L8pvxnGDaPx5Ko7THjQWACzljdX00ausJVM9oNG/F0kvTT1KohcyEbrq/Dy8YhO0whNLh8jWBOMs52/4ysBLGUHcD3rdZ1Wu04SYke+DghgTqB9IqGgMNJtgIT9wk6HSSC/rjz9md7fSghnYdbzUCqHgQPxalkdBuDaVnX4nlwxPfHgke+ULb,iv:QauIH7nUl8izHVpZaruHmYmP5itFDThxTLPqFqEqK08=,tag:ovVivGK7VM3wWijNvpyzNg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN1R6dUlWQTYwb1lXc3I0
            NVZiNkh2ajNnRVJ0UU0zbXdFNnQ5SkJZZ0dNCjhydzAvRkwzTW1DNDRiN3hsMWFz
            UFhyM3B0Y0gydVJkWWNoU0kvTkhuREEKLS0tIHM2bU9TVkpxdEkzSUNGaWNiL2xE
            VGFVTGh6WC9DcHMzSGlVdGY4eFhMWjgK1cuuPSvVYSOdxzNniF9dJ+sYqbMZQ4tF
            jIqI99PDs4PP0LOzspWvX29Vr+A9BbOnskfWgnuuZ68wwFzpZVNu2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T15:51:04Z"
    mac: ENC[AES256_GCM,data:6IVBV62sQVzdI5jK/8DYt2YU84wE1ijaD58wlmNOb9s/+VU9Iu06ujhfuq4skpXnW1bgSBupprHBkcxm5nHIvv4K+yha2Nj+9QYq+9vpczmFsxD8nZ8NJx5B2Nf0E9Be2dcywQyAzpzi3Qq7+KN5RG5nP+iFyaQgv9GM8IKVdtA=,iv:zvTTUUIXDf3614G9CaPZjFZmA3Sh9gDq/H8iKI2kVsU=,tag:RYYodA8L5Wki3VG7YNnOkA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
