apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:I8ibRJibix8nblt8omLvyJ6McG9BjnfUC7prNIW0O9w2pUfuJtiTcgU5tet4vtiH79VMZjtzNWBIsod/nddYcslApc0qRnqbCojLZX98xKv58S868rKKmOoUZNbS7PpdpkdcldshOSz7ctVzU2asiEiGTmYNslOeb7FbzAzphnuvZCVpnl450+6ySOWMdr0jqIXRlSXfaJTfSNo6stvLEzq6EciPlAUSKdizp7VZrUAdxITEp0FCGxgiVU+/0ryrFd8OMrBEHt7FIkSrbASqUbByIL3uPY+r6yeW6DmNo4Nn5lHyKJS1exETf/80OFa8iQYNcyFPStR6flVnOXS7YVSNA7TuAfHcn/DY0pitEm8VYIMuOYkDnZl+yNYCdBLM,iv:85dELuUnpcJgDKHVGIRv+OkmTsb/zgIsJjq0JavVams=,tag:uLuNPzlqEaxgwSkkyAL1ug==,type:str]
    identity.pub: ENC[AES256_GCM,data:KTUDAK3CLmz+1cym8iWbVaFN5y2vmz4TqPj/ULqbp4Zb0B+WAwcetIUHXvwgoCrPt56nxF133vs6yJNI96ciK1V3r4jETDs1Wd5x6A9zhC9Ejf+emUENGKxy7WUwgx5npcxd4xLPM9ZNZ5cgx7F4OPxME6VIyzSBhf/jh3aa4EVU9H+5wEXda1TJ9daaZC69XxIQI1VtN2vboOL0m0rkT9yoa8WCowvSbB8KMCXrbu9CXDBAhPQCUnLF5SAX5TK8KKByzk58JyuSyi4otw==,iv:p+xdz8oa9PNzRLp69FBoa9LakcGV2NJQkahSaKu3cHU=,tag:BPfHVXnOfuLYIND+ILdFQQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:4rIn6i/sBhOu3+GI5rw8yz3d2j+VKGlZ3usImEaJFmxSmND8/XWYzng8EdA5aiTNTZRhmGnkUYGODaRXFim81waAwkBXHCj04UQp3Se65Vmfdja5B3qBxdFdrqTqZnQUNVPiAsStMtpo+1aBDB+cleaydbKpldg7Dxjr+YzfYE9f8KewNaI8mE3tbPWjGiC5wmkzklYbMeSXSQklVsaMVn31E0NWJGgS5Q1p,iv:oNRB2pOyS4LbjPEDQ2R3bad0P+W7dbnAWwk5Vs8fN70=,tag:EJoItP7Sj8nHsV8buZj7Yg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5reegnllyypk4t5522yvknfddhnjvl6tvqmjfzmpc7u9wdfrgwsxqutxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dWJoa1FPQXRLSmZMNlVN
            WXBsa2hnQ1lLUW1qV1JwbHBIZTlRcjZVSUFJCjRUVzBOWXRoM1BTN1ZlOU00T041
            bmlNY05mY3ppSGplSklUZkxsOGpXK1kKLS0tIHJXRFN5K3Z6K3ROMXhkQ2xrOFRT
            LzQwSnIrbm51cHpwR2dkL0IzOExhQVEKYISR/cz+MQ/VB4PIwskEQxtzP4/91gq+
            fKoVKvqNnQuOyFmr68AXgyV9TiozPRJjxeJtKDYoEQE43NjsXwbvtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-13T22:28:42Z"
    mac: ENC[AES256_GCM,data:Gndd71SdktDm4Q0pDD/D4z60bAJxOhT58Qt0rO6FmYy6/Sndnvhnv0UktBF/IMd/4h5GTzL+lt2mbsIVq9ihvbGS/T4L1YC09m1+0S/8+MgLppxM3CuDT2pD/K2+FW4rFwKRgcBbJo4MW5BSxS29ZVXsX3E4Z5z4BD3qOwvoXEc=,iv:FBe8MsxP+ZT2A35xkC469cFkYkrO/EBFIjQ/jeTHF6c=,tag:+RiDvV8bMBNAj5IEyc1spg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
