apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Qtji+Zzjhx9/MJbBo+2dMB22MFsxMlUS/4yFpWAo2Z0FdlPzFFeEjwVhIsigbr8CkYFPf2JRwIkX8WBneV2XCU/DWZhNXkq9rsDXICyBhkRwwAXrX0t/1AfJhSZUhOsTNt+0WPpZF34Ykw8DR2lI8tWAGbs9KTNV3yu80e1hRGo70ffc4ngAdVRdvUp2dc91pylGz7wtnmPIFOLcDFuJqvqrODRlYPA60pp2CcDqcWRG0+v/sJgNjwYW8wMu7lKP6ki2B4mPmQNzbKapYUEgc7JcYxLdoRgG8O/FjiGFuiqO5m8pYhjIJ1DFb2+2wGa9mFbQtyr/5DunKbkN6e5lsxhbJPDTCIbITSy4prIfol/SZShZU520gEvBWVqJ1fsZ,iv:RkCbIf0i8lrwbPfkM4+hiGP8L3G4Y6cvkdEA1ynB/50=,tag:ScTNU0P47BRxczp8jqJLeg==,type:str]
    identity.pub: ENC[AES256_GCM,data:fkOTXrYJjst3KxcBQgxh08QPDlo0EVJAh4Cf1A/nOdYrW7xJlBcuDM9opV9k47opkfo/X21yzg218YQ5HCqPj36F59ZQfHarnDWwuRbwcwKMkoQ/+Y7XToZMUgegV0ybePvPWeU36dBgdpr8WFsfSk6SVxY1yqGNmaVfqCXG0MmUBb400D1aDNgHWZT6NUagy+62ifC5wwGbAa+h25bK+mwGUJ2oxCdsePmAQWRswb11t/ANacTz0LIlnZ29RrMkNmrO+jGQZkzuvVY5NA==,iv:P2dIJd7OsQCA3OedoF1+Iiyhaabxxii0gfk12N9HnxU=,tag:EIi8PWuy9L39v/gbWgs/7A==,type:str]
    known_hosts: ENC[AES256_GCM,data:qHbPM6b80CLIW5Q48My/tMBgdTEBCIDV/0im8zs2WTBUWdOrex7YDUs/rmi7abCBgtZB4FZPhTgo1dhh/9LfH4BmNQMkrAyMyq2sY6NslXY3v2vOp9VsUw1tTKEsYXiHHkAeIzt35u4ScG5rKTKDLUiUyKptCF1qVXm87lMeQUIVVPggK/l9yE53rEzxnNQzixwAjR0XBcQVjCbl6iMM75zHG1eMrhVzO5Kj,iv:Gr7+YoAoGYCZltmgpGX1rwN3/a2tBWFa80bOKCkDJms=,tag:AJ/ygNon7AOwCHA7Xe8tEQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUjcxdG1XZmdJMW1aWVNh
            TFNCOGZpL3JGMmI1Y0htbjVpdTVsUGdqSFhFCkw5ZTQwZEhla3RTbTdPVU5KdmZV
            STdNT2dwbU9rT0VueXJrbXJDa1FtdEEKLS0tIHRyTHV6NlBXaUI4cWFRbks2ZnYx
            NXF2Vm16NHh6ajlCc0Q0TlZtTzRjV3cKpOq0eUS1H984eRfsgDK9dfck3fqh0VYH
            Fg5OZvYG72v1QTK4nuAmXJ7tBS9pii5CR1eG5P01H09Bpe3KeX54mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-01T13:35:37Z"
    mac: ENC[AES256_GCM,data:KsSgr+jZHBp/FxBoxStQ7EhQJB3wlh+2SImMJv5/e8Fxi5YbtjT4PXml7qAMknqdBjUa89KYwJE24H5ui4mGqsl7Gsj7soRyP0WB0UWo2cK9NFXPDE//8uISzAH2xLg645T31I8pvpr3Cj364Q+uhSRzQIrwaJtgq3JgrrgVLLc=,iv:/ds7g9FRguxy2CEik5e3cS+sBVZjs7wsq/7+FE7ZsWg=,tag:V7YWbUSXTLZ1V8C5XXYRkg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
