apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZraF1/xa5Ht0e21evO4DK1QM9ONQfRzaet6WJaddvQyBfsqSqD9SgT0LsEDGMOeyAWdumXu9uoosKU8P7KX82sJ2nKYb+cdKW4I1MaBgftTlVc3Ik3aAQTO3xDE4ryNcLKcauFhizQoq6U+5/MqbIYmvPHzp4E5/ONQ6mzZjs7xa5d5TBvHsGRHRkD3I/Q/Zj2NeM832PYZXImpco0ZEYbKBjEW0zNZbt2MomwcM9tpFA0MPaw8etXxQ4lYWSwgjoq4uDSbe6XIfEQbg8HOPG6wYXZNNqK9P6dgn/Dsk60XbG4EsgoPF9W97S+OjbBu76bp81KG0e0FrB446Gk9F3HFwijkM4Z9DH/8fWOoufuSBDLIx3tUw/+XLlFonEVWt,iv:EgRDrZTklRU3749OqaewGyJo/lLVmtqyPdNhDQdaitw=,tag:QjtonJMpcGMAequxPay9VQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:MTBK8cwT5nzuMyiik8hF2sCXvmsAL9elZwxQItFBwrBYBlat/nHYlqlcsPlWFIdZm8yDvbd46mO8yh0b4dNDlpi1Qkf6FZUDsZcfbyBPVbbs5lhReP5TzYNU6JMHeN+zculaeKx9hCRXrvwRrx83n/qk3xplbiVhsa032eL5L56qjIzgzRALP6WZ4124++iu8R/xSZh5cairaUgdNHmNAE+IVmM0iuKZXNSib2870p5Gxmu9br1o/MYjDre6r6bQAohbpxWcUWqG9cSkAw==,iv:aCYF2MpwXv2dfuvkcfVP7Uc4LnkcKnsTdmPlkwP2aoc=,tag:MDFHam5vy2e1WRvAt1UAHg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Q14psZhNhXKt1M5AQo8qzsy+tINiUti+oB2YYKezPKH8pBeQiXP03EBIb413XXP/c5b31szU1ZoMqtupddVSPz4gFJ6l3jdtii7ptZrOnYFkE8Fh328oHIbFD6eudViA+J642hKLijIvb6OEyZl+cfdQkVr9qe+IDKOVORCUbl9oClGJAyuCYIn/Ae2fsvtOmw+0uDTtVP3TxHRKzxqg8yHIdC2flCpLzLx7,iv:lR0qIi7fuOHLssgPSgs95gzakSonbQFHG9Rg8ivka8E=,tag:Kj0bxl/T6lqrlnd1i7pF0g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUTQ3QzJNYzJHRVkxTmJX
            RWxUWUhTNmREVTVVZDc2eWE5MDRPSkRDbVFZCklJQTZnSVJnMUZsVXRHL2pjR3px
            NlR0Q0RWWDVvQUtiWVdmWDNrVEs2NW8KLS0tIFF3ZUwxM29lT2VGQnBjYXp3Z241
            VW51TVRYcHlvTi93djdNa1o1YVpXSXcKekH6n0xsExK4V5PBvbC5jVgFYvy+Rp34
            rCSUZuN12kNGa0mTriielfX0X8ex9o4Qkr9IMplr0846mywgAxc2Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T10:26:00Z"
    mac: ENC[AES256_GCM,data:dDpjmNOsOi5HSt+epLqi5v9zULBHXvsXZTH3RgUefrO//pYz0y0ILvOds/UcToVhA0SiydUj8gzO0POEXuQFfG/ftVHzLFJEWeAoAMog5daY6zoEZoNh2RfCLdzcIvKDDtwLmRDvgjqu1qGf5ueYo2Ig7tnjpJnmqbxO2aUb+TA=,iv:WaTVdZJ6QiIOSRp0of+KjjaUb5l66/55dX69tAKTBh8=,tag:1kzkI6VdIsGYig4QYlY1DA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
