apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MP4K4YUEENXqJNlWKSfx6jIaIR147tfow444FAFJNy6PfNEKEaYUU4nQg3DZGJuLG/jnQbSR8UTuOB6ukdL1F2vjuwQllusxGjC+C1fLz11+ZfIMKjaZHjhYJh+oeSeqipYyiQ02BWZ60YQ6mUqFaaXLjXnkMM1P7uIcovIFCsvlRZcIKA4QeTscpaQd+VbiH3pyHS6v9lUVB/zOeysCZ/JwpF7GMeqtxpJ8alpjJvwbpSFLPk6VTrMDreH2JmWTXZIGV1wmAgOGqVuZClfxqJSfFHhuQD4rjHapCKnXSS5T0IY302lT0FK+zzkSrJNwjOOOGk2rJ3E0DuYmny7Q9nfdglnWBmIEk2/b1YQD4XFwZYfXF/WTpDFAZn8ciuYW,iv:bj976/oAc3MyT3uo1a9ss4tBgxTkUfARfXZEmDva3gk=,tag:SDlQLHvZbTaGbneG1GIl8w==,type:str]
    identity.pub: ENC[AES256_GCM,data:AuA++KmasCD2vcsqE0YTaFORn9kiiwejrxiRQI4laSBnY4wNkq0F7uiSJZ+FstM5gbqhB3LYx1DrRbodqttldEPnFlXovvPvD5DFWBdTQ4+ojescNUiCl2yNu1Os9DDAnJXtgbcyZ2V4VjAjOZRB0y0JU43+gCn4qXlWVswX3kd7Il5+c1NazcJygc+jq+/VWg69EvfCIYD8fu+nv0M2odFv03fqqfs0NRTRZIVxGcNbLGGsd3mbZ19V1d6sU96gXfUQ1JYIPWOjV9mI6w==,iv:Ba3dxOvHHytw+doohjlguOAH6JuwfgECxWu82XOvsLo=,tag:BbXHTmNaAMQzOSuSIls1zw==,type:str]
    known_hosts: ENC[AES256_GCM,data:8vY3NpmjprL6JK/BuW6rDJ6719EEOXbSj6fQW/KCxdNer0fB8dSFkwR1KEjjqZk1G14l2tCMbGZvfon2QsuCpR/H4B0yiLvaspOAM8T0d9t5zJTDtaZcF+B4k6MwROkRzrT0gQKBA/8FnwvuMSPBLRmrLTbJB4w3ntkHgZYEMn29R6xNk1uApolPYenNZLwRcSp2+6JFgc0EcLbPV69pvqR7sJqyW/4P9/DK,iv:WrBFWGnwMIwiHNZG2XB5rGPKxcdBzsXPepGpp/0UDfs=,tag:1UA1tRlYkojHkj+PYFr5Dg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkKzRUZUhwNndHK05FRG9x
            aHc3K0pubk1XMXB4UG5WYlJtL2lycmJ6UlhrCmZTQ2VaR0grdTYyeGRDY1BsQjhT
            cUQ3KzdpOHlENmdDaXhWamViOG1nN00KLS0tIG8rbEUxa1RyQXVyYllseHZ5aFZT
            R1NWTy9xdWJKNEVmVnJZRHRNdksxSUEKyN9IViRmwPeViDIsYmi2c2bog+q8tC+7
            PbxnaM07/XoJVqZNQNJKXPdVR6xxCevZICnuzv0eKotFqZjpEmnfDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T20:43:46Z"
    mac: ENC[AES256_GCM,data:t8I0yYDGLPAA1Z1UgIrfSdutgSBd/7VFXntRPkfwVEnk0DEV7wHjado3Jc5GMZNoblARfxa6cJlySy8NeIAcC04QWyAPTBhThEptjL0Q1J57qclXt5+mGukfkiUvqqK/4RWOLV+3uPvE8p/k0inJ3aulNCvQzvGa/cWBYnEDfl8=,iv:wq18S6gws4XnNZJvCWXXfyedVemri1twDsoYTddb2po=,tag:GtFUD666GnjR5X4IK7WmHg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
