apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PPwkggd3KS7qPuSj2z/q71NoRRKeVF4IyDUx+RlkIQE/uxMZIMrv7rzOmGMbYw7QVKLCu5EOVBJc4cXK55WmtdgEArWTR8L5DA2Eoy717mp48/i72u6yYUZlzojOpUcWuCpDThseJcqGAmv25W9vdIJirBZyCjvHEYCtJax4O8fCr8qFXzi0tGv5UbkzrA+cz9blO9nRKkHd5hoNKEohWS3Xe4mSNCqcZSQfVae1/lJIqQE3sIumPH0qWhm9fSuMHjOm+tx0Yp06xur4XHpMz1SyUll7VuQ+rYVQht1urkG0YWwN3UF8Q25RfrvDFQkbCD/yHgWqa2FlvUCosS7t0I7s7WFfwKRSMXtk6ryKCZ/uPVOPA7ggpTCdHOJyRNie,iv:tKKN0UsCZPzrpIdBTdJonCfZEVhqI6KF7SXPIx0eKhQ=,tag:n9xHtVZDmmhLLC1MUavNiQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:PAgapvjiLEvKeNikiBgXGD/fkhAINVMSR5HP1UA2slpYtMkLOlR7qwM21KlaSD88hf+/skZzcinz5BGeo4iX3JhtFw0gSTqynu2HSJxgzg5yDL6DL7VczWYVKwzTXKZ8iycFHMfw7DBOiL92TgayI8GbB8xIxeVrTK+Ez/L0PfTbO0SIdm1EeY9ral6de6h0zYF3FLmMm/TnicuPKuk25+qOuMgEIWCvXvv/l0cig10qMqF9a5/f6HvJ4Ig5NKAbFiWWANIiNSs0+BS8kw==,iv:3fQdIUATfaorYaWKcStmaL21YR2RHHSX9h/IN83uU0Q=,tag:n24iMlyNFY3jdO7cuMHJIQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:QWmCNmUHuDAyfwoZc/a4I2LLoqGf+5zAz1GHBy62kNEjgg1a8gIk+RH0WyQ4PM4Y2UEGwOmKQinF6etlkVy9BvxWzPqMLD2siLkYx9/T7D9/E+l3oKEyAKD4vOSG5VjRF5kBaTFU26gWHBCOWOPGhQ6SFQvwwpgblIlZQbBGzgm4lr8lGCoNzURev0tKiyQrSrSUNZFo26Jbh2kbf7h73YVXYgB0ygi2+ioE,iv:lrYNRGS3ezBhNU79F05jsozrPhvpUo8tFnCLXgu6B60=,tag:S043mDbtVmA8UEp3K3HZTg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbVBHWlV5NU9PVHFEN1I4
            TFBCTW9vOGxxc0xnNGM3NjE0RjZ3dHRHUkVZCjQxMkdHaFRxMkN2V3phbGh4bUFZ
            N2RxUWs4dXd2b2s5NyttVmVtTW9nMVEKLS0tIGl6blJVNlVZcGgrandqVFNHKzJ6
            VE1YTWhiOEJ2NkRORHFibmdMY3E4WWsKBg3i1HpbU7mIzrlN5RWPLjdBMuBULMUX
            iHbEtU49rOILdkP7DCiMyCy/SxA7qOVPiM2/6+bZj1jzesGmd8jwZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T10:33:46Z"
    mac: ENC[AES256_GCM,data:UUwyFcU3iQxjSSPbb4em6qO1Xz8Kuz9quq6HjwAg5dkd/hj3HEi40ALa8wj2eXVpBXrlw9pgYOUkkI4nXdmJYHfaAdan7uLEN0r/AGLVbYzrTqOkbIpbJjs370Qu0bys0KLuqh1ke2M8ssZViLqcarniA938juyhPnZ/yAao+qU=,iv:tG1VIBOudfgaOKw4V4CmCr8oFAE9rHCX7UMNMEFuSzY=,tag:sgRwpki5tnno9xUpwkq5Ig==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
