apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zdRVibv5piGikb5D2sevX7c1L09xQV7NnuZ0op/icxzbpRu3ut05MnmMnkksW16YMRC5QMSQdtDtK4EkqBx3UvYJKOLBfACTkZsdd3SYjgzueAnbZG174u9jzuc4ERZ3E7VKLegw1P7PE2wc1ohUla+V5SaepHJ0KmT+a4nUda9LklcKxQRQjSUYJ2sNTXm7DcbDd7luy0T6IoXFsD58xdkv2aZMT2A+xg1K668SYi2hFj7B5XS0M5qXcpwIzFQYiRwMetOEipfd+/lN1JXgzARkRYh+VQwaNvqdxo9lJHuZC9aGeBlamnGvF795fkf1V/R1R6HxT2J+/emnTUyKLFtNJ/J8AajliRS8EkWaQeabrqTREc7aegJoxjBWq30m,iv:4/7BCjOz3w564Ml+9r7IzYMisihhpypoeTLMr+oKD6c=,tag:vPTmjKHLFzGoPU68EaguwA==,type:str]
    identity.pub: ENC[AES256_GCM,data:6y7AlgV9Rp1QZMZNuD3Mo1AeQXTbURhXLDSOFJ8vn2Wb1/1Zkqmo5fmILeVdnIOJSBQ+VMpGUBZSJVlgAu7/4Y8mDhXUCiq0ObYw/XDqdn97Vc/QS4DjI79ops5wW7yyXzFumbdcLhHkfAVustSj7lXGrbXh6gpldUkRqL6GOrADo8smC638TucAolii0zaBk9W4yZsTyJp0p9HeC6qD3Q8OewPtQ6JzoYqk8aLaD+qRe9LO2N7Qm7/qNAxOuXAXG83cxy2xNQh/RWlKdQ==,iv:Ag3fp18vH9Y0tqiOm8LqlBfUjdQYsDzHo2SwSzeCD6s=,tag:im0pVs+h5Wx6EXpv1qUtTA==,type:str]
    known_hosts: ENC[AES256_GCM,data:xFM4kIB+ul4K47NgPokmSf6MjjGl7M4yIC43+Cq6GdQnc8hzd/bLy3MkPieGERRXH75KVdLFZbijoQgan7JIWzODNJCACsRpnmnzbotIG8jxDaN1nfISxVrl8jT8jOkoXRJ9PHq46Y+48TqM2UmXe7rbo4TPQgJHmPmN9AxqLPAlogPH08f0AMWk6SQIN9QGQU9Rb9XKJnjXxaJzCmu/5mDh35Eaxoy2TvwO,iv:r3UppApHZDIp6ZVEHi2arTKJTCRhr3olfFYUwqXfKkk=,tag:zwe7LsRK4rFECqdQrco2IA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWlR0RGcwVTRSckFhUWFQ
            akxXL2RpRlA1RmJRU2JKdXNRTktuTTV3UEFvCjFzSzlRMTBrMTArQ3M0cmxzSmVo
            cE9EcE5qeHVOU2tqY3NqWnBpdVNRWWsKLS0tIHJCbWRtVDJoaUplWXZSS21UM0pu
            Qy83TTNGamozcjMySHFjbFllL09RMUkKxn7j5nC+JmCLpsUFJ1IPFvp2p1PHFTSS
            hhm8KaWnG4f+B2QNFy0zm80uSmMVJ26L5Fdp8Dgowd5d5uPX1Vr/vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T11:21:10Z"
    mac: ENC[AES256_GCM,data:T4APEqhDbd53yltZMlu+ry5JeOSymPzg2oe3uVr95WyCp4c89sfPKPWiKkYWizSr2qkHQlrzT6YDTemWNy6bc4Re1T1asbYqoAWrrYKLVmhXNOxXBgLHZjSkp/OiYW7xGFt6yD07RlcHMG15O3cYvn9W2QfUNjKX2d2WzA+fuWY=,iv:A9jf9QhmfcpxJx5hCbxAKUca5wX5/YN7mWgdYohptUg=,tag:vKrE/wqvHfAglc1ed//ZSg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
