apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TpfSCJetc+ja98zb/EdsDHml8u7tZ8S8JUYNYLkRzBu/mUhl+MfuZAkKGQhFOCoO4iHuykGZ3vf+0FBsJkWebWHEqz+HwN4MBUCRmDCBo5+HcRtBJar08ebzUptCTmLCQ12qwhG679SBUmdXKVf0RgFKuBU6hpMAHb5I7ycYSQD8r415yR3aGPCni92bCNQqwYdon76lbKpENmY3zToAUwXV3+1K2rS9iy7jqY4hkgkjY8v8pE0GqhIJ0UkNZJXQufOQxabQ5zjtWmyYGpxaSP+1XpspfXlmoBoFWn60XnfhkbYRcmmt8PlyxE9jItB9g0cDQElVZR6G8A1mRMHxs5OP6JnEb8INH+xP33n3jP2yFUcX6s5hS/xGSizzovS6,iv:/4uhdlo89vZh69rQkLT8oHtKfvAGxjj57HdazDS/iGo=,tag:kZoYBp0u2GMwZPA1b2YfFw==,type:str]
    identity.pub: ENC[AES256_GCM,data:3a1cnVG6wdwHEjnf0Y52qPAVSdk1jISBZaIFMN8MC9R9Kn4pCt5fmA8OHX5fMpsv/cAd/HyMjGjXhSb51qY8DV9mFaszy/kdUE34u7ZncmYK1+LBkRAk8/d8qZzoVeVW1AF5uw6/f7GvRJbhldxjLaDWkANFaekE0xTVqcorse2Gre7FOJIgFvXNAwMU0vYf+Pu9YFtJEYDsl1XKdlcFYey+EeYVa9rVcMkvh4TIfhvsXfo9upUo7GlLK2mPMpM/kZjtkKI0HQCt+AOlvw==,iv:hq0iiW3pDt4vB1ZVdpTeZnc5CkNaEI8t7pEyTx7wPHM=,tag:VbNrqzcDJDsoTU49adMtTw==,type:str]
    known_hosts: ENC[AES256_GCM,data:YWHhOc4nAlGwc0h+qs9VAHluxgc+pO8QbAdR/gKnYpUWI8Gr2eg78fl/kPrWjAJblgLYqKitAc1FaTIMLd0drg5vPag40DcXcJXOmfVHUIvkgOP1ysxeGBaD/HEWeUK89gtDs9rpLf8t1IGFS3oXZ1MCECQQ6rAxKDOOgve5ehwzv7FO1cuF6C9/MAg0HlgMa3N5SMFsI74nwWSJZAXcEQM9daCKn1CdhI9M,iv:L/xQfcIdkPnWPeQ0fXWcTeF8+4+YJAT1eyULXsA4rzI=,tag:35o6T2o8V0FlERlxI7Trlw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S1Q1WmpuVEFSa3dSYnhU
            VmNiN0wyZWoyaEQ0a1RYNm55T0tjMmRHckg0CjF5RjA5eStzcmJFbGRnMURBZUNH
            YXp5RFE4cUJxeE1YNWc2L1ByUGl2L00KLS0tIFJqc2FDRHczdXNQb0lQS25OaDFk
            azhjdEkrdEdDM2lDcWRDSlZ6TG8wR3MKcm777elIHiQXMRBzCKsEA46WE8uPqWfh
            SzxFAz22CS3INA2b9V/fyiCTZScxIXr20mLPxjL6Sym96O63+hNT0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T17:01:20Z"
    mac: ENC[AES256_GCM,data:rnejukTC0h7gpb1pnY8JVmTTZG10+5J2JCYgAjqwmJsPfLwVQp/kgKMLE+FK24ayUddyQnaJ9kPHyoAnpjk8PO/Yi/OvbdeHgADaTLnQsHFFYHzwUA278GqWL7bRnmP28EOUFPatJ/kETlCt+vYHIBn+CsLEOR1M/8iPVT0Ieow=,iv:fiz/Zy5IyAGsrgfVW2P2PHnUeOVZD/SwEZNGRoBBZUY=,tag:9DPrhz1RhKzOX7P/53TASg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
