apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ROa1TJyrqW5Mzy5+d+2B4JX7scsgo24DTx/TwEhfxXh2lWbdko+6qOmt1pJ2Rb6ZYIxHOc2E6wEmPVaEkPAgJ/or1Xpedzfp+zdp9emw4eYWL4QcYNTwO7037vixa1QxsH5Qi6tNwb4LM3Pt4vnXyPrqII+IHcMsNbE7oVXkpMVdUPp7d3caeg1WeazB8RYjhrnGDL63Sw2U58qJesfOnHffW/VtEWsN7FfxFrsxAJJIFoIUG5Ov5MHcILb/fQyM6vx3QCn0UlMsNuLJhFWHNJq21dB0TKq6vlvwaN7XCD/wT77ymkumX0rxY+nl6qUJVtHEmiPfdSQJdt/ywZYUBWeKr01hWHLw743nD4L2AJCvZy8PCKb32BEUiGpR/7TA,iv:Ao711cXRPRp8ingqiD8YM5VQB5C5w+kCfs6sY33cdGQ=,tag:utfz+mqo+sORfsvyhphBNQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:fpxjuWPxJTn72UC8PBn5ocmqDyO7+V7HxuD4SINRjJsq2sFkbNWdSDIssbL/+Lcy3qklR9lj8Gx2BG+/DkMJ5DXdkzTq5fMirA/MfoiDQHLLXbTIPk3szpTyeQqL9pxitEE7pWDHEVp9Y7G1Eay5Ito7F2GeEekdd5h37354llrQbSBNVVBp9pjiMdLG4I5RFdln1sIe6r7yLcb1gHNZWP7lyL+D8kgu8gaogNWQQhXsGUI+REI9Gc2oBoksXE7yIMhyPdNrq2eMBPCYbw==,iv:cpRy5/v3zpa/hq+CMTW2IBGl0VVV+VmBPZzYq9PbAQE=,tag:TckZbccih5VRyqeiZZx63g==,type:str]
    known_hosts: ENC[AES256_GCM,data:Cq6pLib83LTZgf/yQ8gj10LL31IBGbKQdBv0q+pOKs8Z8cuU2LvK6SNvKfY6BAfSDqAyg8r8A1Pz0OPFPv/1GKmthV4npoUJArjkl3L23dl9LvbHJg1MAP6EM79hIxm0wHvfdOqTRXuI3ilAb4p+IlbOn8Kswj5w06A3xSE9w3RPATPL8FVo4avV0queHrLHRcYKsCPXN0dPH0qnqjtZrt4zKg1PMzEyrccX,iv:9g5tKSPRIBn/Zxuf/4YbDbuSWmlb/UouDyqwojw0Oqk=,tag:GJLarStBbH48ffDZVxVVwQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VEdRTUJuK0hmS2FDUjJC
            UE51MVZSbEs5aFdwUk13UEp2ZFk0eXkyaFZnCjMyTGN6NkxBZm5IVGp2ZklMSnJD
            aTh3Q25VVVVzbU9xc0hTL1lnaXpTTTAKLS0tIGFEUUk0djZQWjgxcG0xZzlTeGE5
            VDUybUp2aittNkNVWXFaTk5tTXQ1Y2MKMHj9fxK84tUug167yg1LfglAw5oUEkit
            noa/TeKd3bYdWYLrOkg5lFOYZLYDez9dMOZDrSPU5M2T81BciF6VGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T20:48:30Z"
    mac: ENC[AES256_GCM,data:WVv36yWT1Vil/6JkfWJIm9AemchBxY6TmGlE7DSGDp7+h0ejX9DLTXq2+ibGRv2hzliYMCA/iyN0C69M2V7ShhXm7y0QObiK/XaPsiWChddmkJXNwQCbmO6YOufRKsuJAD/gqU+p5dKTMIAz35QztL8GyXTgByNRD/1kMucw9cw=,iv:X1QqYzBGKfyEkUYOi5+miWX/ObcuAC4cTZ7SQFnr8m8=,tag:9ig+7ALSZ17rMXr3RX3szw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
