apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eBRj+kv93MDGicMPy1TH/hxdvw+q04qlsPTmgL5D5OgNFTTf2tazP7I4ihpeO1TDNt2NSO/WYf+Oj4Zxt/BA9pA+C4+TpxHDnk1eaiIrEKHyUDi4j/5jxPOss0qgLhNAh5PtOACe3WmxWRs2A5qprGuH55mHf8v8VrYBqLfF00mC4ytW1XWenZSx5reGKO/FHlTt0LMEcAbKOTWNMIL9hrhjAhQ9v6E6fAsVivcB1xRhFw17T6DHscr1Vw8FBkyd5IQUwJoLyW7xZ35HtOpFdYjgIGvVzaXNeZpjwbO7NWWJGWa0yuToMAb/wjulBbK50mBHb1MgEQ3qD9WDeRkChUIc8+gMO6TGsIZDZxvfM8ehxCn1xIfpKuAKze9s9Yuq,iv:B5l+Biu65rMChq0+GIg7V4R+Wgjsv20Hz5/RTNPPrO8=,tag:8LQyriQ2w+ZAiRHX8sngLA==,type:str]
    identity.pub: ENC[AES256_GCM,data:UzhaB7lQZ6RUYQeDTStOdEeXcbTdLGsc/5gitmo2oubrECKj42GGhDb3SBUzjnabKYA/XIf52lxh2PIjFscVZWWD32m57yFgEdNVH6Ma/43/u0fHwtmF0hCWQETJz/kgKmrukbTtMFdMcOk1eE3Y8moep6/hMwRY4Q9yw+R7IY44LwGIqR3rnEQgzWmXMJYlbinD2gkr4xDEOPQztxKFTKORCdWC5TJRPo7wM8gCzd0iUndvHlznAubVmqWoqwosU5FSUVo85Dv42nIVwQ==,iv:i4XYOf7pQpBXlbUJEKlgTlPbc+GnmJYq5n6h7FDlLwA=,tag:KE7wHsGoY+j4FlV1VeS6HQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:hPLtS/2689666chTDJPoc/lpVhbqf/yHQK/k2x3F5DajKi0H8mh7CklPrS7uuRjtfu6ya71DhhiHavieLG+I8Zeni0sfpytNeqZqzoHrGbDdUW5xNnHPDLiCx1YvEJpKzE8ZDCUSWdgQvwUArXw7sNBoM/DBZLK3SmElTgOBnL/mzkQC5ft0U2sTB3mwQ2NmDnKjifXYacrQLBG9R5rvffeR4Ht1N/wuNOBs,iv:5FeofpfbOpH7z9rdGw5ZYGD2AkqVjxHHKc5Q4tb81ew=,tag:jbxg0sO+GtTTKkdiW0fQOg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybVNoZXYrYTR0dm5MMXZq
            azRmUnV3UHRvdTI0MGxrelM5cTU0WlNpL25zCnBoc0l2WjVzcHR0Z3BvMjNHaFhm
            L21hems4UEZKeXZNWGMxR2Vlc3NDdjAKLS0tIGJ3cktCZFBIYmthQWVEY1lCL2NN
            RG90SXlQc3VSSWRHU2ZwNm1rTVFhNlUKdH08cavWcZVu3ygOE0fooMom8K5Qs6fl
            +985+RHSly7nF4VQyBVK3ipvLmS6vTtR2ZGNPssT8fvhiWxQsf82Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T19:34:19Z"
    mac: ENC[AES256_GCM,data:9iQgc/9Md6zjBgHvN+cFFztgsX8YUuy4vXg/RBqQ3QF0raGlSvL0dcxTTzkOFxt7HkcrIdJzPjsBbhoeU0wuHW/ZDPEVumdecu9bJfT38LGCX/vV3zxhqwWnbI8cRwWeGQc5xeKqro9iEvNpcgg+6wJ+so8D/LCWNzu3Og6ndT0=,iv:C8ZnmE1W/112Bv+KbsLcRWu5Y7YnQf/IlexnC0tr2sw=,tag:3svvSZHuAUvtQCMnXI7RsQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
