apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:c+cuJwj8HHaw0Mjq9/4+8Qot1TpyEvC/aexNevZyDTGThf36rXfylab5rQaTTfksJbse2qrCGz+QuC3uiOR7yu7pzEOPQk1/R+YWhN6ajDX3O3W4d5P0F0VnnpUsni6/6oziR6k9r8LMS9zj9bDYVB3VA8xVpNXQpKmog9cwtPhT0tAd7tHwTBBimzSYN6LF2GK2xPOXb5K9Fu7C9TugwR34SYJNLxV1oZw1PHfx+0xOXuck4y74IMb+t6b3E2KOq65NCcfTS7dKp6SgKzlWfgELti6voWJIMzEb764MGuazB/Vju5pb3LO6E5kNYZyvO0BDfNbo9XU5LzkM9XswA3f7a5ByCJQcePKjZLHODbfXIonB+Em+7ViXlNB/fOLv,iv:TmcPXCjdEifhTKeWiULp15tmLk3tDDRKW6LouyHxubA=,tag:GDoOLmMSmcRK9l5aRNXILg==,type:str]
    identity.pub: ENC[AES256_GCM,data:pYsmHC9zmMgEQS/Auoa5bs+sKKYvJbtN00LnOwLMhv3x7aCYRH0ZpX1MIA1mrkO0jLRKKqXxf+LTO8DmM8+D6gh5KQKt+HTewZLGl0O5k9OLTnPhyVU9aKRvmxROBWwNv0cP0HzCnZVLYC4HrKJHFtLtkCIqZRQQWA9FDtQrEHYFfyEw46r0U26B5T7X1sG4qPuA74bYtsHrGvadYKxWyPStOUF9fNtL0jv5+upR89Qby+Y3GHeXVeuOTQe9jrOOsXnCWjwj+mWaDpRSTw==,iv:p8lPy/G03xK9hd361rSL0hjQplM2mZiB0OQbUgLGRhY=,tag:TH61QpVoFG8FaebqItX4lg==,type:str]
    known_hosts: ENC[AES256_GCM,data:yTvYx6w/ieganvJkub68wjAACe5csogH5oJ3RkOKaYzBlaoi0m28DZk2S7MFsJiHQ2htbwWqGQb+numaA3tFlVIYDR721mGXg+5PSllfXX2RwdOlpc/Z/L+xMKcIz8cqLuDdbUKFstPRORAnR03zwWqhfLQGem6Lfcbf3KvAMnyy/RdJKBaRzLmeX/0+9041LSwP1YG7JbufCDYRAuhvbDp1Ktv1KjGhAIrB,iv:HdIycXqf6ARRx+fa26MYYAZlt7M4DH5vP2mBydD1X2g=,tag:fNFQ44zBz/H/f9fRlDukfA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRFdKNHdsczZnUG1SRFB5
            MkxmcngvaHREbEd6L2RaM1YyN3NGUFJPbG1rCkprUzlNcVIyTTVhUWZZQklJYU5r
            eW9sV2Znb2xXYlovcFJoZnFxN012REEKLS0tIHRla3Q3aU93c1RwT3pXNEdGdEVM
            V0xWUGVOWXFMVnZaekdVeUhWdnhFY2cKm6MTO6D8QTydIp47kwMlRRSarpOaO4R3
            Nw0f9TeQzynrEIjY5mA52rk6s75UaX55YDamoLQGJi6A0kqd2b4+Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T15:46:58Z"
    mac: ENC[AES256_GCM,data:/IgG0y9Ur3VXYQQyFnlJ+5rlm12Wtyb7iNx1ZLcTr0RCT7gHhq1qBPxpwQ/meypqyxyQEs0g+wr+VCWPc7lRqfsu6LeuD1JQ92qXgqd1kmHw/D+WkOhXoQgRRDX02KTZkxD9eyEVLwT7gtj+xOTheXGk4hTEpw02PIojzWYxPsg=,iv:LqoyrnzrOUEIZnmVngr8mb5DG0xqPD1Zc59U9OYLjw8=,tag:b2n4E+thNIxJ0FX9oaLVPw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
