apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JQKPNjLQDk6YGd2abum+33oTJTsQTp4pZbzrk0ooHuz4HtBEHp1CWMuaaUETQFHOy88UMbnpkn7nt4NQcS3HgkC+HyJpTMB2BCClPiATPw3IGGhhVZLK7bSUTBW64w84rmUINooyTntT7q5ShGxcM4lKRko0wRehZbJgTiZY3U14cbXwmVNnGbkITBlVN+UmxOihHYszb1rGbeSH8nmIzsrt6sL8HkQtYJYKvoujijjwyUQyD8lUQYpIy0Xf2Z+HQ4tWwJoewQuWN2MuomyQU2pZSMAIQ0GI6AKyBtztVaftjuMCwPm0QFkbBWvWH8epE4NiAwtw43/It+N7USkC0ZYzy1HIQ3M43xPHas1U/jDPmL+gJGvZeg7BFp2Ihxwm,iv:y8sSdY0kYQFKrJVpzqaPWKUHVhIhl6nKU324+Nuz9zI=,tag:ddLPGjxuWKLEUD8Ke4Xxfw==,type:str]
    identity.pub: ENC[AES256_GCM,data:YrxNfaGhGjNrGFGR3ptewi0gVHxexPNP4blc3N6uu3I++t1JzZctJEL27cwmn+D0Q6v1lpqdXBKMzIUNppsdWogfxMhzJ/fl+KeK9HwabzmoQzXFBs+ikNcYmn1bLEMZSiWIgJ4Fh/rcblX+Ru0HYjjxG9UtTM1g7SsmFcRKtLtR9QxLbok6g9nCkhKgWK89/LZETDqQ1d4EMI1d+OsvLNf37zKj89j8Nl0Gg819rWgmTJsQos+phhiARgow48EJUkOBykOjhugqC5QKhA==,iv:evw3rUvq6oMhTue+8fJVzPY13JXKreX0c2m9eytZdIc=,tag:7ZTD5lhcig6eLZJRDHMCzw==,type:str]
    known_hosts: ENC[AES256_GCM,data:SmEKfhOC7aEhhSPNHMnzhxIabfCksY/zI1TDk3OnfIu9M+vxoufT1XXcTCyWUAA++I1rYv7ibGghJv8abCikvyWgIOWYI3YhvCD2zqK1krgCW+b/04CwZfdQQAMsEvP8eMUJPh6A+wllmV67Dr+St47GH0y74gSienkgr28wOtThTtLlBAoe7qHIS7QcgjWGIj0PrAfIxC28ulhr8wTigo/DXsTCK4ZqPJAz,iv:hYcJVkvZYTH8Pklk6oxmjXQ52CYkn9NsV8nMk6qx5I8=,tag:ZwCbWjPnfTvqreVmIcbZ3w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TFF5V3RMWW82L3FWTktt
            MktEVi82ZE5BenVFeWdySjJKd3o0TG1KaEM4Clp0bmwxazlmSGV0ZEFnUmxRb0ow
            ZDBGckdHNkFSd1VOM0xTam5RbnlZT2MKLS0tIHl1cmlveldJZmtaYll2OFUwKzN3
            TFVXdS9iR2Z3SnJ0dDNBd1lDYWJGQnMKli7zNyNSUQUD8UnMcvOPvFIGGKyUD7ju
            ZQeRIqPmanJTopI6xc9NM3qMc83AwHsYC7BVx315OtduYRAcAnt78Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T15:41:28Z"
    mac: ENC[AES256_GCM,data:WUDyUReoTrOEzz6ZdfNR8y+NFyUnhdv/31goFbrfw7Ir36Q4mttoJEOdLmAFhCW0zxBmPCnQAmRAEkybIJM2h0qKvwyoHxTv6fdoy6UAOX5bFDI+eLdz9RPVuRf/DnZETiM1bAD63BQLqVd0K83dzsPaZmbYUBKgnlIHzOq5rsg=,iv:OwHtDG1BqAVesGTIvrr+HBtnK014Dzgm0CqNkZnESCE=,tag:vBYS0cti6zW3uj0u7Zj3Vg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
