apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:m9eJhJbeVvTTsIAXRUxiiDyd+NorwN4nlZ063GheihGVFF7CaHc5H4xPG03Qd1018ZU2cQ51MNfigvT+uUmlqoT24tczPBZbTuUQ2d4QrYqRa409pkuRH2xy2Wq+G6jZQnb6gskYp3/3wx+JKohiefkoAhrwEYhUJSD762b1Uo2WRqQFbHUBaNF0wDFvpsfJcWAxy/2AX2ROOW6tbs+0/xhaa6+c8zvlV3PYLPyRTNxwKskUDryWyYB8Jr3cDryYMx3xYOcDPBMsKAT9t6pZU5v1P0A4d4Rx2zvDB7FUvbSpzREaJ/3uYzc6TgPmoWxKImq6xkugWiUHbqd59/Jk5b0hVs4YfgvN6DgdgOjgQq3SMS6/mJ1SXX76pZobftxd,iv:1de/H5VOPNKF2X7DO+QZXcIIKLkM1vF5Ep0ETdpIqkw=,tag:V/sFKWB+Xt+UyrjeMd8h9A==,type:str]
    identity.pub: ENC[AES256_GCM,data:PUbtdvmsDOfvYOO9wVao7ZdSrHGm6dVWqAsZYs8xfC02LIfa/49xUbNISI+6AuuT5XP8BtwMFH3mCU+zgaKODH4IW38U4PmZdAOz9971dVflsNQhytjRTBg4ToSRsZCwYcjqn2mHa2M+nG4zgYIEb4082LhaK7gloJxRou24jZHbQdm8ct7HHgjcQfJGVkREEdDozznCz8rNoKttPcL5IfqAB+i1gGhSqGO5AOu9fxUsDDSTp+8YCeRUnxSY2PhGEM1zJKqNYdNEcsvzEQ==,iv:HUtKnwSozTjVCA+7KbyDaeTWP61HTE5BrjB2SQ0OEJo=,tag:3xe9L6BxMuapG2kobo0Wzw==,type:str]
    known_hosts: ENC[AES256_GCM,data:3yuKiNKbKi43Sh0Ky5DjCBebf/eNpPesGO312eGNMDP0Lh7HOMUuE1CW9lwGWEdyZEam6EHqSUfQxiLj+oeMx5wsK/sGEqZH6Vz2gN7MviuXIPSsrsW9UdxX+FHSeHk56xYC7l6yrU+AYQhPeWwRTcVLKrhR9vZU5FsKMN7LX0WhRQhpGmcbqflj0vKJhRLI4bip0hZCwZ5i1LzdOS79JC2wGR8N/NzmUXsb,iv:/gdPIZQRGuPMUyvOys1QYKINCcBooyy7TwVwVE2pVvM=,tag:nk6I8w1f55Pgd5sa7/wNtw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbmJSY3RMQzkvTlBBOWlR
            OE5MVVdpdyt0QmtGMDZ1RnZObEpQblRoekVRCm8weWVURFdNMUFJTkdnaGFVNkR3
            SHIvY0Q4NE1UcEpRRXlDbDF2TTVodVkKLS0tIEQyUUcxM3Iyd2R6THowM3h3dGJj
            dVk1KzFjWmlFSXh2YXJwRjZmMkhGc0UKnEph9yVavYh6sAPUBWFgPxO8HVWx7GZ4
            yISv+1Bs+W3SZ+WJWjwG2SCQSiCzkcQle+THBx2PChxi+S8rwv3GwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-11T07:10:25Z"
    mac: ENC[AES256_GCM,data:S+UrXhMszVPJQQsmLFNsOVTKKqpdf+o8blB0g5WIv6b9UKJZ/l22wy9/lmSEM2xlvc4gunE5sMKnS2vGmshXh6f6snTnrb9U833VGFXwnt+pYI6PtZX9bbQtnQ67IA7ut34Q4cX6OEh1VHjBcanvUagvYcs2hrL2E4Xx1cvAg/E=,iv:WplKGrM729WW4zqRUU+Q0kQYugr0Y8BVn0I1FUKg5Fo=,tag:t5pT0tFRWjDr03pyH7Zqbg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
