apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HWvSfxJ4/jXoZeiISMbapX3tBr8DsYu8SNkV8X9fbm1Pv5IEGnNKBUZg3Xbl8fXkuZlbBJS/6m2y+IkGILLEb3mHo/ioyRmPXKJ2oy/bCGXtNlyVD3XWfrqROzDQTwhuQLHhEI7UgvdkV8ZwdR94lpovdc5Pmf+r0s7nXhXclXwVzmFqByERhB1N9RAXdp6aUJJwBnTyK8tX7YkJctezC3mqMs7M8EmN+H6g4p81wxnutIU4xU9FTW+7PsutygLTkfS705YDJzpotwY7ls25A5D8XkFayn+mv3g1neBA5LJcuovUowWTrch08EUKvcYLTPSpWy4h0fYGzxmqCjrrWLjOKrpSDIpne/y+gyvslPTM40V1/bspqjms6oqoVhj+,iv:lzObW2eWxeOF9+3Fg1mWBm/PIZCX658zEl7GLShPSZA=,tag:+npG3Zm9b7J1xSkvaPlaZw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Qgi2FxNOyitTleHJtXNFqnCWYmlLCRTEXQ1rbM6mJF1IH0ztJ4rBgSXmoubGedibQkEu1FHEGujjr2Xza1wZcx2CJnvLAj4r20sCnrigwZ9UP/VqR5fEOWaQjd1WRjJMgUvamdzj5uG15+Nb05tQmsz6orOq7fpdOj5CfxKI2tUC0Yplfy7QF9D9nWZAZSZFNRnFh6NMH1lIrhKLAZ6xt3Q82rYAMrEYsOATLlyMOGy+xygl81TaGjzME75XzLf8RjL6QeN0S4oRyqWZpg==,iv:0AriBAJo7S49ZDDwfgThqRdAxhHO6+9Ay60tbvxpl5k=,tag:APce1kpsd7Kc7LPD3aw+2Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:AV6eH539AX8RH6ZwQVTQoUKlPev5H+mOyRDOgA+EvIuZTVAK2vlcA7ZHogRJCjNxaqNw0fGvr+CrCHAZ0UKGoj/wS7s/rqyQH0uqkWOnZ5NyL2u698M7rB/0fl93m36Ir+z39huBlPhShgxT1KqJtR8yEKPMkIQMPAa8b8vJ1WSe1t/0vpCClHYkSvDK8fr6Aa6dx0R4tZu7kxH0RQyQcfC8j32F5+6p11DG,iv:8Gj77Ox5JzDu+DyNdc1YPXRDO0bku8SM+lhWH0Cw9sg=,tag:st+6lVH/3aG71rMJii7KfQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMU3VXYk9LRXlydnJtdHp6
            d2wxelV5QzMxbTZsNHUwOFRLdzVpcU90a1FjCmVpM1RUdGRwalV1dHBFOFhyRll3
            cHR5ZDdoWkhjclNSQ1lLWGltSUIvQmsKLS0tIEhuS1paUFJXSkZrb2c5VlFxMy85
            TWJWVEEzY2NTTExwSHkrMnFQQ3RXWTQK7AAZBORlUyEoCV6vY9vBUEfJKvKXvxag
            UHjJgE6SF6oJL0VZCODD6A4z6WLCATKRHry1W75SRB3gcJc7uH8U+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-11T18:06:34Z"
    mac: ENC[AES256_GCM,data:FjxpUh8tabJ2Xnbly8fwo/rOeHKi3E5vryD+kC/kw/EWfIwlrFdO+3MISGF5X7Lu5DslPeuOK++mJHnuaPMSeIoOH2np4JmSxesiGjMNUSynFlg6AqP9YyNr5zPEt9XR8GJf40yrGtVoF3d01y0hhVeANX4f1mu6s1nBXOK0iKo=,iv:SwpGPpln294636PPHd+XsAI4u/YyhE7ONeuvzZZV09M=,tag:Rm/byCystiV+xhM0foQ15g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
