apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zOAKD7EVlmfea2WMMhJNuBTuIWhenSOqpMQdk5su6N0vlr1Y9FU1170cxMZA7d/2bLHCp/Nh/jKw6r9LkWg9tdOsQnDZk3A0IEjNwg8VfFV/ZlvtUM7cuCe+IuS+AkNqJOmC1Y7Fx8h+a4QE8gruHDG5yZidK+7G0YC8zd145iFdzOtcLgM4M4z7O/8IkyM8dxqj4VaTrBAlVoXCE+Vkzc//1xXiFfzDJKfhzz9R5f3rFOPn2JGiY2IIDXY+k6Auy2Lw4SfF3nsHaZ50T6gU5wd0Ui1A/w3tko4vdhsIsPj8HP3SwwKsE6RJtVkVQVt84q6BLa3il7bg8fAILYc6CayELAZYl94/rOx7ZBKU+o+ZZTSAnMYEjUifEicsCa+c,iv:ALipIZKUADrdqtUJcd9PY/dmMDise38gQB9fHkgaDrg=,tag:G/71tBiOpj8Jxr2+SvNS9g==,type:str]
    identity.pub: ENC[AES256_GCM,data:WbwyTrIwljCTCV1qdjsydHlBkOpTQlsAKkLNeqVZFXsYdRsLLr2G5JLwe+kfQVd/ogSMHQ524yp88kxKVrZX1ZHBH+9/TH0WOGfvfDpQE3KDa2Bv+V+IM1dtVe2pMbFEzat5guH45xEQTLk0/SbGejH7+FbgStRLr9UIbiBTTtGcrJJ4aAeNX+XfOQ+VSzNiRAmIKNzO7VarZmu5sWxci/Vn5sd7U10uo+FFczaz9Qy/NTi//s8pKkn/OW+rBEKJuJRMEMSmiNIs6+zaLw==,iv:QlHUUrK327remZvJSvW9kl1PXwg3jUHNr4FGK2YYMEc=,tag:Fp85UTTq+fKEt2ENVAJ5Vw==,type:str]
    known_hosts: ENC[AES256_GCM,data:POmhJ/sOZl99h/28uEdwPmHmSbBDXI21VPsmZ3Ac7Xj7PEdMMoyRT7hiOtbKpG4lTyNDJsagXxNwXIAGMtHiCbH4hfE9UXXyEWw1fiVQIwH5QyNQr0NwB6GgV1tYtxJZbXNvwRqQPytVQB5DW+8TGEczn5SFnw7zOxIMZz2w81jTfuvsAQcKECGDRXaMNEmuY2sSamLTdkRFSIcWk2maa95Y9/B79yGVW4b3,iv:SsNWQaTUwyJ4hzZgYP5XK+lYdE1oVjN27q7bkiYbFCY=,tag:0CLmH/aLr8hFVEM9BqdlJw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWlEyUGdmN3YyaGJMN3o0
            RHNSWkkyUktDUVoyNEpHWmRRTWlUYk12bm44Ci9Bdm1UOStEeWtYZjhMRXJvaTRX
            c0hUdWhkQUNJdWxMdzQwNXdjOGwyQzAKLS0tIFZvWi9VVW9JS2FrL1NpcWdkb1NF
            bno5T2tWNWlvcUtONUJBR3F4Ryt6OXMK4G6E/DUwAkyGjQK3ujpbM0MF8tBriwLW
            gnlDTJYSwXQALrpIf8xjTtgEMIvX54GhLW4OqbRkJ2wIT/LTgrFSww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T13:25:08Z"
    mac: ENC[AES256_GCM,data:bQn2Z2zLw3RggO3rtoUol2uAYcaDeInrt0LBX2Jj80imVvvIuWOpnIItEDQ00ZSX3v2QmQdtsd7EczEZPYnQnz15kyIsvcHT5EuZZYY61fbbVhmaLRySvkrKkSCMoFV1LUyWLhn3B4GwK4lfCT2CzEl3mXbZq0EZrnP3mOJ5tNM=,iv:KGcUXiJ0zKHH9+IpzE6tR9Ny3ZfAYawaCMy3MVPZ0D4=,tag:LvY9exCJBPdkKrlkWHNxyg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
