apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:npFJwrdkhuC7D5crdhMh9SaeIPTMim7ejQvj3x3zOr9z6Qha49q/j6KBTqfaWoBDpM/DstDPO2iUs08v91Zn5frpy26E3A3RhBGUCFSxiu5Gcm8Tl+Du1S3jPEk0DAWtIP+8lGfFVwthn+JQPK+QZfqqQ/jDB/RVMaeiEeQsHpQAGUCe4U6Ex2XBAl242IL1BXPJDUGkLrSBMhvGBijqkimXJVuUNI5aLAR/uSSg3gWIHCbJfrGMFAvxy+X7FVTlonxAvSEuA6w8Mz64iA0I+1V4CnefSp5VeFRSKYvmKDLDCMqIzzIx30HLD4WUbzoIN6HnmKr5dotOVb6y+XWmoAYbHyvQpEn0ro+hwk+vkRUYcSsNg3mZ4oiyiUplnsKG,iv:OP1LWJ2H79FrNlAhJeIJ23KIIhfaApxo81qmUfmGUuw=,tag:9DoUaHkdXaZnubtTisTIVA==,type:str]
    identity.pub: ENC[AES256_GCM,data:OJ7sMNc6DYhE2B6matB1UWNCobvAG7hbQR2yXvZqHa8BqeQzQkXxuuF/3Gi3pLmbIFiOms1sDNWOE0JKf7QgjxUHteW6bysoo/sISGz7ibDx6MLHJi74YvHZh6xn1AdwigyNBy0G7g5TFa7Yxhr4vRX2W6LscuXQjOxTefltux49qTAlFJVvMiLoJVz/7upyKy5ZwFyxjqPgm8a6rso6BIh4owFfaHKK7satcmq1Qn1cAJFGp16bVJyoqhkMhuTZanHcpjRWGmh6ytX/Lg==,iv:bKLt+g3mQIlITkQ1UKZmo/OBL1GbSI3keCF+vsjMWGo=,tag:qa/PdLkiikR5ApWN9klTVA==,type:str]
    known_hosts: ENC[AES256_GCM,data:hSc8okXps/QxRMAGUpaZAx8/Ze36nf95jW3DKfC+s+j8jG+rDfDR7WTax4UBvypjVJIIHGQjB8FYyj8YRghsk2DxFywRVPGOHR064IVx+6GYEffAObrdPsbY5sMbWprsMOxxrN4XXhT/jz/x2ZyLF9yNEzmcF/ZETGggFcc7XLcQJfKzMzAmdKm3mZSaveQlmUxvmLnLv+4z++PYslBOPVYY/cfEATeTB6Od,iv:74uzYyEghXqM5UzD7B0qzcoRaWimHWGhk2cDOc8EEnc=,tag:zVNuvbKrjUepT3LuPEu7NA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZFhFWVV5SjU3NGgzM2pK
            eUNhWlZsQXp2UXR6U3J5aUlienVQc1ZZNmg0CjduTXJTdmlOYmhKZHRkZkNxU2VB
            Z0VBODJoOXFIcW5qaE1HT3grZzZRRncKLS0tIGdBNmV6NGVBR1N6VWJaOUsrRlQx
            YnlRRFF5OTZ3aStuY0xmVnNDSlNJZzgKRmx34e8TlEisxzvYyhhErqsxHEuJaGce
            ehJ1CJlEj0RX4Exbc+0aMNVCODg8objN8IPPAOuJ1qVWNtXj//ht6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T21:07:57Z"
    mac: ENC[AES256_GCM,data:obaSMbfHbdLyUwx8D+HG4awEdSQ9vr+CCOzwIY6XeT63yaLpeQ8K0gFwN6xrbPTsnQgN+S5TfXU1jiUyRyDkn0n35iLPO5JkVaP6eIrQPc19KV4VaLh1cK7P1YLj21Zy19DFszO2wz8mnlfZZpYcpA44WcFTQTrkIxoLXXXV93s=,iv:StH1mLeY+w4E4um6GdmRLisfqjqw4Uxu3ded+nRuHwk=,tag:z1ov6dRzMiojx5aRJ6kYOw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
