apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:E2dsalmEf27R/Um84DmL0V8iKZV4jxNG1oS5QWVGOgt13rzinxpnZJV/b9ezcNJERbbNZtjzMWR5pFqyMNx0OCXyCqFj/RhkqSF3fLMa52PQpf0wpgnYRXTn8mLOExQppIop85sypzvjayHbqTPqKCKimeh1D2y1z7R5jfLQjrEixngZ1DCR5TZgSFjUAKd9wLH04eGKm/pdLNvXV7X4OU1ZE9Ji38BdF0qMGqHA7vZ/dsnwKHZsga+bYdUJ1HFx8Ad3grNirxhHhdjTA5JJcCiiZ92dDVtXQ8fsHbTyMWpcRslRT58+XLjNMFleVmZ7pWYSDkPQWrd2JhTMjCuRDOhUDuR+kNCb+SPNxaPaWpuQoabSVMFXf+cypBN736K/,iv:Xcjbzr4yioAKpmQ/W1Uqz2nBKqH6PavwnVnJrZ9FuxU=,tag:hZbKTdGGe1vpEcNryQPG0Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:vEjtGgFMVQTMCVycHhNapUdDTZ5I6x/wl9fFbjPf4I0qY8ENJW/V0Cf7XR5sulQSdTjYEwLEU3FfGuI3CQctIAoiqbDzQHWuF5jaud0zO6IRo0BK++2cwYMbpRplRiFJsTcjA4YuIHUMnoaiT8k9HhzeR6B4uSKj6dKtaNx5Sh32VJA8TDTmXgt3t7GFbrY3rSMkqLlJniSqfDAakPcELg8NfGeBNq3A/2vEDi21zQoji7t7HbEJ1I8oRhIoo+W17BsVC7hx1BvaCkb1LQ==,iv:ivesu58ToyPjgWj39icprdBzjXVKeicCGM+FUG5bAJg=,tag:GTCLEZDB2/m7/CgtnLApoA==,type:str]
    known_hosts: ENC[AES256_GCM,data:pijGZW7O37UPE+q53AGDqiOHvwgag5bNTrEe4mS+I2z3I/KdWagkBY7EJnrVz7wSeyDvLR8GmtnvYexeHh8OhjJgPF8GOdHbPjgI8U3KA3YdUmp7SloWpeccf/l5ww3PHdRa40azuf42yuAKKp6MmqRtVR+fgjPC/26FYQK1kqNvB8xI2RErKRjzh2tWJfAJ1mvPyWWdqmmT4pr4r1OWMb81eF/9NP16MRdu,iv:dgDNkrOMe3ra4F4MbNtGtihc42Y821irS0nYbZ/XMBU=,tag:yp4Hmz37nCztNLzNQHfP1w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v4h4mmyfj4lzu84ev74g2neyw60panc9chgu0kjpczntt6ustehscs7rev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZkZWelZjNzNBVVBuZVpJ
            MklxUlB2V2ZpUFVOdTRZTFA3aUVIeVlDUjJRClhBbm1VQW5lU3B5emsvZmt0ZWs3
            QWZrZEVaOXFMVlBqRmdLcDlJUkxuWHMKLS0tIDlwNWhMUVF4eXdoeDErUGVlRk9x
            NUtwYmVzMTA3dmhtV0tjNnZWeU9yZzQK7EoLJietUoZat+CyGoHRq2yGtCjZ94Up
            HzhkrCR0fg8pIswNxy32eTe4EBsRPXd0xqzo8Vsr2W6iXgXqBiivMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T11:37:41Z"
    mac: ENC[AES256_GCM,data:1I/RWmQdswiNH2imhJUMotyg6MM8qY1a0fa2RzMqFhANcSHAhd+vCmvZO7l7tFKY3LWsnPVUiVh0MvG722RcLKu2E4KLIV0FfB65u20HiFKI0qOVneTyKB6HH/78ATVFrghRJtPBnsxXc1JwToY50MiuK7EBIMUsVHc0alilSa8=,iv:Hcu85gh2qTL21hg1bR7y8lilbcYlBrPiF4eId8LL0X0=,tag:Kf6NPcXUyZL0M+Mz/2Ugew==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
