---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 30.1.25
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      backblaze:
        type: s3
        url: ${S3_BACKBLAZE_URL}
        bucket: ${S3_BACKBLAZE_BUCKET}
        accessKey: ${S3_BACKBLAZE_ACCESSKEY}
        secretKey: ${S3_BACKBLAZE_SECRETKEY}
        encrKey: ${S3_BACKBLAZE_ENCRKEY}
    nextcloud:
      general:
        run_optimize: true
        default_phone_region: DE
        accessIP: ${NEXTCLOUD_IP}
      collabora:
        enabled: true
        username: ${NEXTCLOUD_COLLABORA_USERNAME}
        password: ${NEXTCLOUD_COLLABORA_PASSWORD}
        dictionaries:
          - de_DE
          - en_GB
          - en_US
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: false
      data:
        type: nfs
        server: ${TRUENAS_IP}
        path: ${NEXTCLOUD_NFS_PATH}
    cnpg:
      main:
        mode: recovery
        password: ${NEXTCLOUD_CNPG_PASSWORD}
        backups:
          enabled: false
          revision: "1"
          credentials: backblaze
        recovery:
          enabled: true
          credentials: backblaze
    ingress:
      main:
        enabled: true
        hosts:
          - host: nextcloud.test.arneklein.net
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
