---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ext-homeassistant
  namespace: externals
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: ExternalIP
        externalIP: ${HOMEASSISTANT_IP}
        ports:
          main:
            enabled: false
            port: 8123
            protocol: http
    ingress:
      main:
        enabled: true
        hosts:
          - host: homeassistant.${DOMAIN_0_LOCAL}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
