---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
  namespace: wg-easy
spec:
  interval: 15m
  chart:
    spec:
      chart: wg-easy
      version: 16.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      stopAll: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                WG_HOST: ${WGEASY_PUBLIC_HOST}
                WG_MTU: 1420
                WG_PERSISTENT_KEEPALIVE: 25
                WG_DEFAULT_DNS: ${BLOCKY_IP}
                WG_ALLOWED_IPS: ${WGEASY_ALLOWED_IPS}
                PASSWORD_HASH: ${WGEASY_PASSWORD_HASH}
#                UI_TRAFFIC_STATS: "true"
#    securityContext:
#      container:
#        PUID: 0
#        UMASK: '0022'
#        advanced: false
#        capabilities:
#          add:
#          - NET_ADMIN
#          - NET_RAW
#          - SYS_MODULE
#        readOnlyRootFilesystem: false
#        runAsGroup: 0
#        runAsNonRoot: false
#        runAsUser: 0
#        privileged: true
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            dest:
              enabled: false
            src:
              enabled: true
    service:
      vpn:
        type: LoadBalancer
        loadBalancerIP: ${WGEASY_IP}
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        hosts:
          - host: wg.${DOMAIN_0_LOCAL}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    credentials:
      minio:
        type: s3
        url: ${MINIO_S3_URL}
        bucket: ${MINIO_S3_BUCKET}-wg-easy
        accessKey: ${MINIO_S3_ACCESSKEY}
        secretKey: ${MINIO_S3_SECRETKEY}
        encrKey: ${MINIO_S3_ENCRKEY}