---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
  namespace: wg-easy
spec:
  interval: 15m
  chart:
    spec:
      chart: wg-easy
      version: 16.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    service:
      vpn:
        loadBalancerIP: ${WGEASY_IP}
        type: LoadBalancer
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: wg.${DOMAIN_0_LOCAL}
            paths:
              - path: /
                pathType: Prefix
      external:
        enabled: true
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          cleanupTempPVC: true
          cleanupCachePVC: true
          credentials: minio
          dest:
            enabled: false
          src:
            enabled: true
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                WG_HOST: wg.${DOMAIN_0}
                WG_MTU: 1420
                WG_DEFAULT_DNS: ${BLOCKY_IP}
                PASSWORD_HASH: ${WGEASY_PASSWORD_HASH}
                UI_TRAFFIC_STATS: "true"
    securityContext:
      container:
        PUID: 0
        UMASK: '0022'
        advanced: false
        capabilities:
          add:
          - NET_ADMIN
          - NET_RAW
          - SYS_MODULE
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
        privileged: true
    credentials:
      minio:
        type: s3
        url: ${MINIO_S3_URL}
        bucket: ${MINIO_S3_BUCKET}-immich
        accessKey: ${MINIO_S3_ACCESSKEY}
        secretKey: ${MINIO_S3_SECRETKEY}
        encrKey: ${MINIO_S3_ENCRKEY}
