---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
  namespace: wg-easy
spec:
  interval: 15m
  chart:
    spec:
      chart: wg-easy
      version: 16.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      backblaze:
        type: s3
        url: ${S3_BACKBLAZE_URL}
        bucket: ${S3_BACKBLAZE_BUCKET}
        accessKey: ${S3_BACKBLAZE_ACCESSKEY}
        secretKey: ${S3_BACKBLAZE_SECRETKEY}
        encrKey: ${S3_BACKBLAZE_ENCRKEY}
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            dest:
              enabled: false
            src:
              enabled: false
    service:
      vpn:
        type: LoadBalancer
        loadBalancerIP: ${WGEASY_IP}
    ingress:
      main:
        enabled: true
        hosts:
          - host: wg.test.arneklein.net
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
