---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  interval: 15m
  chart:
    spec:
      chart: paperless-ngx
      version: 10.1.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      stopAll: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PAPERLESS_CONSUMER_POLLING: 10
                PAPERLESS_CONSUMER_POLLING_DELAY: 5
                PAPERLESS_CONSUMER_RETRY_COUNT: 10
                PAPERLESS_URL: https://paperless.${DOMAIN_0}
                PAPERLESS_OCR_LANGUAGE: "eng"
                PAPERLESS_OCR_LANGUAGES: "eng deu"
    cnpg:
      main:
        annotations:
          cnpg.io/skipEmptyWalArchiveCheck: "enabled"
        mode: recovery
        password: ${PAPERLESS_CNPG_PASSWORD}
        backups:
          enabled: true
          credentials: minio
        recovery:
          enabled: true
          credentials: minio
    persistence:
      data:
        volsync:
          - name: data
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
      media:
        volsync:
          - name: documents
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
      consume:
        type: nfs
        server: ${TRUENAS_IP}
        path: ${PAPERLESS_WATCHDIR_NFS_PATH}
    ingress:
      main:
        enabled: true
        hosts:
          - host: paperless.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    credentials:
      minio:
        type: s3
        url: ${MINIO_S3_URL}
        bucket: ${MINIO_S3_BUCKET}-paperless-ngx
        accessKey: ${MINIO_S3_ACCESSKEY}
        secretKey: ${MINIO_S3_SECRETKEY}
        encrKey: ${MINIO_S3_ENCRKEY}
