---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 19.5.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      backblaze:
        type: s3
        url: ${S3_BACKBLAZE_URL}
        bucket: ${S3_BACKBLAZE_BUCKET}
        accessKey: ${S3_BACKBLAZE_ACCESSKEY}
        secretKey: ${S3_BACKBLAZE_SECRETKEY}
        encrKey: ${S3_BACKBLAZE_ENCRKEY}
    plex:
      serverIP: ${PLEX_IP}
      additionalAdvertiseURL: "https://plex.test.arneklein.net"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IP}
    ingress:
      main:
        enabled: true
        hosts:
          - host: plex.test.arneklein.net
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            dest:
              enabled: false
            src:
              enabled: false
      media:
        enabled: true
        existingClaim: media-nfs-pvc
        mountPath: /mnt/media
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PLEX_CLAIM: ${PLEX_CLAIM}
