---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 19.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    plex:
      serverIP: ${PLEX_IP}
      additionalAdvertiseURL: "https://plex.test.arneklein.net,http://plex.test.arneklein.net:32400,https://${PLEX_IP}:32400,http://${PLEX_IP}:32400"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IP}
    ingress:
      main:
        enabled: true
        hosts:
          - host: plex.test.arneklein.net
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    persistence:
      media:
        enabled: true
        existingClaim: media-nfs-pvc
        mountPath: /mnt/media
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PLEX_CLAIM: ${PLEX_CLAIM}
