---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 18.0.12
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    plex:
      serverIP: ${PLEX_IP}
      additionalAdvertiseURL: https://plex.${DOMAIN_0_LOCAL}
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: false
      media:
        enabled: true
        existingClaim: media-nfs-pvc
        mountPath: /mnt/media
#    workload:
#      main:
#        podSpec:
#          containers:
#            main:
#              env:
#                PLEX_CLAIM: claim-NZXmx_pA1qsfgJFjV6tF
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IP}
    ingress:
      main:
        enabled: true
        hosts:
          - host: plex.${DOMAIN_0_LOCAL}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    credentials:
      backblaze:
        type: s3
        url: ${S3_BACKBLAZE_URL}
        bucket: ${S3_BACKBLAZE_BUCKET}-plex
        accessKey: ${S3_BACKBLAZE_ACCESSKEY}
        secretKey: ${S3_BACKBLAZE_SECRETKEY}
        encrKey: ${S3_BACKBLAZE_ENCRKEY}
      minio:
        type: s3
        url: ${MINIO_S3_URL}
        bucket: ${MINIO_S3_BUCKET}-plex
        accessKey: ${MINIO_S3_ACCESSKEY}
        secretKey: ${MINIO_S3_SECRETKEY}
        encrKey: ${MINIO_S3_ENCRKEY}
