---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: drawio
  namespace: drawio
spec:
  interval: 15m
  chart:
    spec:
      chart: drawio
      version: 14.2.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      stopAll: false
    ingress:
      main:
        enabled: true
        hosts:
          - host: drawio.${DOMAIN_0_LOCAL}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    credentials:
      minio:
        type: s3
        url: ${MINIO_S3_URL}
        bucket: ${MINIO_S3_BUCKET}-drawio
        accessKey: ${MINIO_S3_ACCESSKEY}
        secretKey: ${MINIO_S3_SECRETKEY}
        encrKey: ${MINIO_S3_ENCRKEY}
