---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 17.26.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      minio_credentials:
        type: s3
        url: "${S3_URL_MINIO}"
        bucket: "${S3_BUCKET}-immich"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        encrKey: "${S3_ENCRYPTION_KEY}"
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio_credentials
            dest:
              enabled: false
            src:
              enabled: true
    cnpg:
      main:
        backups:
          enabled: true
          credentials: minio_credentials
        recovery:
          method: object_store
          credentials: minio_credentials
    ingress:
      main:
        enabled: true
        hosts:
          - host: immich.test.arneklein.net
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
