---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: prowlarr
      version: 18.12.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      main:
        enabled: true
        hosts:
          - host: prowlarr.${DOMAIN_0_LOCAL}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
